<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Agen membantu guru mengelola absensi, jurnal pembelajaran, dokumentasi, dan laporan kelas dalam satu alur."><title>Agen · Jurnal Kelas</title><link rel="stylesheet" href="/assets/css/app.css"></head><body class="public-site">
<header class="landing-nav"><a class="public-brand" href="/"><span>A</span><div><strong>AGEN</strong><small>Jurnal Kelas</small></div></a><nav aria-label="Navigasi landing page"><a href="#fitur">Fitur</a><a href="#alur">Cara kerja</a><a href="#tentang">Tentang</a></nav><a class="public-login" href="/login">Masuk <span>→</span></a></header>
<main><section class="hero"><div class="hero-copy reveal"><span class="public-kicker"><i></i> Platform kerja kelas untuk guru</span><h1>Kelola kelas.<br><em>Lebih ringan.</em></h1><p>Absensi, jurnal pembelajaran, dokumentasi, dan laporan tersusun dalam satu alur kerja yang ringkas.</p><div class="hero-actions"><a class="hero-primary" href="/login">Mulai bekerja <span>→</span></a><a class="hero-secondary" href="#fitur">Lihat fitur</a></div><div class="hero-trust"><span><b>✓</b> Satu akun sekolah</span><span><b>✓</b> Data tersinkron</span><span><b>✓</b> Aman & tercatat</span></div></div>
<div class="hero-visual reveal delay-1" aria-label="Pratinjau dashboard Agen"><div class="mock-window"><div class="mock-top"><span></span><i></i><i></i><i></i></div><div class="mock-app"><aside><b>A</b><span class="on"></span><span></span><span></span><span></span></aside><div><div class="mock-title"><i></i><i></i></div><div class="mock-metrics"><span><b>12</b><i></i></span><span><b>3</b><i></i></span><span><b>98%</b><i></i></span></div><div class="mock-chart"><i></i><svg viewBox="0 0 440 120" preserveAspectRatio="none"><path d="M0 100 C55 92 60 45 115 64 S185 103 230 48 S310 22 345 54 S405 30 440 18"/></svg></div><div class="mock-rows"><i></i><i></i><i></i></div></div></div></div><span class="visual-badge badge-one"><b>✓</b> Absensi tersimpan</span><span class="visual-badge badge-two"><b>↑</b> Data tersinkron</span></div></section>
<section class="public-stats"><div><strong>1</strong><span>Alur kerja terpadu</span></div><div><strong>4</strong><span>Fitur utama guru</span></div><div><strong>24/7</strong><span>Akses data kelas</span></div><div><strong>100%</strong><span>Terhubung Portal Data</span></div></section>
<section class="feature-section" id="fitur"><div class="public-heading"><span>SEMUA YANG DIBUTUHKAN</span><h2>Dari masuk kelas sampai laporan.</h2><p>Tidak perlu berpindah aplikasi atau mencatat ulang data yang sama.</p></div><div class="feature-grid"><article><span>01</span><div class="feature-icon">✓</div><h3>Absensi kelas</h3><p>Catat kehadiran melalui checklist atau pemindaian barcode NISN.</p><a href="/login">Buka absensi →</a></article><article><span>02</span><div class="feature-icon">✎</div><h3>Jurnal pembelajaran</h3><p>Rekam topik, kegiatan, catatan guru, dan dokumentasi kelas.</p><a href="/login">Buat jurnal →</a></article><article><span>03</span><div class="feature-icon">▤</div><h3>Laporan otomatis</h3><p>Rekap bulanan siap ditinjau serta diekspor ke Excel dan PDF.</p><a href="/login">Lihat laporan →</a></article></div></section>
<section class="workflow" id="alur"><div class="workflow-copy"><span>ALUR SEDERHANA</span><h2>Tiga langkah,<br>satu pekerjaan selesai.</h2><p>Agen dirancang mengikuti urutan kerja guru yang sebenarnya.</p><a href="/login">Masuk ke Agen →</a></div><ol><li><b>01</b><div><strong>Buat absensi</strong><p>Pilih kelas, mata pelajaran, dan jam mengajar.</p></div></li><li><b>02</b><div><strong>Catat pembelajaran</strong><p>Lengkapi jurnal dan unggah dokumentasi.</p></div></li><li><b>03</b><div><strong>Finalisasi & laporkan</strong><p>Data otomatis masuk ke rekap bulanan.</p></div></li></ol></section>
<section class="public-cta" id="tentang"><span>Siap memulai?</span><h2>Lebih sedikit administrasi.<br>Lebih banyak waktu untuk mengajar.</h2><a href="/login">Masuk dengan Portal Data <b>→</b></a></section></main>
<footer class="landing-footer"><a class="public-brand" href="/"><span>A</span><div><strong>AGEN</strong><small>Jurnal Kelas</small></div></a><p>Bagian dari ekosistem Portal Data sekolah.</p><small>© <?= date('Y') ?> MAN 1 Palembang</small></footer></body></html>
