<?php
namespace App\Application\Report;
use App\Infrastructure\Database\Connection;
use Dompdf\Dompdf;
use Dompdf\Options;
use InvalidArgumentException;
use PDO;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
final class MonthlyReportService
{
    public function __construct(private readonly Connection $database){}
    public function data(array $filters,array $actor):array
    {
        $month=(int)($filters['month']??date('n'));$year=(int)($filters['year']??date('Y'));if($month<1||$month>12||$year<2020||$year>2100)throw new InvalidArgumentException('Periode laporan tidak valid.');$where=["j.teacher_public_id=:teacher",'MONTH(j.journal_date)=:month','YEAR(j.journal_date)=:year','j.deleted_at IS NULL'];$params=['teacher'=>$actor['portal_teacher_public_id'],'month'=>$month,'year'=>$year];foreach(['status'=>'j.status','classPublicId'=>'j.class_public_id','subjectPublicId'=>'s.public_id'] as $input=>$column)if(!empty($filters[$input])){$where[]=$column.'=:'.$input;$params[$input]=$filters[$input];}
        $sql="SELECT j.public_id AS publicId,j.journal_number AS journalNumber,j.journal_date AS journalDate,j.class_name_snapshot AS className,j.teacher_name_snapshot AS teacherName,j.period_start AS periodStart,j.period_end AS periodEnd,j.subject_name_snapshot AS subjectName,j.topic,j.status,COUNT(r.id) totalStudents,SUM(r.status='PRESENT') present,SUM(r.status='SICK') sick,SUM(r.status='PERMITTED') permitted,SUM(r.status='ABSENT') absent,SUM(r.status='NOT_PARTICIPATING') notParticipating FROM journals j JOIN subjects s ON s.id=j.subject_id JOIN attendance_sessions a ON a.id=j.attendance_session_id JOIN attendance_records r ON r.attendance_session_id=a.id WHERE ".implode(' AND ',$where).' GROUP BY j.id ORDER BY j.journal_date,j.period_start';$query=$this->database->pdo()->prepare($sql);$query->execute($params);$rows=$query->fetchAll();$summary=['totalJournals'=>count($rows),'totalSessions'=>count($rows),'totalStudents'=>0,'present'=>0,'sick'=>0,'permitted'=>0,'absent'=>0,'notParticipating'=>0,'draft'=>0,'attendancePercentage'=>0.0];foreach($rows as $row){foreach(['totalStudents','present','sick','permitted','absent','notParticipating'] as $key)$summary[$key]+=(int)$row[$key];if($row['status']==='DRAFT')$summary['draft']++;}$denominator=$summary['present']+$summary['sick']+$summary['permitted']+$summary['absent']+$summary['notParticipating'];$summary['attendancePercentage']=$denominator?round($summary['present']/$denominator*100,2):0;return ['period'=>['month'=>$month,'year'=>$year],'filters'=>$filters,'summary'=>$summary,'rows'=>$rows];
    }
    public function excel(array $report):string
    {
        $book=new Spreadsheet();$summary=$book->getActiveSheet();$summary->setTitle('Ringkasan');$summary->fromArray([['Laporan Jurnal MAN 1 Palembang'],['Periode',$report['period']['month'].'/'.$report['period']['year']],[],['Indikator','Nilai'],['Total jurnal',$report['summary']['totalJournals']],['Hadir',$report['summary']['present']],['Sakit',$report['summary']['sick']],['Izin',$report['summary']['permitted']],['Alpa',$report['summary']['absent']],['Tidak mengikuti',$report['summary']['notParticipating']],['Persentase hadir',$report['summary']['attendancePercentage'].'%']]);$detail=$book->createSheet();$detail->setTitle('Detail Jurnal');$headers=['No','Tanggal','Kelas','Guru','Jam','Mata Pelajaran','Pokok Bahasan','Jumlah Siswa','Hadir','Sakit','Izin','Alpa','Tidak Mengikuti','Status'];$detail->fromArray($headers,null,'A1');$line=2;foreach($report['rows'] as $index=>$row){$detail->fromArray([$index+1,$row['journalDate'],$row['className'],$row['teacherName'],$row['periodStart'].($row['periodEnd']!=$row['periodStart']?'–'.$row['periodEnd']:''),$row['subjectName'],$row['topic'],$row['totalStudents'],$row['present'],$row['sick'],$row['permitted'],$row['absent'],$row['notParticipating'],$row['status']],null,'A'.$line++);}$detail->freezePane('A2');$detail->getStyle('A1:N1')->getFont()->setBold(true)->getColor()->setARGB('FFFFFFFF');$detail->getStyle('A1:N1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FF147A55');foreach(range('A','N') as $column)$detail->getColumnDimension($column)->setAutoSize(true);$path=tempnam(sys_get_temp_dir(),'jurnal-xlsx-');(new Xlsx($book))->save($path);$content=(string)file_get_contents($path);@unlink($path);return $content;
    }
    public function pdf(array $report,array $actor):string
    {
        $options=new Options();$options->set('isRemoteEnabled',false);$pdf=new Dompdf($options);$rows='';foreach($report['rows'] as $i=>$row)$rows.='<tr><td>'.($i+1).'</td><td>'.e($row['journalDate']).'</td><td>'.e($row['className']).'</td><td>'.e($row['subjectName']).'</td><td>'.e($row['topic']).'</td><td>'.$row['present'].'</td><td>'.$row['sick'].'</td><td>'.$row['permitted'].'</td><td>'.$row['absent'].'</td><td>'.e($row['status']).'</td></tr>';$html='<style>@page{margin:25px}body{font-family:DejaVu Sans;font-size:10px}h1{text-align:center}table{width:100%;border-collapse:collapse}th,td{padding:5px;border:1px solid #999}th{background:#147a55;color:#fff}</style><h1>MAN 1 Palembang<br>Laporan Jurnal Bulanan</h1><p>Periode: '.e($report['period']['month'].'/'.$report['period']['year']).' · Dicetak oleh: '.e($actor['name']).' · '.date('d-m-Y H:i').'</p><p>Total jurnal: '.$report['summary']['totalJournals'].' · Kehadiran: '.$report['summary']['attendancePercentage'].'%</p><table><thead><tr><th>No</th><th>Tanggal</th><th>Kelas</th><th>Mapel</th><th>Pokok Bahasan</th><th>H</th><th>S</th><th>I</th><th>A</th><th>Status</th></tr></thead><tbody>'.$rows.'</tbody></table>';$pdf->loadHtml($html);$pdf->setPaper('A4','landscape');$pdf->render();return $pdf->output();
    }
}
