import{Body,ConflictException,Controller,Get,Injectable,NotFoundException,Param,Post,Req,UseGuards}from'@nestjs/common';
import{Prisma}from'@prisma/client';import{createHash,randomBytes}from'crypto';import{IsEmail,IsOptional}from'class-validator';import{ulid}from'ulid';
import{AdminAuthGuard}from'../../auth/guards/admin-auth.guard';import{CsrfGuard}from'../../auth/guards/csrf.guard';import{RolesGuard}from'../../auth/guards/roles.guard';import{SessionService}from'../../auth/session.service';import{normalizeUsername}from'../../auth/teacher-auth.service';import{Roles}from'../../common/decorators/roles.decorator';import{PrismaService}from'../../database/prisma.service';import{AuditService}from'../audit-logs/audit.service';import{TeacherAccountMailService}from'./teacher-account-mail.service';
class ProvisionDto{@IsOptional()@IsEmail()email?:string}const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
@Injectable()export class TeacherAccountsService{
 constructor(private db:PrismaService,private sessions:SessionService,private audit:AuditService,private mail:TeacherAccountMailService){}
 private async teacher(id:string){const t=await this.db.teacher.findFirst({where:{publicId:id,deletedAt:null},include:{account:true}});if(!t)throw new NotFoundException('Guru tidak ditemukan.');return t}
 private token(){const raw=randomBytes(32).toString('base64url');return{raw,data:{publicId:ulid(),tokenHash:hash(raw),expiresAt:new Date(Date.now()+24*3600_000)}}}
 private url(raw:string){const base=(process.env.APP_URL??'').replace(/\/$/,'');if(!base)throw new ConflictException('APP_URL belum dikonfigurasi.');return`${base}/teacher/setup-password?token=${encodeURIComponent(raw)}`}
 private async username(t:{nip:string|null;nuptk:string|null;employeeNumber:string|null}){for(const value of[t.nip,t.nuptk,t.employeeNumber]){if(!value)continue;const username=normalizeUsername(value);if(!await this.db.teacherAccount.findUnique({where:{username},select:{id:true}}))return username}throw new ConflictException('NIP, NUPTK, atau nomor pegawai yang dapat dijadikan username belum tersedia atau sudah digunakan.')}
 async one(id:string){const t=await this.teacher(id),a=t.account;if(!a)return null;return{publicId:a.publicId,username:a.username,email:a.email,status:a.status,mustChangePassword:a.mustChangePassword,failedLoginAttempts:a.failedLoginAttempts,lockedUntil:a.lockedUntil,lastLoginAt:a.lastLoginAt,passwordChangedAt:a.passwordChangedAt,activatedAt:a.activatedAt,disabledAt:a.disabledAt,createdAt:a.createdAt,updatedAt:a.updatedAt,passwordConfigured:Boolean(a.passwordHash)}}
 async provision(id:string,d:ProvisionDto,actor:string){const t=await this.teacher(id);if(t.status!=='ACTIVE')throw new ConflictException('Akun hanya dapat dibuat untuk guru aktif.');if(t.account)throw new ConflictException('Guru sudah memiliki akun.');const username=await this.username(t),email=d.email?.trim().toLowerCase()||t.email?.trim().toLowerCase()||null,setup=this.token(),setupUrl=this.url(setup.raw);try{const result=await this.db.$transaction(async tx=>{const account=await tx.teacherAccount.create({data:{publicId:ulid(),teacherId:t.id,username,email,passwordHash:null,status:'PENDING_SETUP'}});await tx.teacherPasswordSetupToken.create({data:{...setup.data,teacherAccountId:account.id}});await this.audit.write({actorPublicId:actor,action:'TEACHER_ACCOUNT_PROVISIONED',entityType:'TeacherAccount',entityPublicId:account.publicId,newValues:{teacherPublicId:t.publicId,username:account.username,email:account.email,status:account.status}},tx);return{account:{publicId:account.publicId,username:account.username,email:account.email,status:account.status}}});const mailStatus=await this.mail.sendSetup({to:email,fullName:t.fullName,username,setupUrl});return{...result,passwordSetupUrl:setupUrl,mailStatus}}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')throw new ConflictException('Username atau email sudah digunakan.');throw e}}
 async regenerate(id:string,actor:string){const t=await this.teacher(id),a=t.account;if(!a)throw new NotFoundException('Akun guru belum tersedia.');if(a.status!=='PENDING_SETUP')throw new ConflictException('Token setup hanya untuk akun yang menunggu setup.');const setup=this.token(),setupUrl=this.url(setup.raw),now=new Date();await this.db.$transaction(async tx=>{await tx.teacherPasswordSetupToken.updateMany({where:{teacherAccountId:a.id,usedAt:null},data:{usedAt:now}});await tx.teacherPasswordSetupToken.create({data:{...setup.data,teacherAccountId:a.id}});await this.audit.write({actorPublicId:actor,action:'SETUP_TOKEN_REGENERATED',entityType:'TeacherAccount',entityPublicId:a.publicId},tx)});const mailStatus=await this.mail.sendSetup({to:a.email??t.email,fullName:t.fullName,username:a.username,setupUrl});return{passwordSetupUrl:setupUrl,mailStatus}}
 async disable(id:string,actor:string){const t=await this.teacher(id),a=t.account;if(!a)throw new NotFoundException('Akun guru belum tersedia.');await this.db.$transaction(async tx=>{await tx.teacherAccount.update({where:{id:a.id},data:{status:'DISABLED',disabledAt:new Date()}});await this.sessions.revokeAllTeacher(a.id,tx);await this.audit.write({actorPublicId:actor,action:'TEACHER_ACCOUNT_DISABLED',entityType:'TeacherAccount',entityPublicId:a.publicId},tx)})}
 async enable(id:string,actor:string){const t=await this.teacher(id),a=t.account;if(!a)throw new NotFoundException('Akun guru belum tersedia.');if(t.status!=='ACTIVE'||!a.passwordHash)throw new ConflictException('Guru harus aktif dan password sudah diatur.');await this.db.teacherAccount.update({where:{id:a.id},data:{status:'ACTIVE',disabledAt:null}});await this.audit.write({actorPublicId:actor,action:'TEACHER_ACCOUNT_ENABLED',entityType:'TeacherAccount',entityPublicId:a.publicId})}
 async unlock(id:string,actor:string){const t=await this.teacher(id),a=t.account;if(!a)throw new NotFoundException('Akun guru belum tersedia.');if(a.status!=='LOCKED'||t.status!=='ACTIVE')throw new ConflictException('Akun tidak dapat dibuka.');await this.db.teacherAccount.update({where:{id:a.id},data:{status:'ACTIVE',failedLoginAttempts:0,lockedUntil:null}});await this.audit.write({actorPublicId:actor,action:'TEACHER_ACCOUNT_UNLOCKED',entityType:'TeacherAccount',entityPublicId:a.publicId})}
 async revoke(id:string,actor:string){const t=await this.teacher(id),a=t.account;if(!a)throw new NotFoundException('Akun guru belum tersedia.');await this.sessions.revokeAllTeacher(a.id);await this.audit.write({actorPublicId:actor,action:'TEACHER_SESSIONS_REVOKED',entityType:'TeacherAccount',entityPublicId:a.publicId})}
}
@UseGuards(AdminAuthGuard,CsrfGuard,RolesGuard)@Controller('teachers/:publicId/account')export class TeacherAccountsController{constructor(private s:TeacherAccountsService){}@Roles('SUPER_ADMIN','DATA_ADMIN','AUDITOR')@Get()async one(@Param('publicId')id:string){return{message:'Akun guru berhasil diambil.',data:await this.s.one(id)}}@Roles('SUPER_ADMIN','DATA_ADMIN')@Post()async provision(@Param('publicId')id:string,@Body()d:ProvisionDto,@Req()r:any){return{message:'Akun guru berhasil dibuat.',data:await this.s.provision(id,d,r.user.publicId)}}@Roles('SUPER_ADMIN','DATA_ADMIN')@Post('setup-token')async token(@Param('publicId')id:string,@Req()r:any){return{message:'Token setup berhasil dibuat ulang.',data:await this.s.regenerate(id,r.user.publicId)}}@Roles('SUPER_ADMIN','DATA_ADMIN')@Post('disable')async disable(@Param('publicId')id:string,@Req()r:any){await this.s.disable(id,r.user.publicId);return{message:'Akun guru dinonaktifkan.',data:null}}@Roles('SUPER_ADMIN','DATA_ADMIN')@Post('enable')async enable(@Param('publicId')id:string,@Req()r:any){await this.s.enable(id,r.user.publicId);return{message:'Akun guru diaktifkan.',data:null}}@Roles('SUPER_ADMIN','DATA_ADMIN')@Post('unlock')async unlock(@Param('publicId')id:string,@Req()r:any){await this.s.unlock(id,r.user.publicId);return{message:'Kunci akun guru dibuka.',data:null}}@Roles('SUPER_ADMIN','DATA_ADMIN')@Post('revoke-sessions')async revoke(@Param('publicId')id:string,@Req()r:any){await this.s.revoke(id,r.user.publicId);return{message:'Session guru dicabut.',data:null}}}
