import{AlertTriangle,CheckCircle2,Code2,Database,ExternalLink,KeyRound,LockKeyhole,School,ShieldCheck,Users}from'lucide-react';
import{Link}from'react-router-dom';import{PageHeader,SectionCard}from'../components/management';
const base='/api/v1',issuer=location.port==='5173'?'http://localhost:3000/oidc':`${location.origin}/oidc`;type Endpoint=[method:string,path:string,description:string];
const accounts=[['Administrator','Email + password','Session cookie admin','Master data sesuai role'],['Guru','Username otomatis + password','Session guru dan OIDC','Portal guru dan aplikasi yang diberikan'],['Siswa','Belum tersedia','—','Hanya data master; belum dapat login'],['Aplikasi/server','Belum tersedia','—','Belum ada API key atau service account']];
const teacherApi:Endpoint[]=[['GET','/auth/teacher/me','Periksa sesi guru'],['GET','/teacher/profile','Ambil profil guru'],['PATCH','/teacher/profile','Ubah email, telepon, alamat'],['POST','/teacher/profile/photo','Unggah foto (multipart)'],['POST','/teacher/profile/change-password','Ganti password'],['GET','/teacher/sessions','Daftar sesi aktif'],['DELETE','/teacher/sessions/:publicId','Cabut satu sesi'],['POST','/teacher/sessions/logout-all','Cabut seluruh sesi']];
const adminApi:Endpoint[]=[['GET','/students','Daftar siswa'],['GET','/students/:publicId','Detail siswa'],['GET','/students/by-nisn/:nisn','Cari berdasarkan NISN'],['GET','/students/:publicId/enrollments','Riwayat kelas siswa'],['GET','/teachers','Daftar guru'],['GET','/teachers/:publicId','Detail guru'],['GET','/classes','Daftar kelas'],['GET','/classes/:publicId/students','Anggota kelas'],['GET','/academic-years','Daftar tahun ajaran'],['GET','/semesters','Daftar semester']];
function Code({lines}:{lines:string[]}){return <pre className="code-block"><code>{lines.join('\n')}</code></pre>}
function Endpoints({rows}:{rows:Endpoint[]}){return <div className="docs-table"><table><thead><tr><th>Method</th><th>Endpoint</th><th>Keterangan</th></tr></thead><tbody>{rows.map(([method,path,text])=><tr key={method+path}><td><span className={`method ${method.toLowerCase()}`}>{method}</span></td><td><code>{base}{path}</code></td><td>{text}</td></tr>)}</tbody></table></div>}
export function GuidePage(){return <div className="page guide-page docs-page">
 <PageHeader title="Dokumentasi Portal Data" description="Panduan operasional, integrasi SSO OpenID Connect, dan referensi REST API" action={<Link className="button" to="/sso/applications">Kelola aplikasi SSO</Link>}/>
 <nav className="guide-index" aria-label="Daftar isi"><a href="#overview">Ikhtisar</a><a href="#accounts">Akun</a><a href="#sso">SSO / OIDC</a><a href="#integration">Integrasi</a><a href="#api">REST API</a><a href="#errors">Error</a><a href="#security">Keamanan</a></nav>
 <section id="overview" className="docs-hero"><div><span className="eyebrow">PORTAL DATA · TECHNICAL GUIDE</span><h2>Satu identitas guru untuk seluruh aplikasi sekolah</h2><p>Portal Data adalah sumber data utama sekaligus Identity Provider OpenID Connect. Aplikasi seperti Jurnal Kelas mengarahkan guru ke Portal Data, menerima authorization code, lalu memverifikasi ID token RS256.</p><div className="docs-actions"><a href={`${issuer}/.well-known/openid-configuration`} target="_blank" rel="noreferrer">OpenID configuration <ExternalLink size={14}/></a><a href="#quickstart">Mulai integrasi</a></div></div><div className="docs-facts"><div><span>Protocol</span><strong>OIDC + OAuth 2.0</strong></div><div><span>Flow</span><strong>Authorization Code</strong></div><div><span>Client</span><strong>Public + PKCE S256</strong></div><div><span>Signing</span><strong>RS256</strong></div></div></section>
 <SectionCard title="Model akun dan batas akses" className="guide-card docs-section"><div id="accounts" className="docs-copy"><p>Data profil dan akun login dipisahkan. Keberadaan data guru atau siswa tidak otomatis berarti pengguna bisa login.</p><div className="docs-table"><table><thead><tr><th>Subjek</th><th>Login</th><th>Autentikasi</th><th>Akses</th></tr></thead><tbody>{accounts.map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={cell}>{i===0?<strong>{cell}</strong>:cell}</td>)}</tr>)}</tbody></table></div><p className="docs-callout warning"><AlertTriangle size={18}/><span><strong>Akun siswa belum diimplementasikan.</strong> Endpoint siswa adalah API pengelolaan data untuk administrator, bukan API login atau portal siswa.</span></p></div></SectionCard>
 <SectionCard title="Provisioning akun guru" className="guide-card docs-section"><ol className="docs-steps"><li><span>1</span><div><strong>Lengkapi profil guru</strong><p>Isi NIP, NUPTK, atau nomor pegawai dan email untuk pengiriman aktivasi.</p></div></li><li><span>2</span><div><strong>Buat akun Portal</strong><p>Username dipilih otomatis dari NIP → NUPTK → nomor pegawai yang belum digunakan.</p></div></li><li><span>3</span><div><strong>Guru melakukan aktivasi</strong><p>Tautan sekali pakai dikirim melalui SMTP, berlaku 24 jam, lalu guru membuat password sendiri.</p></div></li><li><span>4</span><div><strong>Berikan akses aplikasi</strong><p>Tambahkan guru ke aplikasi SSO. Tanpa grant aktif, login aplikasi ditolak.</p></div></li></ol></SectionCard>
 <div id="sso" className="docs-heading"><span><KeyRound size={20}/></span><div><h2>Single Sign-On (OIDC)</h2><p>Konfigurasi Identity Provider untuk aplikasi sekolah.</p></div></div>
 <div className="guide-grid"><SectionCard title="Endpoint discovery" className="guide-card"><div className="docs-copy"><dl className="config-list"><div><dt>Issuer</dt><dd><code>http://localhost:3000/oidc</code></dd></div><div><dt>Discovery</dt><dd><code>/oidc/.well-known/openid-configuration</code></dd></div><div><dt>Authorization</dt><dd><code>/oidc/auth</code></dd></div><div><dt>Token</dt><dd><code>/oidc/token</code></dd></div><div><dt>JWKS</dt><dd><code>/oidc/jwks</code></dd></div></dl><p className="docs-callout"><CheckCircle2 size={17}/> Ambil endpoint dari discovery document dan jangan hard-code selain issuer.</p></div></SectionCard><SectionCard title="Scope dan claims" className="guide-card"><div className="docs-copy"><div className="scope-list"><code>openid</code><code>profile</code><code>email</code><code>portal_role</code></div><Code lines={['{','  "sub": "01...ACCOUNT_PUBLIC_ID",','  "name": "Nama Guru",','  "preferred_username": "1987...",','  "email": "guru@sekolah.id",','  "portal_teacher_id": "01...TEACHER_PUBLIC_ID",','  "portal_role": "TEACHER"','}']}/><p><code>sub</code> adalah public ID akun yang stabil. Jangan memakai nama atau email sebagai primary key.</p></div></SectionCard></div>
 <SectionCard title="Quick start integrasi aplikasi" className="guide-card docs-section"><div id="quickstart" className="docs-copy"><ol><li>Buat aplikasi pada <Link to="/sso/applications">Aplikasi SSO</Link> dan daftarkan redirect URI persis.</li><li>Simpan <code>clientId</code>. Public client tidak memiliki client secret.</li><li>Buat <code>code_verifier</code> acak dan challenge SHA-256 Base64URL.</li><li>Kirim browser ke authorization endpoint dengan state dan nonce acak.</li><li>Di callback, validasi state lalu tukarkan code memakai verifier asli.</li><li>Validasi signature, issuer, audience, expiry, dan nonce ID token melalui JWKS.</li></ol><Code lines={['GET /oidc/auth?','  client_id=portal_jurnal-kelas_xxx&','  response_type=code&','  redirect_uri=https%3A%2F%2Fjurnal.example.sch.id%2Fauth%2Fcallback&','  scope=openid%20profile%20email%20portal_role&','  state=<random>&nonce=<random>&','  code_challenge=<S256_CHALLENGE>&code_challenge_method=S256']}/><Code lines={['POST /oidc/token','Content-Type: application/x-www-form-urlencoded','','grant_type=authorization_code&','client_id=portal_jurnal-kelas_xxx&','code=<authorization_code>&','redirect_uri=https%3A%2F%2Fjurnal.example.sch.id%2Fauth%2Fcallback&','code_verifier=<original_verifier>']}/></div></SectionCard>
 <SectionCard title="Checklist Jurnal Kelas" className="guide-card docs-section"><div id="integration" className="check-grid">{['Gunakan library OIDC resmi untuk framework aplikasi','Simpan state, nonce, dan PKCE verifier pada session server','Redirect URI harus identik dengan konfigurasi Portal Data','Validasi ID token; jangan hanya decode JWT','Petakan pengguna dengan sub atau portal_teacher_id','Tolak akses jika portal_role tidak sesuai','Buat session aplikasi sendiri setelah callback berhasil','Sediakan logout lokal dan redirect pasca-logout'].map(item=><div key={item}><CheckCircle2 size={17}/><span>{item}</span></div>)}</div></SectionCard>
 <div id="api" className="docs-heading"><span><Code2 size={20}/></span><div><h2>REST API</h2><p>Base URL development: <code>http://localhost:3000/api/v1</code></p></div></div>
 <SectionCard title="Autentikasi API" className="guide-card docs-section"><div className="docs-copy"><p>REST API memakai cookie session. Request mutasi wajib membawa nilai cookie CSRF pada header <code>X-CSRF-Token</code>. Session guru dan admin terpisah.</p><div className="auth-grid"><article><LockKeyhole/><strong>Admin</strong><code>portal_session</code><code>portal_csrf</code></article><article><Users/><strong>Guru</strong><code>portal_teacher_session</code><code>portal_teacher_csrf</code></article><article><Database/><strong>Bearer token</strong><span>Belum didukung untuk API manajemen</span></article></div><Code lines={['curl -X PATCH http://localhost:3000/api/v1/teacher/profile \\','  -b cookies.txt -c cookies.txt \\','  -H \'Content-Type: application/json\' \\','  -H \'X-CSRF-Token: <nilai-cookie-portal_teacher_csrf>\' \\','  -d \'{"phone":"081234567890","address":"Alamat baru"}\'']}/></div></SectionCard>
 <div className="guide-grid api-grids"><SectionCard title="API mandiri guru" className="guide-card"><Endpoints rows={teacherApi}/></SectionCard><SectionCard title="API data sekolah (admin)" className="guide-card"><Endpoints rows={adminApi}/></SectionCard></div>
 <SectionCard title="Format respons" className="guide-card docs-section"><div className="guide-grid response-grid"><Code lines={['{','  "success": true,','  "message": "Siswa berhasil diambil.",','  "data": { "publicId": "01..." },','  "meta": { "page": 1, "perPage": 25, "total": 690 }','}']}/><Code lines={['{','  "success": false,','  "message": "Data tidak valid.",','  "errors": [{ "field": "nisn", "message": "NISN wajib 10 digit." }]','}']}/></div><p className="docs-callout warning"><AlertTriangle size={17}/> Selalu gunakan <code>publicId</code>. Internal numeric ID bukan bagian kontrak API.</p></SectionCard>
 <SectionCard title="Status HTTP dan penanganan error" className="guide-card docs-section"><div id="errors" className="status-grid">{[['400','Payload atau parameter tidak valid'],['401','Session tidak ada atau kedaluwarsa'],['403','CSRF salah, role kurang, atau akses aplikasi belum diberikan'],['404','Resource/publicId tidak ditemukan'],['409','Konflik status, identifier duplikat, atau operasi sudah dilakukan'],['429','Rate limit terlampaui'],['500','Kesalahan internal; catat request ID dan periksa log']].map(([status,text])=><div key={status}><strong>{status}</strong><span>{text}</span></div>)}</div></SectionCard>
 <SectionCard title="Keamanan dan produksi" className="guide-card docs-section"><div id="security" className="security-grid"><article><ShieldCheck/><div><strong>HTTPS wajib</strong><p>Gunakan issuer, redirect URI, dan secure cookie berbasis HTTPS. HTTP hanya untuk localhost.</p></div></article><article><KeyRound/><div><strong>Kunci signing persisten</strong><p>Isi <code>OIDC_JWKS_JSON</code>. Key sementara membuat token lama gagal setelah restart.</p></div></article><article><School/><div><strong>Least privilege</strong><p>Berikan akses aplikasi hanya kepada guru yang membutuhkan dan cabut jika tidak relevan.</p></div></article><article><AlertTriangle/><div><strong>Rahasia</strong><p>Jangan commit password, token, SMTP App Password, cookie, atau private JWK ke repository.</p></div></article></div></SectionCard>
 </div>}
