<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?= $csrf ?>"><title><?= $title ?></title><link rel="stylesheet" href="/assets/css/app.css"><link rel="stylesheet" href="/assets/css/attendance.css"><link rel="stylesheet" href="/assets/css/journals.css"></head>
<body><div class="app-shell">
<aside class="app-sidebar"><a class="brand" href="/dashboard" aria-label="Agen, beranda"><span class="brand-mark">A</span><span><strong>AGEN</strong><small>Jurnal kelas</small></span></a><nav class="side-nav" aria-label="Navigasi utama"><a class="active" href="/dashboard"><span>01</span>Ikhtisar</a><a href="/attendance/create"><span>02</span>Absensi</a><a href="/journals"><span>03</span>Jurnal</a><a href="/reports/monthly"><span>04</span>Laporan</a></nav><div class="sidebar-user"><span class="avatar"><?= e(mb_strtoupper(mb_substr($user['name'],0,2))) ?></span><div><strong><?= e($user['name']) ?></strong><small>@<?= e($user['username']) ?></small></div></div><form method="post" action="/logout"><input type="hidden" name="_token" value="<?= $csrf ?>"><button class="quiet logout" type="submit">Keluar dari akun</button></form></aside>
<main class="dashboard-main"><header class="dashboard-head reveal"><div><p class="eyebrow">Selamat datang kembali</p><h1>Halo, <?= e(explode(' ',trim($user['name']))[0]) ?>.</h1><p class="subtle">Kelola kelas hari ini tanpa langkah yang bertele-tele.</p></div><div class="sync-state"><i></i><span>Data tersinkron</span><time><?= $reference['synced_at']?e(date('d M, H:i',$reference['synced_at'])):'Belum tersedia' ?></time></div></header>
<section class="command-grid reveal delay-1" aria-label="Aksi cepat"><a class="command primary-command" href="/attendance/create"><span class="command-index">01</span><div><small>Mulai dari sini</small><strong>Absensi kelas</strong><p>Buat sesi dan scan barcode NISN siswa.</p></div><b aria-hidden="true">↗</b></a><a class="command" href="/journals/create"><span class="command-index">02</span><div><small>Catat pembelajaran</small><strong>Tambah jurnal</strong><p>Isi kegiatan dan unggah dokumentasi.</p></div><b aria-hidden="true">↗</b></a><a class="command compact" href="/journals"><span>Semua jurnal</span><b aria-hidden="true">→</b></a><a class="command compact" href="/reports/monthly"><span>Laporan bulanan</span><b aria-hidden="true">→</b></a></section>
<section class="dashboard-section reveal delay-2"><div class="section-heading"><div><p class="eyebrow">Bulan berjalan</p><h2>Ringkasan kerja</h2></div><span><?= e(date('F Y')) ?></span></div><div class="metric-strip"><article><small>Jurnal hari ini</small><strong><?= $dashboard['metrics']['today'] ?></strong><span>entri</span></article><article><small>Perlu diselesaikan</small><strong><?= $dashboard['metrics']['draft'] ?></strong><span>draft</span></article><article><small>Jurnal bulan ini</small><strong><?= $dashboard['metrics']['month'] ?></strong><span>entri</span></article><article><small>Kehadiran tercatat</small><strong><?= $dashboard['attendance']['PRESENT'] ?></strong><span>siswa</span></article><article><small>Kelas aktif</small><strong><?= count($reference['classes']) ?></strong><span>kelas</span></article></div></section>
<section class="dashboard-section recent-section reveal delay-3"><div class="section-heading"><div><p class="eyebrow">Terbaru</p><h2>Aktivitas jurnal</h2></div><a href="/journals">Lihat semua →</a></div><div class="recent-list"><?php if(!$dashboard['recent']):?><div class="empty-state"><span>Belum ada jurnal</span><p>Mulai dengan membuat sesi absensi untuk kelas hari ini.</p><a href="/attendance/create">Buat absensi</a></div><?php else:foreach($dashboard['recent'] as $index=>$item):?><a class="recent-row" href="/journals/<?= e($item['publicId']) ?>"><span class="row-number"><?= str_pad((string)($index+1),2,'0',STR_PAD_LEFT) ?></span><span class="row-main"><strong><?= e($item['className']) ?></strong><small><?= e($item['subjectName']) ?></small></span><time><?= e(date('d M Y',strtotime($item['journalDate']))) ?></time><span class="status status-<?= strtolower(e($item['status'])) ?>"><?= e($item['status']) ?></span><b aria-hidden="true">→</b></a><?php endforeach;endif?></div></section>
</main></div></body></html>
