<?php
declare(strict_types=1);
namespace Cbt\Repositories;
use Cbt\Support\Id;
use PDO;
final class AdminRepository
{
 public function __construct(private PDO$db){}
 public function dashboard():array{return['totalSiswa'=>(int)$this->db->query('SELECT COUNT(*) FROM students WHERE is_active=1')->fetchColumn(),'totalUjianAktif'=>(int)$this->db->query("SELECT COUNT(*) FROM exams WHERE status='ACTIVE'")->fetchColumn(),'totalSubmit'=>(int)$this->db->query('SELECT COUNT(*) FROM exam_results')->fetchColumn(),'totalPelanggaran'=>(int)$this->db->query('SELECT COUNT(*) FROM violations')->fetchColumn()];}
 public function references():array{return['teachers'=>$this->db->query("SELECT id,portal_teacher_id,nip,nuptk,name_snapshot name FROM teachers WHERE status='ACTIVE' ORDER BY name_snapshot")->fetchAll(),'subjects'=>$this->db->query("SELECT id,public_id,code,name FROM subjects WHERE status='ACTIVE' ORDER BY name")->fetchAll(),'classes'=>$this->db->query("SELECT portal_class_id,code,name,grade,academic_year FROM portal_classes WHERE status='ACTIVE' ORDER BY grade,code")->fetchAll(),'academic_years'=>$this->db->query('SELECT portal_academic_year_id,name,is_active FROM portal_academic_years ORDER BY name DESC')->fetchAll(),'semesters'=>$this->db->query('SELECT portal_semester_id,portal_academic_year_id,type,academic_year,is_active FROM portal_semesters ORDER BY academic_year DESC,type')->fetchAll()];}
 public function exams():array{$studentJoin=$this->hasTable('exam_target_students')?' LEFT JOIN exam_target_students ts ON ts.exam_id=e.id':'';$studentCount=$studentJoin?'COUNT(DISTINCT ts.student_id)':'0';$rows=$this->db->query('SELECT e.*,s.code kode_mapel,s.name nama_mapel,GROUP_CONCAT(DISTINCT x.portal_class_id ORDER BY x.portal_class_id) classes,GROUP_CONCAT(DISTINCT COALESCE(pc.name,pc.code,x.portal_class_id) ORDER BY COALESCE(pc.name,pc.code)) class_names,'.$studentCount.' target_student_count FROM exams e LEFT JOIN subjects s ON s.id=e.subject_id LEFT JOIN exam_target_classes x ON x.exam_id=e.id LEFT JOIN portal_classes pc ON pc.portal_class_id=x.portal_class_id'.$studentJoin.' GROUP BY e.id,s.code,s.name ORDER BY e.id DESC')->fetchAll();return array_map(fn($e)=>['id'=>(int)$e['id'],'subject_id'=>$e['subject_id']?(int)$e['subject_id']:null,'kode_mapel'=>$e['kode_mapel'],'nama_mapel'=>$e['nama_mapel'],'portal_academic_year_id'=>$e['portal_academic_year_id'],'portal_semester_id'=>$e['portal_semester_id'],'nama_ujian'=>$e['name'],'tingkat'=>$e['grade'],'kelas_target'=>$e['classes']??'','nama_kelas_target'=>$e['class_names']??'','target_student_count'=>(int)$e['target_student_count'],'durasi_menit'=>(int)$e['duration_minutes'],'sesi'=>(int)$e['session_number'],'tanggal_ujian'=>substr($e['starts_at'],0,10),'tanggal_mulai'=>substr($e['starts_at'],0,10),'jam_selesai'=>substr($e['ends_at'],11,5),'jam_mulai'=>substr($e['starts_at'],11,5),'tanggal_selesai'=>substr($e['ends_at'],0,10),'tahun_ajaran'=>$e['academic_year'],'semester'=>$e['semester']==='ODD'?'Ganjil':'Genap','status_aktif'=>$e['status']==='ACTIVE'],$rows);}
 private function hasTable(string$table):bool{try{$s=$this->db->query('SHOW TABLES LIKE '.$this->db->quote($table));return(bool)$s->fetchColumn();}catch(\PDOException){return false;}}
 public function examForFollowUp(int$id):?array{$s=$this->db->prepare('SELECT e.* FROM exams e WHERE e.id=:id AND EXISTS(SELECT 1 FROM questions q WHERE q.exam_id=e.id AND q.status=\'ACTIVE\') LIMIT 1');$s->execute(['id'=>$id]);return$s->fetch()?:null;}
 public function cloneFollowUpExam(array$source,array$studentIds,string$name,string$type,string$starts,string$ends,int$actor,bool$active,string$room='',string$notes=''):array{if($active)\Cbt\Support\ExamWindow::assertCommonDay($this->db,$starts,$source['academic_year'],$source['semester']);$p=['public'=>Id::ulid(),'subject'=>$source['subject_id'],'year_id'=>$source['portal_academic_year_id'],'semester_id'=>$source['portal_semester_id'],'name'=>$name,'grade'=>$source['grade'],'duration'=>$source['duration_minutes'],'session'=>$source['session_number'],'starts'=>$starts,'ends'=>$ends,'year'=>$source['academic_year'],'semester'=>$source['semester'],'status'=>$active?'ACTIVE':'INACTIVE','actor'=>$actor];$this->db->prepare('INSERT INTO exams(public_id,subject_id,portal_academic_year_id,portal_semester_id,name,grade,duration_minutes,session_number,starts_at,ends_at,academic_year,semester,status,created_by) VALUES(:public,:subject,:year_id,:semester_id,:name,:grade,:duration,:session,:starts,:ends,:year,:semester,:status,:actor)')->execute($p);$examId=(int)$this->db->lastInsertId();$this->db->prepare('INSERT INTO exam_follow_up_meta(exam_id,source_exam_id,type,room,notes) VALUES(:exam,:source,:type,:room,:notes)')->execute(['exam'=>$examId,'source'=>$source['id'],'type'=>$type,'room'=>$room?:null,'notes'=>$notes?:null]);$valid=$this->db->prepare('SELECT id FROM students WHERE id=:id AND is_active=1 AND grade_snapshot=:grade');$insert=$this->db->prepare('INSERT INTO exam_target_students(exam_id,student_id) VALUES(:exam,:student)');$count=0;foreach($studentIds as$id){$valid->execute(['id'=>$id,'grade'=>$source['grade']]);if($valid->fetchColumn()){$insert->execute(['exam'=>$examId,'student'=>$id]);$count++;}}if(!$count)throw new \UnexpectedValueException('Tidak ada siswa aktif dengan tingkat yang sesuai ujian asal.');if($type==='REMEDIAL'){$update=$this->db->prepare("UPDATE exam_retake_candidates SET status='SCHEDULED' WHERE source_exam_id=:exam AND student_id=:student AND status='APPROVED'");foreach($studentIds as$id)$update->execute(['exam'=>$source['id'],'student'=>$id]);}$questions=$this->db->prepare('SELECT * FROM questions WHERE exam_id=:id AND status=\'ACTIVE\'');$questions->execute(['id'=>$source['id']]);$copy=$this->db->prepare('INSERT INTO questions(public_id,exam_id,question_text,option_a,option_b,option_c,option_d,option_e,correct_answer,points,status) VALUES(:public,:exam,:text,:a,:b,:c,:d,:e,:answer,:points,\'ACTIVE\')');foreach($questions->fetchAll() as$q)$copy->execute(['public'=>Id::ulid(),'exam'=>$examId,'text'=>$q['question_text'],'a'=>$q['option_a'],'b'=>$q['option_b'],'c'=>$q['option_c'],'d'=>$q['option_d'],'e'=>$q['option_e'],'answer'=>$q['correct_answer'],'points'=>$q['points']]);return['id'=>$examId,'name'=>$name,'type'=>$type,'targeted_students'=>$count];}
 public function makeUpCandidates():array{if(!$this->hasTable('exam_target_students')||!$this->hasTable('exam_follow_up_meta'))return[];$sql="SELECT s.id student_id,s.nisn,s.name_snapshot name,s.class_snapshot class,s.grade_snapshot grade,e.id exam_id,e.name exam_name,COALESCE(sub.name,'-') subject_name,e.ends_at normal_ends_at,CASE WHEN EXISTS(SELECT 1 FROM exam_follow_up_meta m JOIN exam_target_students ts ON ts.exam_id=m.exam_id AND ts.student_id=s.id JOIN exam_attempts fa ON fa.exam_id=m.exam_id AND fa.student_id=s.id WHERE m.source_exam_id=e.id AND m.type='SUSULAN' AND fa.status='COMPLETED') THEN 'SELESAI' WHEN EXISTS(SELECT 1 FROM exam_follow_up_meta m JOIN exam_target_students ts ON ts.exam_id=m.exam_id AND ts.student_id=s.id WHERE m.source_exam_id=e.id AND m.type='SUSULAN') THEN 'DIJADWALKAN' ELSE 'BELUM_UJIAN' END status_susulan FROM exams e JOIN students s ON s.is_active=1 AND s.grade_snapshot=e.grade LEFT JOIN subjects sub ON sub.id=e.subject_id WHERE NOT EXISTS(SELECT 1 FROM exam_follow_up_meta m WHERE m.exam_id=e.id) AND e.ends_at<UTC_TIMESTAMP(3) AND (NOT EXISTS(SELECT 1 FROM exam_target_classes c WHERE c.exam_id=e.id) OR EXISTS(SELECT 1 FROM exam_target_classes c WHERE c.exam_id=e.id AND c.portal_class_id=s.portal_class_id)) AND NOT EXISTS(SELECT 1 FROM exam_attempts a WHERE a.exam_id=e.id AND a.student_id=s.id) ORDER BY e.ends_at DESC,s.name_snapshot";return$this->db->query($sql)->fetchAll();}
 public function followUpCandidates():array{if(!$this->hasTable('exam_retake_candidates'))return[];$sql="SELECT a.student_id,a.exam_id,a.violation_count,s.nisn,s.name_snapshot name,s.class_snapshot class,s.grade_snapshot grade,e.name exam_name,e.ends_at source_ends_at,CASE WHEN EXISTS(SELECT 1 FROM exam_follow_up_meta fm JOIN exam_target_students fts ON fts.exam_id=fm.exam_id AND fts.student_id=a.student_id JOIN exam_attempts fa ON fa.exam_id=fm.exam_id AND fa.student_id=a.student_id WHERE fm.source_exam_id=a.exam_id AND fm.type='REMEDIAL' AND fa.status IN ('COMPLETED','TERMINATED')) THEN 'SELESAI' WHEN EXISTS(SELECT 1 FROM exam_follow_up_meta fm JOIN exam_target_students fts ON fts.exam_id=fm.exam_id AND fts.student_id=a.student_id WHERE fm.source_exam_id=a.exam_id AND fm.type='REMEDIAL') THEN 'SCHEDULED' ELSE COALESCE(c.status,'PENDING') END status_retake FROM exam_attempts a JOIN students s ON s.id=a.student_id JOIN exams e ON e.id=a.exam_id LEFT JOIN exam_retake_candidates c ON c.source_exam_id=a.exam_id AND c.student_id=a.student_id WHERE a.violation_count>=3 AND s.is_active=1 AND NOT EXISTS(SELECT 1 FROM exam_follow_up_meta m WHERE m.exam_id=a.exam_id) ORDER BY a.updated_at DESC";return$this->db->query($sql)->fetchAll();}
 public function approveRetakeCandidates(int$examId,array$studentIds,int$actor):int{if(!$this->hasTable('exam_retake_candidates'))throw new \UnexpectedValueException('Migrasi kandidat ujian ulang belum dijalankan.');$eligible=$this->db->prepare('SELECT 1 FROM exam_attempts WHERE exam_id=:exam AND student_id=:student AND violation_count>=3');$save=$this->db->prepare("INSERT INTO exam_retake_candidates(source_exam_id,student_id,status,approved_by,approved_at) VALUES(:exam,:student,'APPROVED',:actor,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE status=IF(status='SCHEDULED','SCHEDULED','APPROVED'),approved_by=VALUES(approved_by),approved_at=VALUES(approved_at)");$count=0;foreach($studentIds as$id){$eligible->execute(['exam'=>$examId,'student'=>$id]);if($eligible->fetchColumn()){$save->execute(['exam'=>$examId,'student'=>$id,'actor'=>$actor]);$count++;}}if(!$count)throw new \UnexpectedValueException('Kandidat tidak memenuhi syarat ujian ulang.');return$count;}
 public function approvedRetakeCandidates(int$examId,array$studentIds):bool{if(!$this->hasTable('exam_retake_candidates'))return false;$marks=implode(',',array_fill(0,count($studentIds),'?'));$s=$this->db->prepare("SELECT COUNT(*) FROM exam_retake_candidates WHERE source_exam_id=? AND status='APPROVED' AND student_id IN ($marks)");$s->execute(array_merge([$examId],$studentIds));return(int)$s->fetchColumn()===count($studentIds);}
 public function followUpSchedules():array{$sql="SELECT e.id,e.name,e.starts_at,e.ends_at,e.status,m.type,m.room,m.notes,source.id source_exam_id,source.name source_name,source.ends_at source_ends_at,COUNT(DISTINCT ts.student_id) student_count,COUNT(DISTINCT a.student_id) started_count,COUNT(DISTINCT CASE WHEN r.id IS NOT NULL THEN a.student_id END) completed_count,CASE WHEN e.status<>'ACTIVE' THEN 'INACTIVE' WHEN UTC_TIMESTAMP(3)<e.starts_at THEN 'UPCOMING' WHEN UTC_TIMESTAMP(3)<=e.ends_at THEN 'ONGOING' ELSE 'COMPLETED' END execution_state,GROUP_CONCAT(DISTINCT CONCAT(s.name_snapshot,' (',s.nisn,')') ORDER BY s.name_snapshot SEPARATOR ', ') students FROM exam_follow_up_meta m JOIN exams e ON e.id=m.exam_id JOIN exams source ON source.id=m.source_exam_id LEFT JOIN exam_target_students ts ON ts.exam_id=e.id LEFT JOIN students s ON s.id=ts.student_id LEFT JOIN exam_attempts a ON a.exam_id=e.id AND a.student_id=ts.student_id LEFT JOIN exam_results r ON r.attempt_id=a.id GROUP BY e.id,e.name,e.starts_at,e.ends_at,e.status,m.type,m.room,m.notes,source.id,source.name,source.ends_at ORDER BY e.id DESC";return$this->db->query($sql)->fetchAll();}
 public function setFollowUpStatus(int$id,bool$active):void
 {
  $valid=$this->db->prepare('SELECT e.* FROM exam_follow_up_meta m JOIN exams e ON e.id=m.exam_id WHERE e.id=? FOR UPDATE');$valid->execute([$id]);
  $exam=$valid->fetch();if(!$exam)throw new \UnexpectedValueException('Jadwal susulan/remedial tidak ditemukan.');
  if($active){
   \Cbt\Support\ExamWindow::assertSameDay(new \DateTimeImmutable($exam['starts_at'],new \DateTimeZone('UTC')),new \DateTimeImmutable($exam['ends_at'],new \DateTimeZone('UTC')));
   \Cbt\Support\ExamWindow::assertCommonDay($this->db,$exam['starts_at'],$exam['academic_year'],$exam['semester'],$id);
  }
  $this->db->prepare('UPDATE exams SET status=:status WHERE id=:id')->execute(['status'=>$active?'ACTIVE':'INACTIVE','id'=>$id]);
 }
 public function activeAttemptByPublicId(string$publicId,bool$lock=false):?array{$sql="SELECT id,student_id,exam_id,status FROM exam_attempts WHERE public_id=:public AND status='IN_PROGRESS' LIMIT 1".($lock?' FOR UPDATE':'');$s=$this->db->prepare($sql);$s->execute(['public'=>$publicId]);return$s->fetch()?:null;}
 public function activeAttemptsForExam(int$examId,bool$lock=false):array{$sql="SELECT id,student_id,exam_id,status FROM exam_attempts WHERE exam_id=:exam AND status='IN_PROGRESS'".($lock?' FOR UPDATE':'');$s=$this->db->prepare($sql);$s->execute(['exam'=>$examId]);return$s->fetchAll();}
 public function terminateAttempts(array$ids):void{if(!$ids)return;$marks=implode(',',array_fill(0,count($ids),'?'));$this->db->prepare("UPDATE exam_attempts SET status='TERMINATED' WHERE status='IN_PROGRESS' AND id IN ($marks)")->execute(array_map('intval',$ids));}
 public function deactivateExam(int$examId):bool{$s=$this->db->prepare("UPDATE exams SET status='INACTIVE' WHERE id=:id");$s->execute(['id'=>$examId]);return$s->rowCount()>0;}
 public function period(string$yearId,string$semesterId):?array{$s=$this->db->prepare('SELECT y.portal_academic_year_id,y.name academic_year,s.portal_semester_id,s.type semester FROM portal_academic_years y JOIN portal_semesters s ON s.portal_academic_year_id=y.portal_academic_year_id WHERE y.portal_academic_year_id=:year AND s.portal_semester_id=:semester LIMIT 1');$s->execute(['year'=>$yearId,'semester'=>$semesterId]);return$s->fetch()?:null;}
 public function subject(int$id):?array{$s=$this->db->prepare("SELECT id,code,name FROM subjects WHERE id=:id AND status='ACTIVE'");$s->execute(['id'=>$id]);return$s->fetch()?:null;}
 public function saveExam(array$d,int$actor):void{$params=['subject_id'=>(int)$d['subject_id'],'year_id'=>$d['portal_academic_year_id'],'semester_id'=>$d['portal_semester_id'],'name'=>$d['nama_ujian'],'grade'=>$d['tingkat'],'duration'=>(int)$d['durasi_menit'],'session'=>(int)($d['sesi']??1),'starts'=>$d['starts_at'],'ends'=>$d['ends_at'],'year'=>$d['tahun_ajaran'],'semester'=>$d['semester'],'status'=>$d['status']];if(!empty($d['id'])){$examId=(int)$d['id'];$meta=$this->db->prepare('SELECT source.ends_at FROM exam_follow_up_meta m JOIN exams source ON source.id=m.source_exam_id WHERE m.exam_id=?');$meta->execute([$examId]);$sourceEnds=$meta->fetchColumn();if($sourceEnds){$start=new \DateTimeImmutable($d['starts_at'],new \DateTimeZone('UTC'));$end=new \DateTimeImmutable($d['ends_at'],new \DateTimeZone('UTC'));\Cbt\Support\ExamWindow::assertSameDay($start,$end);if($d['status']==='ACTIVE')\Cbt\Support\ExamWindow::assertCommonDay($this->db,$d['starts_at'],$d['tahun_ajaran'],$d['semester'],$examId);if($d['starts_at']<$sourceEnds)throw new \UnexpectedValueException('Jadwal ujian lanjutan harus dimulai setelah ujian asal selesai.');}$params['id']=$examId;$sql='UPDATE exams SET subject_id=:subject_id,portal_academic_year_id=:year_id,portal_semester_id=:semester_id,name=:name,grade=:grade,duration_minutes=:duration,session_number=:session,starts_at=:starts,ends_at=:ends,academic_year=:year,semester=:semester,status=:status WHERE id=:id';}else{$params+=['public'=>Id::ulid(),'actor'=>$actor];$sql='INSERT INTO exams(public_id,subject_id,portal_academic_year_id,portal_semester_id,name,grade,duration_minutes,session_number,starts_at,ends_at,academic_year,semester,status,created_by) VALUES(:public,:subject_id,:year_id,:semester_id,:name,:grade,:duration,:session,:starts,:ends,:year,:semester,:status,:actor)';}$this->db->prepare($sql)->execute($params);$examId=$examId??(int)$this->db->lastInsertId();$this->db->prepare('DELETE FROM exam_target_classes WHERE exam_id=:id')->execute(['id'=>$examId]);foreach(array_filter(array_map('trim',explode(',',(string)($d['kelas_target']??''))))as$class){$find=$this->db->prepare("SELECT portal_class_id FROM portal_classes WHERE portal_class_id=:portal AND grade=:grade AND academic_year=:year AND status='ACTIVE' LIMIT 1");$find->execute(['portal'=>$class,'grade'=>$d['tingkat'],'year'=>$d['tahun_ajaran']]);$portal=$find->fetchColumn();if(!$portal)throw new \UnexpectedValueException("Rombel target tidak sesuai tingkat/tahun ajaran Portal Data.");$this->db->prepare('INSERT INTO exam_target_classes(exam_id,portal_class_id) VALUES(:exam,:class)')->execute(['exam'=>$examId,'class'=>$portal]);}}
 public function questions(?int$examId=null):array{$where=" WHERE q.status='ACTIVE'".($examId?' AND q.exam_id=:exam':'');$sql='SELECT q.id,q.exam_id,q.question_text pertanyaan,q.option_a opsi_a,q.option_b opsi_b,q.option_c opsi_c,q.option_d opsi_d,q.option_e opsi_e,q.correct_answer jawaban_benar,q.points poin,q.status,e.name nama_ujian,e.grade tingkat,e.academic_year tahun_ajaran,e.semester,e.subject_id,COALESCE(s.name,"Mapel Umum") nama_mapel,COALESCE(s.code,"UMUM") kode_mapel,GROUP_CONCAT(DISTINCT COALESCE(pc.name,pc.code,etc.portal_class_id)) target_kelas_names,GROUP_CONCAT(DISTINCT etc.portal_class_id) target_kelas_ids FROM questions q LEFT JOIN exams e ON e.id=q.exam_id LEFT JOIN subjects s ON s.id=e.subject_id LEFT JOIN exam_target_classes etc ON etc.exam_id=e.id LEFT JOIN portal_classes pc ON pc.portal_class_id=etc.portal_class_id'.$where.' GROUP BY q.id,e.name,e.grade,e.academic_year,e.semester,e.subject_id,s.name,s.code ORDER BY q.id DESC';$s=$this->db->prepare($sql);$s->execute($examId?['exam'=>$examId]:[]);return$s->fetchAll();}
 public function activeQuestionTexts(int$examId):array{$s=$this->db->prepare("SELECT id,question_text pertanyaan FROM questions WHERE exam_id=:exam AND status='ACTIVE' ORDER BY id");$s->execute(['exam'=>$examId]);return$s->fetchAll();}
 public function saveQuestion(array$d):void{$p=['exam'=>(int)$d['ujian_id'],'question'=>$d['pertanyaan'],'a'=>$d['opsi_a'],'b'=>$d['opsi_b'],'c'=>$d['opsi_c'],'d'=>$d['opsi_d'],'e'=>$d['opsi_e']?:null,'answer'=>$d['jawaban_benar'],'points'=>(float)$d['poin']];if(!empty($d['id'])){$p['id']=(int)$d['id'];$sql="UPDATE questions SET exam_id=:exam,question_text=:question,option_a=:a,option_b=:b,option_c=:c,option_d=:d,option_e=:e,correct_answer=:answer,points=:points WHERE id=:id AND status='ACTIVE'";}else{$p['public']=Id::ulid();$sql="INSERT INTO questions(public_id,exam_id,question_text,option_a,option_b,option_c,option_d,option_e,correct_answer,points,status) VALUES(:public,:exam,:question,:a,:b,:c,:d,:e,:answer,:points,'ACTIVE')";}$this->db->prepare($sql)->execute($p);}
 public function disableQuestion(int$id):bool{$s=$this->db->prepare("UPDATE questions SET status='DISABLED' WHERE id=:id AND status='ACTIVE'");$s->execute(['id'=>$id]);return$s->rowCount()>0;}
 public function examIdByName(string$name):?int{$s=$this->db->prepare('SELECT id FROM exams WHERE LOWER(name)=LOWER(:name) LIMIT 1');$s->execute(['name'=>trim($name)]);$id=$s->fetchColumn();return$id?(int)$id:null;}
 public function users():array{$rows=$this->db->query('SELECT id,username,name,role,status FROM users ORDER BY id DESC')->fetchAll();return array_map(fn($u)=>['id'=>(int)$u['id'],'username'=>$u['username'],'nama_lengkap'=>$u['name'],'password'=>'••••••••','role'=>strtolower($u['role']),'status_aktif'=>$u['status']==='ACTIVE'],$rows);}
 public function saveUser(array$d):void{$role=strtoupper($d['role']);$teacherId=null;if($role==='TEACHER'){$find=$this->db->prepare("SELECT id FROM teachers WHERE nip=:nip AND status='ACTIVE' LIMIT 1");$find->execute(['nip'=>$d['username']]);$teacherId=$find->fetchColumn()?:null;if(!$teacherId)throw new \UnexpectedValueException('Username akun guru wajib berupa NIP aktif dari Portal Data.');}$p=['username'=>$d['username'],'name'=>$d['nama_lengkap'],'role'=>$role,'status'=>$d['status_aktif']?'ACTIVE':'DISABLED','teacher'=>$teacherId];if(!empty($d['password']))$p['hash']=password_hash($d['password'],defined('PASSWORD_ARGON2ID')?PASSWORD_ARGON2ID:PASSWORD_DEFAULT);if(!empty($d['id'])){$p['id']=(int)$d['id'];$sql='UPDATE users SET username=:username,name=:name,role=:role,status=:status,teacher_id=:teacher'.(isset($p['hash'])?',password_hash=:hash':'').' WHERE id=:id';}else{$sql="INSERT INTO users(username,password_hash,name,role,status,teacher_id) VALUES(:username,:hash,:name,:role,:status,:teacher)";}$this->db->prepare($sql)->execute($p);}
 public function assignments():array{$relations=$this->db->query('SELECT a.id,t.id guru_id,a.exam_id,a.duty_role,t.name_snapshot nama_guru,e.name nama_ujian,s.name nama_mapel,s.code kode_mapel,e.session_number,e.grade tingkat FROM teacher_exam_assignments a JOIN teachers t ON t.id=a.teacher_id JOIN exams e ON e.id=a.exam_id LEFT JOIN subjects s ON s.id=e.subject_id ORDER BY a.id DESC')->fetchAll();$teachers=$this->db->query("SELECT id,nip username,name_snapshot nama_lengkap FROM teachers WHERE status='ACTIVE' ORDER BY name_snapshot")->fetchAll();$exams=$this->exams();foreach($relations as&$r)$r['nama_ujian']=($r['nama_mapel']?($r['nama_mapel'].' — '):'').$r['nama_ujian'].' (Sesi '.$r['session_number'].')';return['data'=>$relations,'guruList'=>$teachers,'ujianList'=>$exams];}
 public function saveAssignment(?int$id,int$teacherId,int$examId,string$dutyRole,int$actor):void{$s=$this->db->prepare("SELECT id FROM teachers WHERE id=:id AND status='ACTIVE'");$s->execute(['id'=>$teacherId]);$teacher=$s->fetchColumn();if(!$teacher)throw new \UnexpectedValueException('Guru aktif belum tersedia dari Portal Data. Jalankan sinkronisasi guru.');if($id){$this->db->prepare('UPDATE teacher_exam_assignments SET teacher_id=:teacher,exam_id=:exam,duty_role=:duty WHERE id=:id')->execute(['teacher'=>$teacher,'exam'=>$examId,'duty'=>$dutyRole,'id'=>$id]);}else{$this->db->prepare('INSERT INTO teacher_exam_assignments(teacher_id,exam_id,duty_role,created_by) VALUES(:teacher,:exam,:duty,:actor)')->execute(['teacher'=>$teacher,'exam'=>$examId,'duty'=>$dutyRole,'actor'=>$actor]);}}
 public function deleteAssignment(int$id):void{$this->db->prepare('DELETE FROM teacher_exam_assignments WHERE id=:id')->execute(['id'=>$id]);}
 public function results(?array$examIds=null):array{$where='';$params=[];if($examIds!==null){if(!$examIds)return[];$marks=implode(',',array_fill(0,count($examIds),'?'));$where=" WHERE a.exam_id IN ($marks)";$params=$examIds;}$sql='SELECT r.id,a.exam_id,a.nisn_snapshot nomor_ujian,a.name_snapshot nama_siswa,a.class_snapshot kelas,a.grade_snapshot tingkat,e.name nama_ujian,COALESCE(sub.name,\'Mata Pelajaran Umum\') nama_mapel,e.session_number,e.starts_at tanggal_ujian,e.academic_year tahun_ajaran,e.semester,r.score nilai,r.correct_count jumlah_benar,r.wrong_count jumlah_salah,r.blank_count jumlah_kosong,a.status,a.completed_at waktu_selesai FROM exam_results r JOIN exam_attempts a ON a.id=r.attempt_id JOIN exams e ON e.id=a.exam_id LEFT JOIN subjects sub ON sub.id=e.subject_id'.$where.' ORDER BY r.id DESC';$s=$this->db->prepare($sql);$s->execute($params);$rows=$s->fetchAll();foreach($rows as&$r){$r['nama_ujian'].=' (Sesi '.$r['session_number'].')';$r['semester']=$r['semester']==='ODD'?'Ganjil':'Genap';$r['status']=strtolower($r['status']);}return$rows;}
 public function violations(?array$examIds=null):array{$where='';$params=[];if($examIds!==null){if(!$examIds)return[];$where=' WHERE a.exam_id IN ('.implode(',',array_fill(0,count($examIds),'?')).')';$params=$examIds;}$sql='SELECT v.id,a.exam_id,a.student_id,a.status attempt_status,a.nisn_snapshot nomor_ujian,a.name_snapshot nama_siswa,a.class_snapshot kelas,a.grade_snapshot tingkat,e.name nama_ujian,e.session_number,a.violation_count jumlah_pelanggaran,v.type keterangan,v.occurred_at waktu FROM violations v JOIN exam_attempts a ON a.id=v.attempt_id JOIN exams e ON e.id=a.exam_id'.$where.' ORDER BY v.id DESC';$s=$this->db->prepare($sql);$s->execute($params);$rows=$s->fetchAll();foreach($rows as&$r)$r['nama_ujian'].=' (Sesi '.$r['session_number'].')';return$rows;}
 public function liveSessions(array$examIds):array{if(!$examIds)return[];$marks=implode(',',array_fill(0,count($examIds),'?'));$sql="SELECT a.public_id,a.exam_id,a.nisn_snapshot nomor_ujian,a.name_snapshot nama_siswa,a.class_snapshot kelas,a.grade_snapshot tingkat,e.name nama_ujian,e.session_number,COALESCE(sub.name,'Mata Pelajaran Umum') nama_mapel,a.started_at,a.expires_at,a.updated_at,connection.last_seen_at,IF(connection.last_seen_at>=UTC_TIMESTAMP(3)-INTERVAL 90 SECOND,'ONLINE','UNKNOWN') connection_state,a.violation_count,a.status,COUNT(DISTINCT q.question_id) total_soal,COUNT(DISTINCT CASE WHEN sa.answer IS NOT NULL THEN sa.question_id END) terjawab,COUNT(DISTINCT CASE WHEN sa.is_flagged=1 THEN sa.question_id END) ragu,COALESCE(SUM(CASE WHEN sa.answer=q.correct_answer THEN q.points ELSE 0 END),0) earned_points,COALESCE(SUM(q.points),0) maximum_points,GREATEST(TIMESTAMPDIFF(SECOND,UTC_TIMESTAMP(3),a.expires_at),0) sisa_detik FROM exam_attempts a JOIN exams e ON e.id=a.exam_id LEFT JOIN subjects sub ON sub.id=e.subject_id LEFT JOIN attempt_questions q ON q.attempt_id=a.id LEFT JOIN attempt_connections connection ON connection.attempt_id=a.id LEFT JOIN student_answers sa ON sa.attempt_id=a.id AND sa.question_id=q.question_id LEFT JOIN exam_results result ON result.attempt_id=a.id WHERE a.exam_id IN ($marks) AND ((a.status='IN_PROGRESS' AND a.expires_at>UTC_TIMESTAMP(3)) OR a.status='TERMINATED') AND result.id IS NULL GROUP BY a.id,e.id ORDER BY e.session_number,a.updated_at DESC";$s=$this->db->prepare($sql);$s->execute($examIds);return array_map(function(array$r):array{$total=(int)$r['total_soal'];$answered=(int)$r['terjawab'];$maximum=(float)$r['maximum_points'];return['publicId'=>$r['public_id'],'examId'=>(int)$r['exam_id'],'nisn'=>$r['nomor_ujian'],'studentName'=>$r['nama_siswa'],'className'=>$r['kelas'],'gradeName'=>$r['tingkat'],'subjectName'=>$r['nama_mapel'],'examTitle'=>$r['nama_ujian'],'sessionNumber'=>(int)$r['session_number'],'examName'=>$r['nama_ujian'].' (Sesi '.(int)$r['session_number'].')','status'=>$r['status'],'startedAt'=>$r['started_at'].'Z','expiresAt'=>$r['expires_at'].'Z','lastActivityAt'=>$r['updated_at'].'Z','lastSeenAt'=>$r['last_seen_at']?$r['last_seen_at'].'Z':null,'connectionState'=>$r['connection_state'],'totalQuestions'=>$total,'answeredQuestions'=>$answered,'flaggedQuestions'=>(int)$r['ragu'],'progressPercent'=>$total>0?(int)round($answered/$total*100):0,'liveScore'=>$maximum>0?round((float)$r['earned_points']/$maximum*100,2):0.0,'violationCount'=>(int)$r['violation_count'],'remainingSeconds'=>(int)$r['sisa_detik']];},$s->fetchAll());}
 public function copyTeacherAssignments(int$sourceExamId,int$targetExamId,int$actor):void{$s=$this->db->prepare('INSERT IGNORE INTO teacher_exam_assignments(teacher_id,exam_id,duty_role,created_by) SELECT teacher_id,:target,duty_role,:actor FROM teacher_exam_assignments WHERE exam_id=:source');$s->execute(['target'=>$targetExamId,'actor'=>$actor,'source'=>$sourceExamId]);}
 public function allExamIds():array{return array_map('intval',$this->db->query('SELECT id FROM exams')->fetchAll(PDO::FETCH_COLUMN));}
 public function teacherIdForUser(int$userId):int{if($userId<=0)return 0;$s=$this->db->prepare("SELECT teacher_id FROM users WHERE id=:id AND role='TEACHER' AND status='ACTIVE' LIMIT 1");$s->execute(['id'=>$userId]);return(int)($s->fetchColumn()?:0);}
 public function teacherExamIds(int$teacherId):array{if($teacherId<=0)return[];$s=$this->db->prepare('SELECT DISTINCT exam_id FROM teacher_exam_assignments WHERE teacher_id=:teacher ORDER BY exam_id DESC');$s->execute(['teacher'=>$teacherId]);return array_map('intval',$s->fetchAll(PDO::FETCH_COLUMN));}
 private function ensureSettingsTable():void{$this->db->exec("CREATE TABLE IF NOT EXISTS cbt_settings (key_name VARCHAR(100) NOT NULL PRIMARY KEY,value VARCHAR(500) NOT NULL DEFAULT '',description VARCHAR(255) NULL,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$this->db->exec("INSERT INTO cbt_settings(key_name,value,description) VALUES ('remedial_score_cap_X','75','Nilai maksimum ujian ulang siswa tingkat X (0-100)'),('remedial_score_cap_XI','75','Nilai maksimum ujian ulang siswa tingkat XI (0-100)'),('remedial_score_cap_XII','75','Nilai maksimum ujian ulang siswa tingkat XII (0-100)') ON DUPLICATE KEY UPDATE key_name=VALUES(key_name)");}
 public function getSettings():array{$this->ensureSettingsTable();$rows=$this->db->query('SELECT key_name,value,description FROM cbt_settings ORDER BY key_name')->fetchAll();return array_column($rows,null,'key_name');}
 public function saveSettings(array$data):void{$this->ensureSettingsTable();$allowed=['remedial_score_cap_X','remedial_score_cap_XI','remedial_score_cap_XII'];$s=$this->db->prepare('INSERT INTO cbt_settings(key_name,value) VALUES(:k,:v) ON DUPLICATE KEY UPDATE value=VALUES(value)');foreach($data as$key=>$val){if(!in_array((string)$key,$allowed,true))continue;$s->execute(['k'=>$key,'v'=>(string)$val]);}}
 public function getSettingValue(string$key,string$default=''):string{try{$s=$this->db->prepare('SELECT value FROM cbt_settings WHERE key_name=:k LIMIT 1');$s->execute(['k'=>$key]);$v=$s->fetchColumn();return$v!==false?(string)$v:$default;}catch(\PDOException){return$default;}}
}
