<?php
declare(strict_types=1);
namespace Cbt\Repositories;
use Cbt\Support\Id;
use PDO;
final class AdminRepository
{
 public function __construct(private PDO$db){}
 public function dashboard():array{return['totalSiswa'=>(int)$this->db->query('SELECT COUNT(*) FROM students WHERE is_active=1')->fetchColumn(),'totalUjianAktif'=>(int)$this->db->query("SELECT COUNT(*) FROM exams WHERE status='ACTIVE'")->fetchColumn(),'totalSubmit'=>(int)$this->db->query('SELECT COUNT(*) FROM exam_results')->fetchColumn(),'totalPelanggaran'=>(int)$this->db->query('SELECT COUNT(*) FROM violations')->fetchColumn()];}
 public function references():array{return['teachers'=>$this->db->query("SELECT id,portal_teacher_id,nip,nuptk,name_snapshot name FROM teachers WHERE status='ACTIVE' ORDER BY name_snapshot")->fetchAll(),'subjects'=>$this->db->query("SELECT id,public_id,code,name FROM subjects WHERE status='ACTIVE' ORDER BY name")->fetchAll(),'classes'=>$this->db->query("SELECT portal_class_id,code,name,grade,academic_year FROM portal_classes WHERE status='ACTIVE' ORDER BY grade,code")->fetchAll(),'academic_years'=>$this->db->query('SELECT portal_academic_year_id,name,is_active FROM portal_academic_years ORDER BY name DESC')->fetchAll(),'semesters'=>$this->db->query('SELECT portal_semester_id,portal_academic_year_id,type,academic_year,is_active FROM portal_semesters ORDER BY academic_year DESC,type')->fetchAll()];}
 public function exams():array{$rows=$this->db->query('SELECT e.*,s.code kode_mapel,s.name nama_mapel,GROUP_CONCAT(x.portal_class_id ORDER BY x.portal_class_id) classes FROM exams e LEFT JOIN subjects s ON s.id=e.subject_id LEFT JOIN exam_target_classes x ON x.exam_id=e.id GROUP BY e.id,s.code,s.name ORDER BY e.id DESC')->fetchAll();return array_map(fn($e)=>['id'=>(int)$e['id'],'subject_id'=>$e['subject_id']?(int)$e['subject_id']:null,'kode_mapel'=>$e['kode_mapel'],'nama_mapel'=>$e['nama_mapel'],'portal_academic_year_id'=>$e['portal_academic_year_id'],'portal_semester_id'=>$e['portal_semester_id'],'nama_ujian'=>$e['name'],'tingkat'=>$e['grade'],'kelas_target'=>$e['classes']??'','durasi_menit'=>(int)$e['duration_minutes'],'sesi'=>(int)$e['session_number'],'tanggal_ujian'=>substr($e['starts_at'],0,10),'tanggal_mulai'=>substr($e['starts_at'],0,10),'jam_mulai'=>substr($e['starts_at'],11,5),'tanggal_selesai'=>substr($e['ends_at'],0,10),'jam_selesai'=>substr($e['ends_at'],11,5),'tahun_ajaran'=>$e['academic_year'],'semester'=>$e['semester']==='ODD'?'Ganjil':'Genap','status_aktif'=>$e['status']==='ACTIVE'],$rows);}
 public function period(string$yearId,string$semesterId):?array{$s=$this->db->prepare('SELECT y.portal_academic_year_id,y.name academic_year,s.portal_semester_id,s.type semester FROM portal_academic_years y JOIN portal_semesters s ON s.portal_academic_year_id=y.portal_academic_year_id WHERE y.portal_academic_year_id=:year AND s.portal_semester_id=:semester LIMIT 1');$s->execute(['year'=>$yearId,'semester'=>$semesterId]);return$s->fetch()?:null;}
 public function subject(int$id):?array{$s=$this->db->prepare("SELECT id,code,name FROM subjects WHERE id=:id AND status='ACTIVE'");$s->execute(['id'=>$id]);return$s->fetch()?:null;}
 public function saveExam(array$d,int$actor):void{$params=['subject_id'=>(int)$d['subject_id'],'year_id'=>$d['portal_academic_year_id'],'semester_id'=>$d['portal_semester_id'],'name'=>$d['nama_ujian'],'grade'=>$d['tingkat'],'duration'=>(int)$d['durasi_menit'],'session'=>(int)($d['sesi']??1),'starts'=>$d['starts_at'],'ends'=>$d['ends_at'],'year'=>$d['tahun_ajaran'],'semester'=>$d['semester'],'status'=>$d['status']];if(!empty($d['id'])){$examId=(int)$d['id'];$params['id']=$examId;$sql='UPDATE exams SET subject_id=:subject_id,portal_academic_year_id=:year_id,portal_semester_id=:semester_id,name=:name,grade=:grade,duration_minutes=:duration,session_number=:session,starts_at=:starts,ends_at=:ends,academic_year=:year,semester=:semester,status=:status WHERE id=:id';}else{$params+=['public'=>Id::ulid(),'actor'=>$actor];$sql='INSERT INTO exams(public_id,subject_id,portal_academic_year_id,portal_semester_id,name,grade,duration_minutes,session_number,starts_at,ends_at,academic_year,semester,status,created_by) VALUES(:public,:subject_id,:year_id,:semester_id,:name,:grade,:duration,:session,:starts,:ends,:year,:semester,:status,:actor)';}$this->db->prepare($sql)->execute($params);$examId=$examId??(int)$this->db->lastInsertId();$this->db->prepare('DELETE FROM exam_target_classes WHERE exam_id=:id')->execute(['id'=>$examId]);foreach(array_filter(array_map('trim',explode(',',(string)($d['kelas_target']??''))))as$class){$find=$this->db->prepare("SELECT portal_class_id FROM portal_classes WHERE portal_class_id=:portal AND grade=:grade AND academic_year=:year AND status='ACTIVE' LIMIT 1");$find->execute(['portal'=>$class,'grade'=>$d['tingkat'],'year'=>$d['tahun_ajaran']]);$portal=$find->fetchColumn();if(!$portal)throw new \UnexpectedValueException("Rombel target tidak sesuai tingkat/tahun ajaran Portal Data.");$this->db->prepare('INSERT INTO exam_target_classes(exam_id,portal_class_id) VALUES(:exam,:class)')->execute(['exam'=>$examId,'class'=>$portal]);}}
 public function questions(?int$examId=null):array{$sql='SELECT id,exam_id,question_text pertanyaan,option_a opsi_a,option_b opsi_b,option_c opsi_c,option_d opsi_d,option_e opsi_e,correct_answer jawaban_benar,points poin,status FROM questions'.($examId?' WHERE exam_id=:exam':'').' ORDER BY id DESC';$s=$this->db->prepare($sql);$s->execute($examId?['exam'=>$examId]:[]);return$s->fetchAll();}
 public function saveQuestion(array$d):void{$p=['exam'=>(int)$d['ujian_id'],'question'=>$d['pertanyaan'],'a'=>$d['opsi_a'],'b'=>$d['opsi_b'],'c'=>$d['opsi_c'],'d'=>$d['opsi_d'],'e'=>$d['opsi_e']?:null,'answer'=>$d['jawaban_benar'],'points'=>(float)$d['poin']];if(!empty($d['id'])){$p['id']=(int)$d['id'];$sql='UPDATE questions SET exam_id=:exam,question_text=:question,option_a=:a,option_b=:b,option_c=:c,option_d=:d,option_e=:e,correct_answer=:answer,points=:points WHERE id=:id';}else{$p['public']=Id::ulid();$sql="INSERT INTO questions(public_id,exam_id,question_text,option_a,option_b,option_c,option_d,option_e,correct_answer,points,status) VALUES(:public,:exam,:question,:a,:b,:c,:d,:e,:answer,:points,'ACTIVE')";}$this->db->prepare($sql)->execute($p);}
 public function examIdByName(string$name):?int{$s=$this->db->prepare('SELECT id FROM exams WHERE LOWER(name)=LOWER(:name) LIMIT 1');$s->execute(['name'=>trim($name)]);$id=$s->fetchColumn();return$id?(int)$id:null;}
 public function users():array{$rows=$this->db->query('SELECT id,username,name,role,status FROM users ORDER BY id DESC')->fetchAll();return array_map(fn($u)=>['id'=>(int)$u['id'],'username'=>$u['username'],'nama_lengkap'=>$u['name'],'password'=>'••••••••','role'=>strtolower($u['role']),'status_aktif'=>$u['status']==='ACTIVE'],$rows);}
 public function saveUser(array$d):void{$role=strtoupper($d['role']);$teacherId=null;if($role==='TEACHER'){$find=$this->db->prepare("SELECT id FROM teachers WHERE nip=:nip AND status='ACTIVE' LIMIT 1");$find->execute(['nip'=>$d['username']]);$teacherId=$find->fetchColumn()?:null;if(!$teacherId)throw new \UnexpectedValueException('Username akun guru wajib berupa NIP aktif dari Portal Data.');}$p=['username'=>$d['username'],'name'=>$d['nama_lengkap'],'role'=>$role,'status'=>$d['status_aktif']?'ACTIVE':'DISABLED','teacher'=>$teacherId];if(!empty($d['password']))$p['hash']=password_hash($d['password'],defined('PASSWORD_ARGON2ID')?PASSWORD_ARGON2ID:PASSWORD_DEFAULT);if(!empty($d['id'])){$p['id']=(int)$d['id'];$sql='UPDATE users SET username=:username,name=:name,role=:role,status=:status,teacher_id=:teacher'.(isset($p['hash'])?',password_hash=:hash':'').' WHERE id=:id';}else{$sql="INSERT INTO users(username,password_hash,name,role,status,teacher_id) VALUES(:username,:hash,:name,:role,:status,:teacher)";}$this->db->prepare($sql)->execute($p);}
 public function assignments():array{$relations=$this->db->query('SELECT a.id,t.id guru_id,a.exam_id,t.name_snapshot nama_guru,e.name nama_ujian,s.name nama_mapel,s.code kode_mapel,e.session_number,e.grade tingkat FROM teacher_exam_assignments a JOIN teachers t ON t.id=a.teacher_id JOIN exams e ON e.id=a.exam_id LEFT JOIN subjects s ON s.id=e.subject_id ORDER BY a.id DESC')->fetchAll();$teachers=$this->db->query("SELECT id,nip username,name_snapshot nama_lengkap FROM teachers WHERE status='ACTIVE' ORDER BY name_snapshot")->fetchAll();$exams=$this->exams();foreach($relations as&$r)$r['nama_ujian']=($r['nama_mapel']?($r['nama_mapel'].' — '):'').$r['nama_ujian'].' (Sesi '.$r['session_number'].')';return['data'=>$relations,'guruList'=>$teachers,'ujianList'=>$exams];}
 public function saveAssignment(?int$id,int$teacherId,int$examId,int$actor):void{$s=$this->db->prepare("SELECT id FROM teachers WHERE id=:id AND status='ACTIVE'");$s->execute(['id'=>$teacherId]);$teacher=$s->fetchColumn();if(!$teacher)throw new \UnexpectedValueException('Guru aktif belum tersedia dari Portal Data. Jalankan sinkronisasi guru.');if($id){$this->db->prepare('UPDATE teacher_exam_assignments SET teacher_id=:teacher,exam_id=:exam WHERE id=:id')->execute(['teacher'=>$teacher,'exam'=>$examId,'id'=>$id]);}else{$this->db->prepare('INSERT INTO teacher_exam_assignments(teacher_id,exam_id,created_by) VALUES(:teacher,:exam,:actor)')->execute(['teacher'=>$teacher,'exam'=>$examId,'actor'=>$actor]);}}
 public function deleteAssignment(int$id):void{$this->db->prepare('DELETE FROM teacher_exam_assignments WHERE id=:id')->execute(['id'=>$id]);}
 public function results(?array$examIds=null):array{$where='';$params=[];if($examIds!==null){if(!$examIds)return[];$marks=implode(',',array_fill(0,count($examIds),'?'));$where=" WHERE a.exam_id IN ($marks)";$params=$examIds;}$sql='SELECT r.id,a.exam_id,a.nisn_snapshot nomor_ujian,a.name_snapshot nama_siswa,a.class_snapshot kelas,a.grade_snapshot tingkat,e.name nama_ujian,e.session_number,e.starts_at tanggal_ujian,e.academic_year tahun_ajaran,e.semester,r.score nilai,r.correct_count jumlah_benar,r.wrong_count jumlah_salah,r.blank_count jumlah_kosong,a.status,a.completed_at waktu_selesai FROM exam_results r JOIN exam_attempts a ON a.id=r.attempt_id JOIN exams e ON e.id=a.exam_id'.$where.' ORDER BY r.id DESC';$s=$this->db->prepare($sql);$s->execute($params);$rows=$s->fetchAll();foreach($rows as&$r){$r['nama_ujian'].=' (Sesi '.$r['session_number'].')';$r['semester']=$r['semester']==='ODD'?'Ganjil':'Genap';$r['status']=strtolower($r['status']);}return$rows;}
 public function violations(?array$examIds=null):array{$where='';$params=[];if($examIds!==null){if(!$examIds)return[];$where=' WHERE a.exam_id IN ('.implode(',',array_fill(0,count($examIds),'?')).')';$params=$examIds;}$sql='SELECT v.id,a.exam_id,a.nisn_snapshot nomor_ujian,a.name_snapshot nama_siswa,a.class_snapshot kelas,e.name nama_ujian,e.session_number,a.violation_count jumlah_pelanggaran,v.type keterangan,v.occurred_at waktu FROM violations v JOIN exam_attempts a ON a.id=v.attempt_id JOIN exams e ON e.id=a.exam_id'.$where.' ORDER BY v.id DESC';$s=$this->db->prepare($sql);$s->execute($params);$rows=$s->fetchAll();foreach($rows as&$r)$r['nama_ujian'].=' (Sesi '.$r['session_number'].')';return$rows;}
 public function teacherExamIds(int$userId,bool$admin):array{if($admin)return array_map('intval',$this->db->query('SELECT id FROM exams')->fetchAll(PDO::FETCH_COLUMN));$s=$this->db->prepare('SELECT a.exam_id FROM teacher_exam_assignments a JOIN users u ON u.teacher_id=a.teacher_id WHERE u.id=:id');$s->execute(['id'=>$userId]);return array_map('intval',$s->fetchAll(PDO::FETCH_COLUMN));}
}
