<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Portal Data</title>@vite('resources/js/portal-react/main.tsx')</head>
<body>
<div id="root"></div>
{{-- Legacy shell retained below temporarily during cutover; React entrypoint is authoritative. --}}
<div id="legacy-portal" hidden>
<div id="portal" class="shell" hidden>
<aside><div class="brand"><span class="logo">PD</span><span><b>Portal Data</b><small>Sumber data sekolah</small></span></div><nav><button class="nav active" data-page="dashboard">Ringkasan</button><button class="nav" data-page="students">Siswa</button><button class="nav" data-page="teachers">Guru</button><button class="nav" data-page="classes">Kelas</button><button class="nav" data-page="periods">Periode</button><button class="nav" data-page="imports">Import data</button><button class="nav" data-page="audit">Audit log</button><button class="nav" data-page="guide">Panduan</button><button class="nav" data-page="sso">Aplikasi SSO</button><button id="admin-nav" class="nav" data-page="admins">Pengguna admin</button><button class="nav" data-page="profile">Profil & keamanan</button></nav><div class="account"><b id="account-name"></b><small id="account-role"></small><button id="logout" class="outline">Keluar</button></div></aside>
<main><header><div><p class="overline">Portal Data</p><h1 id="title">Ringkasan sekolah</h1></div><span id="period" class="period">Memuat periode…</span></header><div id="notice" class="notice" hidden></div>
<section id="dashboard-page" class="page"><div id="metrics" class="metrics"></div><div class="grid"><article class="panel"><p class="overline">Kualitas data</p><h2>Perlu perhatian</h2><div id="quality"></div></article><article class="panel"><p class="overline">Jejak sistem</p><h2>Aktivitas terbaru</h2><div id="activities"></div></article></div></section>
<section id="master-page" class="page" hidden><div class="panel"><div class="panel-head"><div><p id="master-overline" class="overline">Master data</p><h2 id="master-heading"></h2></div><div class="actions"><button id="master-export" class="outline">Export</button><button id="master-new">Tambah</button></div></div><div id="master-filters" class="filters"></div><div id="master-form" class="form-grid" hidden></div><div id="master-table" class="table-wrap"></div></div></section>
<section id="audit-page" class="page" hidden><div class="panel"><div class="panel-head"><div><p class="overline">Jejak perubahan</p><h2>Audit log</h2></div></div><form id="audit-filters" class="filters"><select name="actorType"><option value="">Semua aktor</option><option>ADMIN</option><option>TEACHER</option><option>SYSTEM</option></select><input name="actorPublicId" placeholder="Public ID aktor"><input name="action" placeholder="Aksi"><input name="entityType" placeholder="Tipe entitas"><input name="entityPublicId" placeholder="Public ID entitas"><input name="dateFrom" type="date"><input name="dateTo" type="date"><select name="sortDirection"><option value="desc">Terbaru</option><option value="asc">Terlama</option></select><button class="primary">Terapkan</button><button type="button" id="audit-reset">Reset</button></form><div id="audit-table" class="table-wrap"></div><div id="audit-detail" class="detail-box" hidden></div></div></section>
<section id="guide-page" class="page" hidden><div class="panel guide-content"><p class="overline">Portal Data · Dokumentasi</p><h2>Panduan operasional dan integrasi</h2><p class="muted">Portal Data adalah sumber data sekolah sekaligus Identity Provider OpenID Connect untuk aplikasi internal.</p><div class="guide-grid"><article><h3>Akun dan akses</h3><p>Administrator mengelola master data sesuai role. Guru login memakai username dan password akun guru. Data siswa tidak memiliki akses login.</p></article><article><h3>Provisioning guru</h3><p>Lengkapi identifier guru, buat akun, kirim link aktivasi, lalu berikan akses ke aplikasi SSO.</p></article><article><h3>Keamanan</h3><p>Gunakan HTTPS di produksi, cookie secure, CSRF untuk request mutasi, dan jangan commit password, token, atau private signing key.</p></article><article><h3>Import siswa</h3><p>Unduh template XLSX, validasi workbook, periksa warning/error, lalu commit setelah data sesuai.</p></article></div><h3>Integrasi OIDC</h3><pre class="code-block"><code>Issuer: {{ config('oidc.issuer') }} · Discovery: /oidc/.well-known/openid-configuration · Authorization: /oidc/authorize · Token: /oidc/token · JWKS: /oidc/jwks · Flow: Authorization Code + PKCE S256 · Scope: openid profile email portal_role</code></pre><h3>Checklist aplikasi</h3><ul><li>Simpan state, nonce, dan PKCE verifier di session server.</li><li>Validasi signature, issuer, audience, expiry, dan nonce ID token.</li><li>Gunakan <code>sub</code> atau <code>portal_teacher_id</code> sebagai identitas stabil.</li><li>Pastikan redirect URI terdaftar persis dan memakai HTTPS di produksi.</li></ul><h3>Respons API</h3><pre class="code-block"><code>{ "success": true, "message": "...", "data": {}, "meta": {} }</code></pre></div></section>
<section id="imports-page" class="page" hidden><div class="grid import-grid"><article class="panel"><p class="overline">Import siswa</p><h2>Validasi workbook</h2><p class="muted">Gunakan file .xlsx sesuai template. File diperiksa sebelum data disimpan.</p><form id="import-form" class="stack"><label class="drop">Pilih file Excel<input id="import-file" name="file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required><span id="file-name">Belum ada file</span></label><button>Validasi file</button></form><a href="/api/v1/import-templates/students">Unduh template import</a><div id="import-result" class="result" hidden></div></article><article class="panel wide"><div class="panel-head"><div><p class="overline">Riwayat</p><h2>Batch terbaru</h2></div><button id="refresh-imports" class="outline compact">Muat ulang</button></div><div id="import-history" class="table-wrap"></div></article></div></section>
<section id="sso-page" class="page" hidden><div class="grid"><article class="panel"><p class="overline">OpenID Connect</p><h2>Daftarkan aplikasi</h2><form id="sso-form" class="stack"><label>Nama aplikasi<input name="name" required></label><label>Slug<input name="slug" pattern="[a-z0-9-]+" required></label><label>Redirect URI<input name="redirectUri" type="url" required></label><label>Post logout URI<input name="logoutUri" type="url"></label><button>Tambah aplikasi</button></form></article><article class="panel"><p class="overline">Client OIDC</p><h2>Aplikasi terdaftar</h2><div id="sso-list"></div></article></div><article class="panel below"><p class="overline">Akses guru</p><h2>Berikan akses ke aplikasi</h2><form id="sso-access-form" class="inline-form"><label>Aplikasi<select name="application" required></select></label><label>Guru<select name="teacherPublicId" required></select></label><label>Role<input name="role" value="TEACHER" required></label><button>Berikan akses</button></form></article></section>
<section id="admins-page" class="page" hidden><div class="grid"><article class="panel"><p class="overline">Super admin</p><h2>Tambah pengguna admin</h2><form id="admin-form" class="stack"><label>Nama<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Password awal<input name="password" type="password" minlength="12" required></label><label>Role<select name="role"><option>DATA_ADMIN</option><option>DATA_OPERATOR</option><option>AUDITOR</option><option>SUPER_ADMIN</option></select></label><button>Tambah pengguna</button></form></article><article class="panel"><p class="overline">Akses internal</p><h2>Pengguna admin</h2><div id="admin-list"></div></article></div></section>
<section id="profile-page" class="page" hidden><div class="grid"><article class="panel"><p class="overline">Identitas</p><h2>Profil admin</h2><form id="profile-form" class="stack"><label>Nama<input name="name" required></label><label>Email<input name="email" type="email" required></label><button>Simpan profil</button></form></article><article class="panel"><p class="overline">Password</p><h2>Ganti password</h2><form id="admin-password-form" class="stack"><label>Password saat ini<input name="currentPassword" type="password" required></label><label>Password baru<input name="newPassword" type="password" minlength="12" required></label><label>Konfirmasi<input name="newPassword_confirmation" type="password" minlength="12" required></label><button>Ganti password</button></form></article></div><article class="panel below"><div class="panel-head"><div><p class="overline">Perangkat</p><h2>Session aktif</h2></div><button id="admin-logout-all" class="outline compact">Cabut semua</button></div><div id="admin-sessions"></div></article></section>
</main></div></div></body></html>
