<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Portal Data</title>@vite(['resources/css/portal.css','resources/css/admin.css','resources/js/portal.js'])</head>
<body>
<div id="login" class="auth" hidden><section class="login-card"><span class="logo">PD</span><p class="overline">Sistem data sekolah</p><h1>Masuk ke Portal Data</h1><p class="muted">Kelola sumber data sekolah dari satu tempat yang aman.</p><form id="login-form" class="stack"><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><p id="login-error" class="error" hidden></p><button>Masuk</button></form></section></div>
<div id="portal" class="shell" hidden>
<aside><div class="brand"><span class="logo">PD</span><span><b>Portal Data</b><small>Sumber data sekolah</small></span></div><nav><button class="nav active" data-page="dashboard">Ringkasan</button><button class="nav" data-page="imports">Import data</button><button class="nav" data-page="sso">Aplikasi SSO</button><button id="admin-nav" class="nav" data-page="admins">Pengguna admin</button><button class="nav" data-page="profile">Profil & keamanan</button></nav><div class="account"><b id="account-name"></b><small id="account-role"></small><button id="logout" class="outline">Keluar</button></div></aside>
<main><header><div><p class="overline">Portal Data</p><h1 id="title">Ringkasan sekolah</h1></div><span id="period" class="period">Memuat periode…</span></header><div id="notice" class="notice" hidden></div>
<section id="dashboard-page" class="page"><div id="metrics" class="metrics"></div><div class="grid"><article class="panel"><p class="overline">Kualitas data</p><h2>Perlu perhatian</h2><div id="quality"></div></article><article class="panel"><p class="overline">Jejak sistem</p><h2>Aktivitas terbaru</h2><div id="activities"></div></article></div></section>
<section id="imports-page" class="page" hidden><div class="grid import-grid"><article class="panel"><p class="overline">Import siswa</p><h2>Validasi workbook</h2><p class="muted">Gunakan file .xlsx sesuai template. File diperiksa sebelum data disimpan.</p><form id="import-form" class="stack"><label class="drop">Pilih file Excel<input id="import-file" name="file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required><span id="file-name">Belum ada file</span></label><button>Validasi file</button></form><a href="/api/v1/import-templates/students">Unduh template import</a><div id="import-result" class="result" hidden></div></article><article class="panel wide"><div class="panel-head"><div><p class="overline">Riwayat</p><h2>Batch terbaru</h2></div><button id="refresh-imports" class="outline compact">Muat ulang</button></div><div id="import-history" class="table-wrap"></div></article></div></section>
<section id="sso-page" class="page" hidden><div class="grid"><article class="panel"><p class="overline">OpenID Connect</p><h2>Daftarkan aplikasi</h2><form id="sso-form" class="stack"><label>Nama aplikasi<input name="name" required></label><label>Slug<input name="slug" pattern="[a-z0-9-]+" required></label><label>Redirect URI<input name="redirectUri" type="url" required></label><label>Post logout URI<input name="logoutUri" type="url"></label><button>Tambah aplikasi</button></form></article><article class="panel"><p class="overline">Client OIDC</p><h2>Aplikasi terdaftar</h2><div id="sso-list"></div></article></div><article class="panel below"><p class="overline">Akses guru</p><h2>Berikan akses ke aplikasi</h2><form id="sso-access-form" class="inline-form"><label>Aplikasi<select name="application" required></select></label><label>Guru<select name="teacherPublicId" required></select></label><label>Role<input name="role" value="TEACHER" required></label><button>Berikan akses</button></form></article></section>
<section id="admins-page" class="page" hidden><div class="grid"><article class="panel"><p class="overline">Super admin</p><h2>Tambah pengguna admin</h2><form id="admin-form" class="stack"><label>Nama<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Password awal<input name="password" type="password" minlength="12" required></label><label>Role<select name="role"><option>DATA_ADMIN</option><option>DATA_OPERATOR</option><option>AUDITOR</option><option>SUPER_ADMIN</option></select></label><button>Tambah pengguna</button></form></article><article class="panel"><p class="overline">Akses internal</p><h2>Pengguna admin</h2><div id="admin-list"></div></article></div></section>
<section id="profile-page" class="page" hidden><div class="grid"><article class="panel"><p class="overline">Identitas</p><h2>Profil admin</h2><form id="profile-form" class="stack"><label>Nama<input name="name" required></label><label>Email<input name="email" type="email" required></label><button>Simpan profil</button></form></article><article class="panel"><p class="overline">Password</p><h2>Ganti password</h2><form id="admin-password-form" class="stack"><label>Password saat ini<input name="currentPassword" type="password" required></label><label>Password baru<input name="newPassword" type="password" minlength="12" required></label><label>Konfirmasi<input name="newPassword_confirmation" type="password" minlength="12" required></label><button>Ganti password</button></form></article></div><article class="panel below"><div class="panel-head"><div><p class="overline">Perangkat</p><h2>Session aktif</h2></div><button id="admin-logout-all" class="outline compact">Cabut semua</button></div><div id="admin-sessions"></div></article></section>
</main></div></body></html>
