<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Portal Guru</title>@vite('resources/js/portal-react/main.tsx')</head>
<body>
<div id="root"></div>
<div id="legacy-teacher" hidden>
<div id="teacher-setup" class="auth" hidden><section class="login-card"><span class="logo">PG</span><p class="overline">Aktivasi akun</p><h1>Atur password</h1><p id="setup-person" class="muted">Memeriksa link…</p><form id="setup-form" class="stack" hidden><label>Password baru<input name="password" type="password" minlength="10" required></label><small>Minimal 10 karakter, huruf besar, huruf kecil, dan angka.</small><label>Konfirmasi password<input name="password_confirmation" type="password" minlength="10" required></label><p id="setup-error" class="error" hidden></p><button>Aktifkan akun</button></form><a href="/teacher/login">Kembali ke login</a></section></div>
<div id="teacher-portal" class="shell teacher-shell" hidden><aside><div class="brand"><span class="logo">PG</span><span><b>Portal Guru</b><small>Akun Portal Data</small></span></div><nav><button class="nav active" data-teacher-page="home">Beranda</button><button class="nav" data-teacher-page="profile">Profil</button><button class="nav" data-teacher-page="security">Keamanan</button></nav><div class="account"><b id="teacher-name"></b><small id="teacher-username"></small><button id="teacher-logout" class="outline">Keluar</button></div></aside><main><header><div><p class="overline">Layanan mandiri</p><h1 id="teacher-title">Beranda guru</h1></div></header><div id="teacher-notice" class="notice" hidden></div>
<section id="teacher-home-page" class="teacher-page"><div class="panel hero"><p class="overline">Selamat datang</p><h2 id="teacher-greeting"></h2><p class="muted">Kelola informasi kontak, foto profil, password, dan perangkat yang masuk ke akun Anda.</p></div></section>
<section id="teacher-profile-page" class="teacher-page" hidden><div class="grid teacher-profile-grid"><article class="panel"><div id="photo-preview" class="photo-preview"></div><form id="photo-form" class="stack"><label>Foto JPEG, PNG, atau WebP<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required></label><button>Unggah foto</button></form></article><article class="panel"><p class="overline">Informasi kontak</p><h2>Profil guru</h2><form id="teacher-profile-form" class="stack"><label>Email<input name="email" type="email"></label><label>Telepon<input name="phone"></label><label>Alamat<textarea name="address" rows="4"></textarea></label><button>Simpan profil</button></form><dl id="teacher-identifiers" class="profile-data"></dl></article></div></section>
<section id="teacher-security-page" class="teacher-page" hidden><div class="grid"><article class="panel"><p class="overline">Password</p><h2>Ganti password</h2><form id="teacher-password-form" class="stack"><label>Password saat ini<input name="currentPassword" type="password" required></label><label>Password baru<input name="newPassword" type="password" minlength="10" required></label><label>Konfirmasi<input name="confirmation" type="password" minlength="10" required></label><button>Ganti password</button></form></article><article class="panel"><div class="panel-head"><div><p class="overline">Perangkat</p><h2>Session aktif</h2></div><button id="teacher-logout-all" class="outline compact">Cabut semua</button></div><div id="teacher-sessions"></div></article></div></section>
</main></div></div></body></html>
