import React, { useEffect, useState } from 'react';
import { api } from './lib/api';
import { RichContentEditor } from './RichContentEditor';

type Exam = { id:number; name:string; grade:string };
type Question = { id:number; exam_id:number; question_type:'MULTIPLE_CHOICE'|'MULTIPLE_RESPONSE'|'SHORT_ANSWER'; question_text:string; option_a:string|null; option_b:string|null; option_c:string|null; option_d:string|null; option_e:string|null; correct_answer:string; points:number; status:string };
type Draft = Omit<Question,'id'|'status'>;
const empty = (exam_id:number):Draft => ({exam_id,question_type:'MULTIPLE_CHOICE',question_text:'',option_a:'',option_b:'',option_c:'',option_d:'',option_e:'',correct_answer:'',points:1});
const columns = ['exam_id','question_type','question_text','option_a','option_b','option_c','option_d','option_e','correct_answer','points'];
function csv(rows:string[][]){return '\ufeff'+rows.map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\r\n');}
function download(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function filename(value:string){return value.normalize('NFKD').replace(/[^A-Za-z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase().slice(0,80)||'ujian';}
function downloadTemplate(exam:Exam){download(`template-soal-${filename(exam.name)}-${exam.grade}.csv`,csv([columns,[String(exam.id),'MULTIPLE_CHOICE',`Contoh pertanyaan ${exam.name}`,'Pilihan A','Pilihan B','Pilihan C','Pilihan D','','A','1']]));}
function parseCsv(source:string):string[][]{const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<source.length;i++){const ch=source[i];if(quoted){if(ch==='"'&&source[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}if(quoted)throw new Error('Tanda kutip CSV belum ditutup');if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}
function previewHtml(value:string){const documentHtml=new DOMParser().parseFromString(value,'text/html');const math=new Set(['MATH','MROW','MI','MN','MO','MTEXT','MSPACE','MFRAC','MSQRT','MROOT','MSUB','MSUP','MSUBSUP','MUNDER','MOVER','MUNDEROVER','MMULTISCRIPTS','MPRESCRIPTS','NONE','MTABLE','MTR','MTD','MENCLOSE','MPADDED','MPHANTOM']);const allowed=new Set(['P','BR','B','STRONG','I','EM','U','S','SUB','SUP','UL','OL','LI','TABLE','THEAD','TBODY','TR','TH','TD','IMG','SPAN','DIV',...math]);for(const element of Array.from(documentHtml.body.querySelectorAll('*')).reverse()){if(!allowed.has(element.tagName)){element.replaceWith(documentHtml.createTextNode(element.textContent??''));continue;}for(const attribute of Array.from(element.attributes)){const keep=element.tagName==='IMG'&&attribute.name==='alt'||element.tagName==='IMG'&&attribute.name==='src'&&/^\/api\/question-images\/[0-9a-f]{64}\.(png|jpg|webp|gif)$/.test(attribute.value)||math.has(element.tagName)&&['xmlns','display','width','accent','accentunder','notation','linethickness','bevelled'].includes(attribute.name)||attribute.name==='dir';if(!keep)element.removeAttribute(attribute.name);}}return documentHtml.body.innerHTML;}
function normalizeCsv(text:string,examId:number){const [headers,...rows]=parseCsv(text.replace(/^\ufeff/,''));if(!headers)throw new Error('CSV kosong');const names=headers.map(x=>x.trim().toLowerCase());if(!names.includes('question_text')&&!names.includes('pertanyaan'))throw new Error('Kolom question_text atau pertanyaan wajib ada');return rows.filter(row=>row.some(Boolean)).map(row=>{const data:Record<string,string|number>={};names.forEach((name,index)=>data[name]=row[index]??'');data.exam_id=Number(data.exam_id||data.ujian_id||examId);const sourceType=String(data.question_type||data.tipe_soal||'MULTIPLE_CHOICE').trim().toUpperCase();data.question_type=({'1':'MULTIPLE_CHOICE','2':'MULTIPLE_RESPONSE','3':'SHORT_ANSWER','PILIHAN GANDA':'MULTIPLE_CHOICE','PILIHAN_GANDA':'MULTIPLE_CHOICE','PILIHAN GANDA KOMPLEKS':'MULTIPLE_RESPONSE','PILIHAN_GANDA_KOMPLEKS':'MULTIPLE_RESPONSE','ISIAN SINGKAT':'SHORT_ANSWER','ISIAN_SINGKAT':'SHORT_ANSWER'} as Record<string,string>)[sourceType]??sourceType;data.question_text=String(data.question_text||data.pertanyaan||'');for(const key of ['a','b','c','d','e'])data[`option_${key}`]=String(data[`option_${key}`]||data[`opsi_${key}`]||'');data.correct_answer=String(data.correct_answer||data.jawaban_benar||'');data.points=Number(data.points||data.poin||1);return Object.fromEntries(columns.map(key=>[key,data[key]]));});}
function normalizeJsonRow(row:Record<string,unknown>,examId:number){const type=String(row.question_type??row.tipe_soal??'MULTIPLE_CHOICE').toUpperCase();const mapped=({'1':'MULTIPLE_CHOICE','2':'MULTIPLE_RESPONSE','3':'SHORT_ANSWER','PILIHAN GANDA':'MULTIPLE_CHOICE','PILIHAN_GANDA':'MULTIPLE_CHOICE','PILIHAN GANDA KOMPLEKS':'MULTIPLE_RESPONSE','PILIHAN_GANDA_KOMPLEKS':'MULTIPLE_RESPONSE','ISIAN SINGKAT':'SHORT_ANSWER','ISIAN_SINGKAT':'SHORT_ANSWER'} as Record<string,string>)[type]??type;return {exam_id:Number(row.exam_id??row.ujian_id??examId),question_type:mapped,question_text:String(row.question_text??row.pertanyaan??''),option_a:String(row.option_a??row.opsi_a??''),option_b:String(row.option_b??row.opsi_b??''),option_c:String(row.option_c??row.opsi_c??''),option_d:String(row.option_d??row.opsi_d??''),option_e:String(row.option_e??row.opsi_e??''),correct_answer:String(row.correct_answer??row.jawaban_benar??''),points:Number(row.points??row.poin??1)};}
function importErrors(row:Record<string,unknown>){const errors:string[]=[];if(!Number.isSafeInteger(Number(row.exam_id))||Number(row.exam_id)<1)errors.push('ID ujian');if(!String(row.question_text??'').trim())errors.push('pertanyaan');if(!['MULTIPLE_CHOICE','MULTIPLE_RESPONSE','SHORT_ANSWER'].includes(String(row.question_type)))errors.push('jenis soal');if(!String(row.correct_answer??'').trim())errors.push('kunci');if(!(Number(row.points)>0))errors.push('bobot');if(row.question_type!=='SHORT_ANSWER'){for(const key of ['a','b','c','d'])if(!String(row[`option_${key}`]??'').trim())errors.push(`opsi ${key.toUpperCase()}`);const keys=String(row.correct_answer??'').toUpperCase().split(',').map(x=>x.trim()).filter(Boolean);if(row.question_type==='MULTIPLE_CHOICE'&&keys.length!==1||row.question_type==='MULTIPLE_RESPONSE'&&keys.length<2||keys.some(key=>!['A','B','C','D','E'].includes(key)||!String(row[`option_${key.toLowerCase()}`]??'').trim()))errors.push('kunci tidak cocok dengan opsi');}return errors;}

export function QuestionBank({initialExamId}:{initialExamId?:number}={}){
 const [exams,setExams]=useState<Exam[]>([]),[examId,setExamId]=useState(''),[items,setItems]=useState<Question[]>([]),[page,setPage]=useState(1),[draft,setDraft]=useState<Draft|null>(null),[editing,setEditing]=useState<number|null>(null),[preview,setPreview]=useState(false),[importRows,setImportRows]=useState<Record<string,unknown>[]>([]),[jsonText,setJsonText]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{void api<Exam[]>('/api/admin/exams').then(rows=>{setExams(rows);if(initialExamId&&rows.some(exam=>exam.id===initialExamId))setExamId(String(initialExamId));}).catch(e=>setNotice(e.message));},[initialExamId]);
 useEffect(()=>{if(preview){const engine=(window as unknown as {MathJax?:{typesetPromise?:()=>Promise<void>}}).MathJax;void engine?.typesetPromise?.();}},[preview]);
 async function load(nextPage=page){setBusy(true);try{const result=await api<{items:Question[]}>(`/api/admin/questions?page=${nextPage}&limit=50${examId?`&exam_id=${examId}`:''}`);setItems(result.items);setPage(nextPage);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load(1);},[examId]);
 function edit(row?:Question){setDraft(row?Object.fromEntries(columns.map(key=>[key,row[key as keyof Question]])) as Draft:empty(Number(examId||exams[0]?.id||0)));setEditing(row?.id??null);setPreview(false);}
 async function save(event:React.FormEvent){event.preventDefault();if(!draft)return;setBusy(true);setNotice('');try{await api(editing?`/api/admin/questions/${editing}`:'/api/admin/questions',{method:editing?'PUT':'POST',body:draft});setDraft(null);setNotice('Soal tersimpan');await load(1);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function remove(id:number){if(!confirm('Hapus soal ini?'))return;setBusy(true);try{await api(`/api/admin/questions/${id}`,{method:'DELETE'});setNotice('Soal dihapus');await load();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File){if(file.size>2*1024*1024)throw new Error('Gambar maksimal 2 MB');setBusy(true);try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await api<{url:string}>('/api/admin/question-images',{method:'POST',body:{base64:btoa(binary)}});setNotice('Gambar berhasil diunggah');return result.url;}catch(e){setNotice((e as Error).message);throw e;}finally{setBusy(false);}}
 async function importCsv(file:File){try{const rows=normalizeCsv(await file.text(),Number(examId));if(!rows.length)throw new Error('Tidak ada baris soal');if(rows.length>1000)throw new Error('Maksimal 1.000 baris per file');setImportRows(rows);setNotice(`${rows.length} baris siap diperiksa sebelum impor`);}catch(e){setNotice((e as Error).message);}}
 async function commitImport(){setBusy(true);let inserted=0,failed=0;const failedRows:Record<string,unknown>[]=[];try{let batch:Record<string,unknown>[]=[];let size=0;const send=async()=>{if(!batch.length)return;const result=await api<{inserted:number;failed:number;errors:{row:number;error:string}[]}>('/api/admin/questions/import',{method:'POST',body:{rows:batch}});inserted+=result.inserted;failed+=result.failed;for(const error of result.errors)if(batch[error.row-1])failedRows.push(batch[error.row-1]);batch=[];size=0;};for(const row of importRows){const length=new TextEncoder().encode(JSON.stringify(row)).length;if(length>50000)throw new Error('Satu baris terlalu besar untuk impor; pendekkan konten');if(batch.length>=20||size+length>50000)await send();batch.push(row);size+=length;}await send();setImportRows(failedRows);setNotice(`Impor selesai: ${inserted} masuk, ${failed} gagal${failed?', baris gagal tetap dalam pratinjau':''}`);await load(1);}catch(e){setNotice(`${(e as Error).message}. ${inserted} soal sudah masuk; periksa daftar sebelum mengulang.`);}finally{setBusy(false);}}
 const field=(key:keyof Draft,label:string,multi=false)=><label style={{display:'block',margin:'8px 0'}}>{label}{multi?<textarea required={key==='question_text'} value={String(draft?.[key]??'')} onChange={e=>setDraft(draft&&{...draft,[key]:e.target.value})} rows={key==='question_text'?5:2} style={{display:'block',width:'100%',boxSizing:'border-box'}}/>:<input required={key==='correct_answer'} value={String(draft?.[key]??'')} onChange={e=>setDraft(draft&&{...draft,[key]:e.target.value})} style={{display:'block',width:'100%',boxSizing:'border-box'}}/>}</label>;
 return <section><h3>Bank soal</h3>{notice&&<p role="status">{notice}</p>}<label>Ujian <select value={examId} onChange={e=>setExamId(e.target.value)}><option value="">Semua ujian</option>{exams.map(exam=><option key={exam.id} value={exam.id}>{exam.name} · {exam.grade}</option>)}</select></label> <button disabled={busy||!exams.length} onClick={()=>edit()}>Tambah soal</button> <button disabled={!examId} onClick={()=>{const exam=exams.find(item=>String(item.id)===examId);if(exam)downloadTemplate(exam);}}>Unduh template ujian terpilih</button> <button onClick={()=>download('bank-soal-arena.csv',csv([columns,...items.map(item=>columns.map(key=>String(item[key as keyof Question]??'')))]))}>Ekspor halaman CSV</button>
 <div style={{marginTop:14}}><h4 style={{marginBottom:8}}>Katalog template per ujian</h4>{!exams.length?<p>Belum ada ujian.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Nama ujian</th><th>Tingkat</th><th>ID Arena</th><th>Template</th></tr></thead><tbody>{exams.map(exam=><tr key={exam.id}><td>{exam.name}</td><td>{exam.grade}</td><td>{exam.id}</td><td><button type="button" onClick={()=>downloadTemplate(exam)}>Unduh template {exam.name}</button></td></tr>)}</tbody></table></div>}</div>
 <p>Impor CSV dapat dibuka di Excel. Pilih ujian terlebih dahulu jika file tidak punya kolom exam_id.</p><input type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void importCsv(file);e.target.value='';}}/><details><summary>Impor JSON (format Arena/CBT)</summary><textarea value={jsonText} onChange={e=>setJsonText(e.target.value)} rows={5} style={{display:'block',width:'100%',boxSizing:'border-box'}}/><button onClick={()=>{try{const rows=JSON.parse(jsonText) as Record<string,unknown>[];if(!Array.isArray(rows)||!rows.length||rows.length>200)throw new Error('Isi dengan array 1–200 soal');setImportRows(rows.map(row=>normalizeJsonRow(row,Number(examId))));setNotice(`${rows.length} baris JSON siap diimpor`);}catch(e){setNotice((e as Error).message);}}}>Periksa JSON</button></details>
 {importRows.length>0&&<div style={{border:'1px solid #d9e2ec',padding:12,marginTop:12}}><b>Pratinjau impor: {importRows.length} soal · {importRows.filter(row=>importErrors(row).length).length} baris perlu diperbaiki</b><ol>{importRows.map((row,index)=>({row,index,errors:importErrors(row)})).filter(item=>item.errors.length).slice(0,20).map(({row,index,errors})=><li key={index}>Baris {index+2}: {errors.join(', ')} · {String(row.question_text).slice(0,80)}</li>)}</ol><p>Contoh: {importRows.slice(0,3).map(row=>String(row.question_text).slice(0,70)).join(' | ')}</p><button disabled={busy||importRows.some(row=>importErrors(row).length>0)} onClick={()=>void commitImport()}>Konfirmasi impor</button> <button onClick={()=>setImportRows([])}>Batal</button></div>}
 {draft&&<form onSubmit={e=>void save(e)} style={{border:'1px solid #d9e2ec',padding:16,marginTop:12}}><h4>{editing?'Ubah':'Tambah'} soal</h4><label>Ujian <select required value={draft.exam_id||''} onChange={e=>setDraft({...draft,exam_id:Number(e.target.value)})}><option value="">Pilih</option>{exams.map(exam=><option key={exam.id} value={exam.id}>{exam.name}</option>)}</select></label> <label>Jenis <select value={draft.question_type} onChange={e=>setDraft({...draft,question_type:e.target.value as Draft['question_type']})}><option value="MULTIPLE_CHOICE">Pilihan ganda</option><option value="MULTIPLE_RESPONSE">Pilihan kompleks</option><option value="SHORT_ANSWER">Isian singkat</option></select></label><RichContentEditor label="Pertanyaan" required value={draft.question_text} onChange={value=>setDraft(current=>current&&({...current,question_text:value}))} onUpload={upload}/>{draft.question_type!=='SHORT_ANSWER'&&(['a','b','c','d','e'] as const).map(key=><RichContentEditor key={key} label={`Opsi ${key.toUpperCase()}`} value={draft[`option_${key}`]||''} onChange={value=>setDraft(current=>current&&({...current,[`option_${key}`]:value}))} onUpload={upload}/>)}{field('correct_answer',draft.question_type==='SHORT_ANSWER'?'Jawaban benar (pisahkan alternatif dengan |)':'Kunci (contoh A atau A,C)')}<label>Bobot <input type="number" min="0.01" max="1000" step="0.01" value={draft.points} onChange={e=>setDraft({...draft,points:Number(e.target.value)})}/></label><div><button disabled={busy||!draft.question_text.trim()}>Simpan</button> <button type="button" onClick={()=>setPreview(!preview)}>Pratinjau</button> <button type="button" onClick={()=>setDraft(null)}>Batal</button></div>{preview&&<article dir="auto" style={{padding:12,background:'#f7fafc',fontFamily:'"Noto Naskh Arabic","Noto Sans Arabic","Segoe UI",sans-serif',unicodeBidi:'plaintext'}}><div dangerouslySetInnerHTML={{__html:previewHtml(draft.question_text)}}/>{(['a','b','c','d','e'] as const).map(key=>draft[`option_${key}`]&&<p dir="auto" key={key}>{key.toUpperCase()}. <span dangerouslySetInnerHTML={{__html:previewHtml(draft[`option_${key}`]||'')}}/></p>)}</article>}</form>}
 <div style={{overflowX:'auto',marginTop:12}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Ujian</th><th>Pertanyaan</th><th>Jenis</th><th>Bobot</th><th>Aksi</th></tr></thead><tbody>{items.map(row=><tr key={row.id}><td>{exams.find(e=>e.id===row.exam_id)?.name||row.exam_id}</td><td>{row.question_text.replace(/<[^>]+>/g,' ').slice(0,150)}</td><td>{row.question_type}</td><td>{row.points}</td><td><button onClick={()=>edit(row)}>Ubah</button> <button disabled={busy} onClick={()=>void remove(row.id)}>Hapus</button></td></tr>)}</tbody></table></div><button disabled={busy||page<=1} onClick={()=>void load(page-1)}>Sebelumnya</button> <span>Halaman {page}</span> <button disabled={busy||items.length<50} onClick={()=>void load(page+1)}>Berikutnya</button></section>;
}
