import React, { useEffect, useRef, useState } from 'react';
import { api } from './lib/api';
import { exportExcel, safeFilename } from './lib/spreadsheet';

type Row=Record<string,unknown>;
const card:React.CSSProperties={border:'1px solid #d9e2ec',borderRadius:10,padding:14,margin:'10px 0'};
function value(row:Row,key:string){return String(row[key]??'—');}

export function StaffOperations({view,admin}:{view:string;admin:boolean}){
 const [rows,setRows]=useState<Row[]>([]),[exams,setExams]=useState<Row[]>([]),[people,setPeople]=useState<{teachers:Row[];employees:Row[]}>({teachers:[],employees:[]}),[results,setResults]=useState<Row[]>([]),[selectedExam,setSelectedExam]=useState(''),[page,setPage]=useState(1),[resultPage,setResultPage]=useState(1),[personType,setPersonType]=useState<'teacher'|'employee'>('teacher'),[personId,setPersonId]=useState(''),[assignedExam,setAssignedExam]=useState(''),[duty,setDuty]=useState<'TEACHER'|'PROCTOR'>('TEACHER'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[lastLoaded,setLastLoaded]=useState<Date|null>(null);
 const pageRef=useRef(1);
 const path=view==='dashboard'?'/api/teacher/dashboard':view==='sessions'?(admin?'/api/admin/live-sessions':'/api/teacher/live-sessions'):view==='violations'?(admin?'/api/admin/violations':'/api/staff/violations'):'/api/admin/teacher-assignments';
 async function load(nextPage=pageRef.current){if(document.hidden)return;try{const response=await api<unknown>(['sessions','violations'].includes(view)?`${path}?page=${nextPage}&limit=100`:path);setRows(Array.isArray(response)?response:((response as {exams?:Row[];items?:Row[]}).exams??(response as {items?:Row[]}).items??[]));pageRef.current=nextPage;setPage(nextPage);setLastLoaded(new Date());}catch(e){setNotice((e as Error).message);}}
 useEffect(()=>{setRows([]);setNotice('');void load(1);if(view==='assignments'&&admin){void Promise.all([api<Row[]>('/api/admin/exams'),api<typeof people>('/api/admin/personnel')]).then(([examRows,staffRows])=>{setExams(examRows);setPeople(staffRows);}).catch(e=>setNotice((e as Error).message));}const onVisible=()=>{if(!document.hidden)void load();};document.addEventListener('visibilitychange',onVisible);const timer=view==='sessions'||view==='violations'?window.setInterval(()=>{if(!document.hidden)void load();},45_000):0;return()=>{document.removeEventListener('visibilitychange',onVisible);if(timer)clearInterval(timer);};},[path,view,admin]);
 async function report(id:string,nextPage=1){setSelectedExam(id);if(!id){setResults([]);return;}setBusy(true);try{const data=await api<{items:Row[]}>(`/api/teacher/exams/${id}/results?page=${nextPage}`);setResults(data.items);setResultPage(nextPage);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function exportResults(){const exam=rows.find(row=>String(row.id)===selectedExam),name=String(exam?.name??`ujian-${selectedExam}`);setBusy(true);setNotice('Menyiapkan seluruh hasil ujian…');try{const all:Row[]=[];for(let next=1;next<=1000;next++){const response=await api<{items:Row[]}>(`/api/teacher/exams/${selectedExam}/results?page=${next}`);all.push(...response.items);if(response.items.length<100)break;}exportExcel(`hasil-${safeFilename(name)}.xlsx`,[{name:'Hasil Ujian',rows:[['NISN','Nama siswa','Kelas','Status','Nilai','Benar','Salah','Kosong','Waktu selesai'],...all.map(row=>[row.nisn,row.name_snapshot,row.class_snapshot,row.status,row.score,row.correct_count,row.wrong_count,row.blank_count,row.completed_at])],widths:[18,30,18,16,12,10,10,10,24]}]);setNotice(`${all.length} hasil diekspor ke Excel`);}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function addAssignment(event:React.FormEvent){event.preventDefault();if(!personId)return;setBusy(true);try{await api('/api/admin/teacher-assignments',{method:'POST',body:{teacher_id:personType==='teacher'?Number(personId):null,employee_id:personType==='employee'?Number(personId):null,exam_id:assignedExam?Number(assignedExam):null,duty_role:duty}});setNotice('Penugasan tersimpan');await load();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function removeAssignment(id:number){if(!confirm('Hapus penugasan ini?'))return;setBusy(true);try{await api(`/api/admin/teacher-assignments/${id}`,{method:'DELETE'});setNotice('Penugasan dihapus');await load();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function eligibility(person:Row){setBusy(true);try{await api(`/api/admin/teachers/${person.id}/proctor-eligibility`,{method:'POST',body:{eligible:!Boolean(person.proctor_eligible)}});setPeople(previous=>({...previous,teachers:previous.teachers.map(row=>row.id===person.id?{...row,proctor_eligible:!Boolean(row.proctor_eligible)}:row)}));}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 return <div style={card}><h3>{({dashboard:'Ujian yang ditugaskan',sessions:'Sesi peserta aktif',violations:'Pelanggaran ujian',assignments:'Penugasan guru dan pengawas'} as Record<string,string>)[view]}</h3><p><button disabled={busy} onClick={()=>void load()}>Muat ulang</button> {lastLoaded&&<small>Diperbarui {lastLoaded.toLocaleTimeString('id-ID')}{view==='sessions'||view==='violations'?' · otomatis tiap 45 detik saat tab terbuka':''}</small>}</p>{notice&&<p role="status">{notice}</p>}
 {view==='dashboard'&&<><div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Ujian</th><th>Jadwal</th><th>Status</th><th>Peserta</th><th>Berlangsung</th><th>Hasil</th></tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}><td>{value(row,'name')}</td><td>{new Date(String(row.starts_at)).toLocaleString('id-ID')}</td><td>{value(row,'status')}</td><td>{value(row,'attempts')}</td><td>{value(row,'in_progress')}</td><td><button onClick={()=>void report(String(row.id))}>Lihat hasil</button></td></tr>)}</tbody></table></div>{selectedExam&&<section style={card}><h4>Hasil ujian #{selectedExam}</h4><button type="button" disabled={busy||!results.length} onClick={()=>void exportResults()}>Unduh seluruh hasil Excel</button><div style={{overflowX:'auto',maxHeight:400}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>NISN</th><th>Nama</th><th>Kelas</th><th>Status</th><th>Nilai</th><th>Benar</th><th>Salah</th><th>Kosong</th></tr></thead><tbody>{results.map((row,index)=><tr key={index}><td>{value(row,'nisn')}</td><td>{value(row,'name_snapshot')}</td><td>{value(row,'class_snapshot')}</td><td>{value(row,'status')}</td><td>{value(row,'score')}</td><td>{value(row,'correct_count')}</td><td>{value(row,'wrong_count')}</td><td>{value(row,'blank_count')}</td></tr>)}</tbody></table></div><button disabled={busy||resultPage<=1} onClick={()=>void report(selectedExam,resultPage-1)}>Sebelumnya</button> Halaman {resultPage} <button disabled={busy||results.length<100} onClick={()=>void report(selectedExam,resultPage+1)}>Berikutnya</button></section>}</>}
 {view==='sessions'&&<div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Peserta</th><th>Kelas</th><th>Ujian</th><th>Mulai</th><th>Batas waktu</th><th>Pelanggaran</th><th>Koneksi terakhir</th></tr></thead><tbody>{rows.map(row=><tr key={String(row.public_id)}><td>{value(row,'name_snapshot')}<br/><small>{value(row,'nisn')}</small></td><td>{value(row,'class_snapshot')}</td><td>{value(row,'exam_name')}</td><td>{new Date(String(row.started_at)).toLocaleString('id-ID')}</td><td>{new Date(String(row.expires_at)).toLocaleString('id-ID')}</td><td>{value(row,'violation_count')}</td><td>{row.last_seen_at?new Date(String(row.last_seen_at)).toLocaleString('id-ID'):'—'}</td></tr>)}</tbody></table>{!rows.length&&<p>Belum ada sesi aktif dalam cakupan tugas Anda.</p>}<button disabled={page<=1} onClick={()=>void load(page-1)}>Sebelumnya</button> Halaman {page} <button disabled={rows.length<100} onClick={()=>void load(page+1)}>Berikutnya</button></div>}
 {view==='violations'&&<div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Waktu</th><th>Peserta</th><th>Ujian</th><th>Jenis</th><th>Jumlah</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}><td>{new Date(String(row.occurred_at)).toLocaleString('id-ID')}</td><td>{value(row,'name_snapshot')} · {value(row,'nisn')}</td><td>{value(row,'exam_name')}</td><td>{value(row,'type')}</td><td>{value(row,'violation_count')}</td><td>{value(row,'attempt_status')}</td></tr>)}</tbody></table><button disabled={page<=1} onClick={()=>void load(page-1)}>Sebelumnya</button> Halaman {page} <button disabled={rows.length<100} onClick={()=>void load(page+1)}>Berikutnya</button></div>}
 {view==='assignments'&&admin&&<><form onSubmit={e=>void addAssignment(e)} style={card}><h4>Buat penugasan</h4><label>Personel <select value={personType} onChange={e=>{setPersonType(e.target.value as 'teacher'|'employee');setPersonId('');}}><option value="teacher">Guru</option><option value="employee">Pegawai</option></select></label> <select required value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Pilih personel</option>{(personType==='teacher'?people.teachers:people.employees).filter(person=>person.status==='ACTIVE').map(person=><option key={String(person.id)} value={String(person.id)}>{value(person,'name')}</option>)}</select> <label>Peran <select value={duty} onChange={e=>setDuty(e.target.value as 'TEACHER'|'PROCTOR')}><option value="TEACHER">Guru pengampu</option><option value="PROCTOR">Pengawas</option></select></label> <label>Ujian <select value={assignedExam} onChange={e=>setAssignedExam(e.target.value)}><option value="">Seluruh ujian (pengawas)</option>{exams.map(exam=><option key={String(exam.id)} value={String(exam.id)}>{value(exam,'name')}</option>)}</select></label> <button disabled={busy||!personId||(!assignedExam&&duty==='TEACHER')}>Simpan tugas</button></form><div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Personel</th><th>Peran</th><th>Ujian</th><th>Aksi</th></tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}><td>{String(row.teacher_name??row.employee_name)}</td><td>{value(row,'duty_role')}</td><td>{row.exam_name?String(row.exam_name):'Seluruh ujian'}</td><td><button disabled={busy} onClick={()=>void removeAssignment(Number(row.id))}>Hapus</button></td></tr>)}</tbody></table></div><h4>Kelayakan pengawas guru</h4>{people.teachers.map(person=><label key={String(person.id)} style={{display:'inline-block',margin:6}}><input type="checkbox" checked={Boolean(person.proctor_eligible)} disabled={busy} onChange={()=>void eligibility(person)}/>{value(person,'name')}</label>)}</>}
 </div>;
}
