import React, { useEffect, useRef, useState } from 'react';
import { api, mutationId } from './lib/api';

export type ExamQuestion={id:number;tipe:string;pertanyaan:string;opsi:{key:string;text:string}[];poin:number};
export type ExamAttempt={attempt_id:string;exam:{id:number;nama_ujian:string};expires_at:string;server_time?:string;soal:ExamQuestion[];jawaban:{question_id:number;answer:string|null;is_flagged:boolean;revision:number}[]};
export type ExamResult={status?:string;nilai?:number;benar?:number;salah?:number;kosong?:number;jumlah_soal?:number;is_remedial?:boolean;score_cap?:number|null;follow_up_type?:string|null};
const card:React.CSSProperties={border:'1px solid #d9e2ec',borderRadius:12,padding:16,margin:'12px 0'};

export function StudentExam({attempt,answers,flags,busy,change,toggleFlag,submit,onTerminated,children}:{attempt:ExamAttempt;answers:Record<number,string>;flags:Record<number,boolean>;busy:boolean;change:(question:ExamQuestion,value:string)=>void;toggleFlag:(question:ExamQuestion)=>void;submit:(finalizeOnly?:boolean)=>Promise<void>;onTerminated:(result:ExamResult|null)=>void;children?:React.ReactNode}){
 const [remaining,setRemaining]=useState(0),[warning,setWarning]=useState(''),[current,setCurrent]=useState(0);const lastEvent=useRef<Record<string,number>>({}),submitting=useRef(false),fullscreenRequested=useRef(false),submitRef=useRef(submit);
 submitRef.current=submit;
 const offset=useRef(attempt.server_time?Date.parse(attempt.server_time)-Date.now():0);
 useEffect(()=>{offset.current=attempt.server_time?Date.parse(attempt.server_time)-Date.now():0;submitting.current=false;const tick=()=>{const seconds=Math.max(0,Math.ceil((Date.parse(attempt.expires_at)-Date.now()-offset.current)/1000));setRemaining(seconds);if(seconds===0&&!submitting.current){submitting.current=true;void submitRef.current(true).catch(()=>setWarning('Waktu habis. Periksa koneksi lalu muat ulang hasil.'));}};tick();const timer=window.setInterval(tick,1000);return()=>clearInterval(timer);},[attempt.attempt_id]);
 useEffect(()=>{let active=true;const record=(type:string)=>{if(busy||submitting.current)return;const now=Date.now();if(now-(lastEvent.current[type]??0)<5000)return;lastEvent.current[type]=now;void api<{count:number;terminated:boolean;hasil?:ExamResult}>(`/api/student/exams/${attempt.exam.id}/violations`,{method:'POST',body:{event_key:mutationId(),type}}).then(result=>{if(!active)return;if(result.terminated){submitting.current=true;onTerminated({...result.hasil,status:'TERMINATED'});}else setWarning(`Pelanggaran tercatat (${result.count}/3). Tetap di halaman ujian.`);}).catch(error=>{if(active)setWarning(`Pelanggaran belum tercatat: ${(error as Error).message}`);});};
 const visibility=()=>{if(document.hidden)record('TAB_HIDDEN');};
 const copy=(event:ClipboardEvent)=>{event.preventDefault();record('COPY_ATTEMPT');};
 const keydown=(event:KeyboardEvent)=>{const key=event.key.toLowerCase();const platform=navigator.platform.toLowerCase();const screenshot=event.key==='PrintScreen'||(platform.includes('win')&&event.metaKey&&event.shiftKey&&key==='s')||(platform.includes('mac')&&event.metaKey&&event.shiftKey&&['3','4','5'].includes(key));if(!event.repeat&&screenshot){event.preventDefault();record('SCREENSHOT_ATTEMPT');}};
 const fullscreen=()=>{if(fullscreenRequested.current&&!document.fullscreenElement)record('FULLSCREEN_EXIT');};
 let viewportTimer=0,constrained=false;const viewport=()=>{clearTimeout(viewportTimer);viewportTimer=window.setTimeout(()=>{if(document.hidden||navigator.maxTouchPoints<1||document.activeElement?.matches('input,textarea,select')||Math.min(screen.width,screen.height)>600||!screen.width||!screen.height)return;const current=window.innerWidth/screen.width<0.72||window.innerHeight/screen.height<0.58;if(current&&!constrained)record('SPLIT_SCREEN_SUSPECTED');constrained=current;},1500);};
 document.addEventListener('visibilitychange',visibility);document.addEventListener('copy',copy,true);document.addEventListener('keydown',keydown,true);document.addEventListener('fullscreenchange',fullscreen);window.addEventListener('resize',viewport);viewport();return()=>{active=false;document.removeEventListener('visibilitychange',visibility);document.removeEventListener('copy',copy,true);document.removeEventListener('keydown',keydown,true);document.removeEventListener('fullscreenchange',fullscreen);window.removeEventListener('resize',viewport);clearTimeout(viewportTimer);};},[attempt.attempt_id,busy]);
  const question=attempt.soal[current];const minutes=Math.floor(remaining/60),seconds=remaining%60;
  useEffect(()=>{const engine=(window as unknown as {MathJax?:{typesetPromise?:()=>Promise<void>}}).MathJax;void engine?.typesetPromise?.();},[question?.id]);
 return <section><h2>{attempt.exam.nama_ujian}</h2><p><strong aria-live="off">Sisa waktu {String(minutes).padStart(2,'0')}:{String(seconds).padStart(2,'0')}</strong> · Berakhir {new Date(attempt.expires_at).toLocaleString('id-ID')}</p><button type="button" onClick={()=>{fullscreenRequested.current=true;void document.documentElement.requestFullscreen?.().catch(()=>{fullscreenRequested.current=false;setWarning('Mode layar penuh tidak tersedia pada perangkat ini.');});}}>Layar penuh</button>{warning&&<p role="status" style={{color:'#a04400'}}>{warning}</p>}
 <nav aria-label="Nomor soal" style={{display:'flex',gap:6,flexWrap:'wrap',margin:'12px 0'}}>{attempt.soal.map((item,index)=><button type="button" key={item.id} aria-current={index===current?'step':undefined} onClick={()=>setCurrent(index)} style={{fontWeight:index===current?700:400,background:flags[item.id]?'#fff3c4':answers[item.id]?'#ddf4e9':undefined}}>{index+1}</button>)}</nav>
  {question&&<article style={card}><h3>Soal {current+1} dari {attempt.soal.length}</h3><button type="button" aria-pressed={flags[question.id]??false} onClick={()=>toggleFlag(question)}>{flags[question.id]?'Hapus tanda ragu':'Tandai ragu'}</button><div dir="auto" style={{fontFamily:'"Noto Naskh Arabic","Noto Sans Arabic","Segoe UI",sans-serif',unicodeBidi:'plaintext',lineHeight:1.75}} dangerouslySetInnerHTML={{__html:question.pertanyaan}}/>{question.tipe==='SHORT_ANSWER'?<input dir="auto" maxLength={500} value={answers[question.id]??''} onChange={e=>change(question,e.target.value)} style={{width:'100%',padding:10,boxSizing:'border-box'}}/>:question.opsi.map(option=><label key={option.key} style={{display:'grid',gridTemplateColumns:'auto minmax(0,1fr)',gap:6,padding:8}}><input type={question.tipe==='MULTIPLE_RESPONSE'?'checkbox':'radio'} name={`question-${question.id}`} checked={(answers[question.id]??'').split(',').includes(option.key)} onChange={e=>{const selected=new Set((answers[question.id]??'').split(',').filter(Boolean));if(question.tipe==='MULTIPLE_RESPONSE')e.target.checked?selected.add(option.key):selected.delete(option.key);else{selected.clear();selected.add(option.key);}change(question,[...selected].sort().join(','));}}/> <span dir="auto" style={{fontFamily:'"Noto Naskh Arabic","Noto Sans Arabic","Segoe UI",sans-serif',unicodeBidi:'plaintext',lineHeight:1.75}}><b dir="ltr">{option.key}.</b> <span dangerouslySetInnerHTML={{__html:option.text}}/></span></label>)}</article>}
 <div style={{display:'flex',gap:8}}><button disabled={current===0} onClick={()=>setCurrent(current-1)}>Sebelumnya</button><button disabled={current>=attempt.soal.length-1} onClick={()=>setCurrent(current+1)}>Berikutnya</button><button disabled={busy||remaining===0} onClick={()=>{if(confirm('Selesaikan ujian sekarang?')){submitting.current=true;void submit(false).catch(()=>{submitting.current=false;});}}}>Selesaikan ujian</button></div><p>{Object.values(answers).filter(Boolean).length} dari {attempt.soal.length} soal terjawab · {Object.values(flags).filter(Boolean).length} ditandai ragu</p>{children}</section>;
}

export function StudentResult({result,review,onClose}:{result:ExamResult;review:{soal:{id:number;pertanyaan?:string;status:string}[]}|null;onClose:()=>void}){return <section style={card}><h2>Hasil ujian</h2><p>Status: {result.status??'selesai'}</p>{result.nilai!==undefined&&<><p style={{fontSize:28,fontWeight:700}}>Nilai {result.nilai}</p><p>Benar {result.benar??0} · Salah {result.salah??0} · Kosong {result.kosong??0}</p></>}{(result.is_remedial||result.follow_up_type==='REMEDIAL')&&<p>Nilai remedial mengikuti batas maksimum yang berlaku{result.score_cap!=null?`: ${result.score_cap}`:''}.</p>}{review&&<><h3>Review jawaban</h3><ol>{review.soal.map((item,index)=><li key={item.id} style={card}><b>Soal {index+1}: {item.status}</b>{item.pertanyaan&&<div dangerouslySetInnerHTML={{__html:item.pertanyaan}}/>}</li>)}</ol></>}<button onClick={onClose}>Kembali ke daftar ujian</button></section>;}
