import React,{createContext,useContext,useEffect,useRef,useState}from'react';import{ChevronLeft,ChevronRight,X}from'lucide-react';import type{PageMeta}from'../lib/api';
export function PageHeader({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className="pagehead"><div><small>Portal Data / {title}</small><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function LoadingSkeleton({rows=4}:{rows?:number}){return <div className="loading" aria-busy="true" aria-label="Memuat">{Array.from({length:rows},(_,i)=><i key={i}/>)}</div>};export function EmptyState({title='Belum ada data',description}:{title?:string;description?:string}){return <section className="state"><h3>{title}</h3>{description&&<p>{description}</p>}</section>};export function ErrorState({retry}:{retry:()=>void}){return <section className="state" role="alert"><p>Data gagal dimuat.</p><button onClick={retry}>Coba lagi</button></section>}
export function StatusBadge({value}:{value:string|boolean}){const label=typeof value==='boolean'?(value?'Aktif':'Tidak aktif'):value.replaceAll('_',' ');return <span className={`badge ${String(value).toLowerCase()}`}>{label}</span>}
export function ServerPagination({meta,onPage}:{meta?:PageMeta|undefined;onPage:(page:number)=>void}){if(!meta||meta.totalPages<=1)return null;return <div className="pagination"><button aria-label="Halaman sebelumnya" disabled={meta.page<=1} onClick={()=>onPage(meta.page-1)}><ChevronLeft/></button><span>Halaman {meta.page} dari {meta.totalPages} · {meta.total} data</span><button aria-label="Halaman berikutnya" disabled={meta.page>=meta.totalPages} onClick={()=>onPage(meta.page+1)}><ChevronRight/></button></div>}
export function FormField({label,error,children}:{label:string;error?:string|undefined;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}{error&&<small role="alert">{error}</small>}</label>}
export function DetailItem({label,value}:{label:string;value:React.ReactNode}){return <div className="detail"><small>{label}</small><strong>{value??'—'}</strong></div>}
export function Modal({title,open,onClose,children}:{title:string;open:boolean;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDivElement>(null),trigger=useRef<HTMLElement|null>(null);useEffect(()=>{if(open){trigger.current=document.activeElement as HTMLElement;ref.current?.focus()}else trigger.current?.focus()},[open]);if(!open)return null;function keys(e:React.KeyboardEvent){if(e.key==='Escape'){onClose();return}if(e.key==='Tab'){const nodes=[...ref.current!.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0]!,last=nodes[nodes.length-1]!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}return <div className="overlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref} onKeyDown={keys}><header><h2>{title}</h2><button aria-label="Tutup" onClick={onClose}><X/></button></header>{children}</div></div>}
export function ConfirmDialog({open,title,description,busy,onConfirm,onClose}:{open:boolean;title:string;description:string;busy?:boolean;onConfirm:()=>void;onClose:()=>void}){return <Modal open={open} title={title} onClose={onClose}><p>{description}</p><div className="actions"><button onClick={onClose} disabled={busy}>Batal</button><button className="danger" onClick={onConfirm} disabled={busy}>{busy?'Memproses…':'Ya, lanjutkan'}</button></div></Modal>}
type Toast={id:number;kind:'success'|'error'|'warning'|'info';message:string};const ToastContext=createContext<(message:string,kind?:Toast['kind'])=>void>(()=>undefined);export function ToastProvider({children}:{children:React.ReactNode}){const[list,setList]=useState<Toast[]>([]);function push(message:string,kind:Toast['kind']='success'){const id=Date.now();setList(v=>[...v,{id,kind,message}]);setTimeout(()=>setList(v=>v.filter(x=>x.id!==id)),3500)}return <ToastContext.Provider value={push}>{children}<div className="toasts" aria-live="polite">{list.map(t=><div key={t.id} className={`toast ${t.kind}`}>{t.message}</div>)}</div></ToastContext.Provider>}export const useToast=()=>useContext(ToastContext);
