<?php
declare(strict_types=1);
namespace Cbt\Services;
use Cbt\Core\Database;
use Cbt\Exceptions\DomainException;
use Cbt\Repositories\AttemptRepository;
final class ScoringService
{
 public function __construct(private Database$db,private AttemptRepository$attempts){}
 public function submit(int$studentId,int$examId):array{return$this->db->transaction(function()use($studentId,$examId){$attempt=$this->attempts->find($studentId,$examId,true)??throw new DomainException('Sesi ujian tidak ditemukan.',404);$existing=$this->attempts->result((int)$attempt['id']);if($existing)return$this->format($existing);if($attempt['status']!=='IN_PROGRESS')throw new DomainException('Ujian tidak dapat disubmit.',409);$sql='SELECT q.id,q.correct_answer,q.points,a.answer FROM questions q LEFT JOIN student_answers a ON a.question_id=q.id AND a.attempt_id=:attempt WHERE q.exam_id=:exam AND q.status=\'ACTIVE\'';$statement=$this->db->pdo()->prepare($sql);$statement->execute(['attempt'=>$attempt['id'],'exam'=>$examId]);$rows=$statement->fetchAll();if(!$rows)throw new DomainException('Soal ujian tidak ditemukan.',409);$correct=$wrong=$blank=0;$earned=$maximum=0.0;foreach($rows as$row){$maximum+=(float)$row['points'];if($row['answer']===null){$blank++;}elseif(hash_equals($row['correct_answer'],$row['answer'])){$correct++;$earned+=(float)$row['points'];}else{$wrong++;}}$score=$maximum>0?round($earned/$maximum*100,2):0.0;$insert=$this->db->pdo()->prepare('INSERT INTO exam_results(attempt_id,question_count,correct_count,wrong_count,blank_count,earned_points,maximum_points,score) VALUES(:attempt,:total,:correct,:wrong,:blank,:earned,:maximum,:score)');$insert->execute(['attempt'=>$attempt['id'],'total'=>count($rows),'correct'=>$correct,'wrong'=>$wrong,'blank'=>$blank,'earned'=>$earned,'maximum'=>$maximum,'score'=>$score]);$this->db->pdo()->prepare("UPDATE exam_attempts SET status='COMPLETED',completed_at=UTC_TIMESTAMP(3) WHERE id=:id")->execute(['id'=>$attempt['id']]);return['jumlah_soal'=>count($rows),'benar'=>$correct,'salah'=>$wrong,'kosong'=>$blank,'total_poin'=>$earned,'nilai'=>$score,'status'=>'selesai'];});}
 private function format(array$r):array{return['jumlah_soal'=>(int)$r['question_count'],'benar'=>(int)$r['correct_count'],'salah'=>(int)$r['wrong_count'],'kosong'=>(int)$r['blank_count'],'total_poin'=>(float)$r['earned_points'],'nilai'=>(float)$r['score'],'status'=>'selesai'];}
 public function review(int$studentId,int$examId):array{$attempt=$this->attempts->find($studentId,$examId)??throw new DomainException('Sesi ujian tidak ditemukan.',404);if($attempt['status']!=='COMPLETED')throw new DomainException('Review hanya tersedia setelah ujian selesai.',403);$sql='SELECT q.id,q.question_text,q.correct_answer,a.answer FROM questions q LEFT JOIN student_answers a ON a.question_id=q.id AND a.attempt_id=:attempt WHERE q.exam_id=:exam AND q.status=\'ACTIVE\'';$s=$this->db->pdo()->prepare($sql);$s->execute(['attempt'=>$attempt['id'],'exam'=>$examId]);$rows=$s->fetchAll();return['soal'=>array_map(fn($r)=>['id'=>(int)$r['id'],'pertanyaan'=>$r['question_text'],'jawaban_benar'=>$r['correct_answer']],$rows),'jawaban'=>array_map(fn($r)=>['soal_id'=>(int)$r['id'],'jawaban'=>$r['answer']],$rows)];}
}
