<?php
declare(strict_types=1);
namespace Cbt\Services;
use Cbt\Core\Database;
use Cbt\Exceptions\DomainException;
use Cbt\Support\Id;
use PDO;
final class StaffAdminCommunicationService
{
 private const CATEGORIES=['TECHNICAL','ASSISTANCE','EXAM_REPORT','EMERGENCY','OTHER'];
 private const STATUSES=['OPEN','READ','IN_PROGRESS','RESOLVED'];
 public function __construct(private Database$db){}
 public function threads(array$auth):array{$this->authorize($auth);$admin=($auth['role']??'')==='ADMIN';$where=$admin?'':' WHERE t.created_by=:user';$q=$this->db->pdo()->prepare("SELECT t.public_id,t.category,t.subject,t.status,t.created_at,t.updated_at,t.resolved_at,u.name creator_name,(SELECT message FROM staff_admin_messages lm WHERE lm.thread_id=t.id ORDER BY lm.id DESC LIMIT 1) last_message,(SELECT COUNT(*) FROM staff_admin_messages um WHERE um.thread_id=t.id AND um.sender_user_id<>:viewer AND um.read_at IS NULL) unread_count FROM staff_admin_threads t JOIN users u ON u.id=t.created_by{$where} ORDER BY (t.status='RESOLVED'),t.updated_at DESC LIMIT 200");$params=['viewer'=>(int)$auth['user_id']];if(!$admin)$params['user']=(int)$auth['user_id'];$q->execute($params);return array_map([$this,'mapThread'],$q->fetchAll());}
 public function create(array$auth,array$data):array{$this->authorize($auth,true);$category=strtoupper(trim((string)($data['category']??'OTHER')));$subject=trim((string)($data['subject']??''));$message=trim((string)($data['message']??''));if(!in_array($category,self::CATEGORIES,true))throw new DomainException('Kategori komunikasi tidak valid.',422);if(mb_strlen($subject)<4||mb_strlen($subject)>180)throw new DomainException('Subjek wajib 4–180 karakter.',422);$this->validateMessage($message);$attachment=$this->attachment((string)($data['attachment']??''));return$this->db->transaction(function(PDO$pdo)use($auth,$category,$subject,$message,$attachment){$public=Id::ulid();$pdo->prepare("INSERT INTO staff_admin_threads(public_id,created_by,category,subject,status) VALUES(?,?,?,?,'OPEN')")->execute([$public,(int)$auth['user_id'],$category,$subject]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO staff_admin_messages(thread_id,sender_user_id,message,attachment_path) VALUES(?,?,?,?)')->execute([$id,(int)$auth['user_id'],$message,$attachment]);return['id'=>$public];});}
 public function messages(array$auth,string$public):array{$thread=$this->thread($auth,$public);$pdo=$this->db->pdo();$pdo->prepare('UPDATE staff_admin_messages SET read_at=COALESCE(read_at,UTC_TIMESTAMP(3)) WHERE thread_id=? AND sender_user_id<>?')->execute([$thread['id'],(int)$auth['user_id']]);if(($auth['role']??'')==='ADMIN'&&$thread['status']==='OPEN')$pdo->prepare("UPDATE staff_admin_threads SET status='READ' WHERE id=?")->execute([$thread['id']]);$q=$pdo->prepare('SELECT m.id,m.message,m.attachment_path,m.read_at,m.created_at,m.sender_user_id,u.name sender_name,u.role sender_role FROM staff_admin_messages m JOIN users u ON u.id=m.sender_user_id WHERE m.thread_id=? ORDER BY m.id');$q->execute([$thread['id']]);return array_map(fn($r)=>['id'=>(int)$r['id'],'message'=>$r['message'],'attachment'=>$r['attachment_path'],'sentAt'=>$r['created_at'].'Z','readAt'=>$r['read_at']?$r['read_at'].'Z':null,'mine'=>(int)$r['sender_user_id']===(int)$auth['user_id'],'senderName'=>$r['sender_name'],'senderRole'=>$r['sender_role']],$q->fetchAll());}
 public function reply(array$auth,string$public,array$data):void{$thread=$this->thread($auth,$public);if($thread['status']==='RESOLVED')throw new DomainException('Percakapan sudah selesai.',409);$message=trim((string)($data['message']??''));$this->validateMessage($message);$attachment=$this->attachment((string)($data['attachment']??''));$this->db->transaction(function(PDO$pdo)use($thread,$auth,$message,$attachment){$pdo->prepare('INSERT INTO staff_admin_messages(thread_id,sender_user_id,message,attachment_path) VALUES(?,?,?,?)')->execute([$thread['id'],(int)$auth['user_id'],$message,$attachment]);$status=($auth['role']??'')==='ADMIN'?'IN_PROGRESS':'OPEN';$pdo->prepare('UPDATE staff_admin_threads SET status=?,resolved_at=NULL WHERE id=?')->execute([$status,$thread['id']]);});}
 public function status(array$auth,string$public,string$status):void{if(($auth['role']??'')!=='ADMIN')throw new DomainException('Hanya admin yang dapat mengubah status percakapan.',403);$thread=$this->thread($auth,$public);$status=strtoupper(trim($status));if(!in_array($status,self::STATUSES,true))throw new DomainException('Status tidak valid.',422);$this->db->pdo()->prepare('UPDATE staff_admin_threads SET status=?,resolved_at=? WHERE id=?')->execute([$status,$status==='RESOLVED'?gmdate('Y-m-d H:i:s'):null,$thread['id']]);}
 private function authorize(array$auth,bool$proctorOnly=false):void{$this->ensureTables();if(($auth['role']??'')==='ADMIN')return;if(!in_array(($auth['role']??''),['TEACHER','EMPLOYEE'],true))throw new DomainException('Akses komunikasi ditolak.',403);$q=$this->db->pdo()->prepare("SELECT EXISTS(SELECT 1 FROM users u JOIN teacher_exam_assignments a ON (u.teacher_id IS NOT NULL AND a.teacher_id=u.teacher_id) OR (u.employee_id IS NOT NULL AND a.employee_id=u.employee_id) WHERE u.id=? AND a.duty_role='PROCTOR' AND a.exam_id IS NULL)");$q->execute([(int)($auth['user_id']??0)]);if(!$q->fetchColumn())throw new DomainException('Fitur komunikasi hanya untuk petugas piket.',403);}
 private function ensureTables():void{try{$pdo=$this->db->pdo();$pdo->exec("CREATE TABLE IF NOT EXISTS staff_admin_threads (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(26) NOT NULL,created_by BIGINT UNSIGNED NOT NULL,category ENUM('TECHNICAL','ASSISTANCE','EXAM_REPORT','EMERGENCY','OTHER') NOT NULL,subject VARCHAR(180) NOT NULL,status ENUM('OPEN','READ','IN_PROGRESS','RESOLVED') NOT NULL DEFAULT 'OPEN',resolved_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE KEY uq_staff_admin_thread_public(public_id),KEY idx_staff_admin_thread_status(status,updated_at),CONSTRAINT fk_staff_admin_thread_creator FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$pdo->exec("CREATE TABLE IF NOT EXISTS staff_admin_messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,thread_id BIGINT UNSIGNED NOT NULL,sender_user_id BIGINT UNSIGNED NOT NULL,message VARCHAR(2000) NOT NULL,attachment_path VARCHAR(255) NULL,read_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),KEY idx_staff_admin_message_thread(thread_id,id),CONSTRAINT fk_staff_admin_message_thread FOREIGN KEY(thread_id) REFERENCES staff_admin_threads(id) ON DELETE CASCADE,CONSTRAINT fk_staff_admin_message_sender FOREIGN KEY(sender_user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}catch(\PDOException){throw new DomainException('Fitur komunikasi belum siap. Jalankan migrasi database CBT terbaru.',503);}}
 private function thread(array$auth,string$public):array{$this->authorize($auth);$sql='SELECT * FROM staff_admin_threads WHERE public_id=?';$params=[$public];if(($auth['role']??'')!=='ADMIN'){$sql.=' AND created_by=?';$params[]=(int)$auth['user_id'];}$q=$this->db->pdo()->prepare($sql);$q->execute($params);return$q->fetch()?:throw new DomainException('Percakapan tidak ditemukan.',404);}
 private function validateMessage(string$message):void{if(mb_strlen($message)<2||mb_strlen($message)>2000)throw new DomainException('Pesan wajib 2–2000 karakter.',422);}
 private function attachment(string$data):?string{if($data==='')return null;if(strlen($data)>2800000||!preg_match('~^data:image/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$~D',$data,$m))throw new DomainException('Lampiran harus PNG, JPEG, atau WebP maksimal 2 MB.',422);$bytes=base64_decode($m[2],true);if($bytes===false||strlen($bytes)>2000000||@getimagesizefromstring($bytes)===false)throw new DomainException('Lampiran gambar tidak valid.',422);$ext=$m[1]==='jpeg'?'jpg':$m[1];$name=hash('sha256',$bytes).'.'.$ext;$dir=dirname(__DIR__,2).'/public/assets/uploads/staff-chat';if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new \RuntimeException('Folder lampiran tidak dapat dibuat.');$path=$dir.'/'.$name;if(!is_file($path)&&file_put_contents($path,$bytes,LOCK_EX)===false)throw new \RuntimeException('Lampiran gagal disimpan.');return'assets/uploads/staff-chat/'.$name;}
 private function mapThread(array$r):array{return['id'=>$r['public_id'],'category'=>$r['category'],'subject'=>$r['subject'],'status'=>$r['status'],'creatorName'=>$r['creator_name'],'lastMessage'=>$r['last_message'],'unread'=>(int)$r['unread_count'],'createdAt'=>$r['created_at'].'Z','updatedAt'=>$r['updated_at'].'Z','resolvedAt'=>$r['resolved_at']?$r['resolved_at'].'Z':null];}
}
