import axios from 'axios';
const $=s=>document.querySelector(s),api=axios;api.defaults.headers.common['X-Requested-With']='XMLHttpRequest';api.defaults.headers.common['X-CSRF-TOKEN']=$('meta[name="csrf-token"]').content;api.defaults.headers.common.Accept='application/json';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),message=e=>e.response?.data?.message||'Permintaan gagal. Silakan coba kembali.';
function notice(text,bad=false){const n=$('#notice');n.textContent=text;n.classList.toggle('bad',bad);n.hidden=false;setTimeout(()=>n.hidden=true,5000)}
async function dashboard(){try{const[{data:s},{data:q},{data:a}]=await Promise.all([api.get('/api/v1/dashboard/summary'),api.get('/api/v1/dashboard/data-quality'),api.get('/api/v1/dashboard/recent-activities')]);const d=s.data;$('#period').textContent=[d.activeAcademicYear?.name,d.activeSemester?.type].filter(Boolean).join(' · ')||'Periode belum aktif';$('#metrics').innerHTML=[['Siswa aktif',d.students],['Guru aktif',d.teachers],['Kelas aktif',d.classes]].map(x=>`<article class="metric"><span>${x[0]}</span><b>${x[1]}</b></article>`).join('');$('#quality').innerHTML=[['Tanpa enrollment',q.data.studentsWithoutEnrollment],['Telepon belum valid',q.data.studentsWithoutValidPhone],['RFID belum tersedia',q.data.studentsWithoutRfid]].map(x=>`<div class="quality"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#activities').innerHTML=a.data.length?a.data.map(x=>`<div class="activity"><b>${esc(x.action)}</b><small>${esc(x.entityType||'Sistem')} · ${new Date(x.createdAt).toLocaleString('id-ID')}</small></div>`).join(''):'<p class="muted">Belum ada aktivitas.</p>'}catch(e){notice(message(e),true)}}
async function imports(){try{const{data}=await api.get('/api/v1/imports?perPage=12');$('#import-history').innerHTML=data.data.length?`<table><thead><tr><th>File</th><th>Status</th><th>Total</th><th>Warning</th><th>Dibuat</th></tr></thead><tbody>${data.data.map(x=>`<tr><td>${esc(x.originalFilename)}</td><td><span class="status ${x.status}">${esc(x.status)}</span></td><td>${x.totalRows}</td><td>${x.warningRows}</td><td>${new Date(x.createdAt).toLocaleDateString('id-ID')}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">Belum ada riwayat import.</p>'}catch(e){$('#import-history').innerHTML=`<p class="error">${esc(message(e))}</p>`}}
function enter(user){$('#login').hidden=true;$('#portal').hidden=false;$('#account-name').textContent=user.name;$('#account-role').textContent=user.role.replaceAll('_',' ');$('#admin-nav').hidden=user.role!=='SUPER_ADMIN';document.querySelector('[data-page="sso"]').hidden=!['SUPER_ADMIN','DATA_ADMIN'].includes(user.role);dashboard()}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const err=$('#login-error');err.hidden=true;try{const{data}=await api.post('/api/v1/auth/admin/login',Object.fromEntries(new FormData(e.currentTarget)));enter(data.data)}catch(x){err.textContent=message(x);err.hidden=false}});$('#logout').addEventListener('click',async()=>{await api.post('/api/v1/auth/admin/logout');location.reload()});document.querySelectorAll('.nav').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===x));document.querySelectorAll('.page').forEach(n=>n.hidden=n.id!==`${x.dataset.page}-page`);$('#title').textContent={dashboard:'Ringkasan sekolah',imports:'Import data siswa',sso:'Aplikasi SSO',admins:'Pengguna admin',profile:'Profil & keamanan'}[x.dataset.page];if(x.dataset.page==='imports')imports();if(x.dataset.page==='sso')sso();if(x.dataset.page==='admins')admins();if(x.dataset.page==='profile')profile()}));$('#import-file').addEventListener('change',e=>$('#file-name').textContent=e.target.files[0]?.name||'Belum ada file');$('#refresh-imports').addEventListener('click',imports);
$('#import-form').addEventListener('submit',async e=>{e.preventDefault();try{const{data}=await api.post('/api/v1/imports/students/validate',new FormData(e.currentTarget));const x=data.data,s=x.summary,r=$('#import-result');r.innerHTML=`<b>Validasi selesai</b><dl><div><dt>Total</dt><dd>${s.totalRows}</dd></div><div><dt>Valid</dt><dd>${s.validRows}</dd></div><div><dt>Warning</dt><dd>${s.warningRows}</dd></div><div><dt>Gagal</dt><dd>${s.failedRows}</dd></div></dl><button id="commit">Commit import</button>`;r.hidden=false;$('#commit').onclick=async()=>{try{await api.post(`/api/v1/imports/students/${x.importPublicId}/commit`);notice('Import berhasil disimpan.');r.hidden=true;imports()}catch(z){notice(message(z),true)}};imports()}catch(x){notice(message(x),true)}});
async function admins(){try{const{data}=await api.get('/api/v1/admin-users?perPage=100');$('#admin-list').innerHTML=data.data.map(x=>`<div class="record"><div><b>${esc(x.name)}</b><small>${esc(x.email)} · ${esc(x.role)} · ${esc(x.status)}</small></div>${x.status==='ACTIVE'?`<button data-admin-disable="${x.publicId}">Nonaktifkan</button>`:''}</div>`).join('')||'<p class="muted">Belum ada pengguna.</p>';document.querySelectorAll('[data-admin-disable]').forEach(x=>x.onclick=async()=>{try{await api.post(`/api/v1/admin-users/${x.dataset.adminDisable}/deactivate`);notice('Pengguna dinonaktifkan.');admins()}catch(e){notice(message(e),true)}})}catch(e){notice(message(e),true)}}
$('#admin-form').onsubmit=async e=>{e.preventDefault();try{await api.post('/api/v1/admin-users',Object.fromEntries(new FormData(e.currentTarget)));e.currentTarget.reset();notice('Pengguna admin dibuat.');admins()}catch(x){notice(message(x),true)}};
async function profile(){try{const[{data:p},{data:s}]=await Promise.all([api.get('/api/v1/profile'),api.get('/api/v1/profile/sessions')]);const f=$('#profile-form');f.name.value=p.data.name;f.email.value=p.data.email;$('#admin-sessions').innerHTML=s.data.map(x=>`<div class="record"><div><b>${esc(x.device)}${x.current?' · saat ini':''}</b><small>${esc(x.ipAddress||'—')} · ${new Date(x.lastUsedAt).toLocaleString('id-ID')}</small></div><button data-admin-session="${x.publicId}">Cabut</button></div>`).join('');document.querySelectorAll('[data-admin-session]').forEach(x=>x.onclick=async()=>{await api.delete(`/api/v1/profile/sessions/${x.dataset.adminSession}`);profile()})}catch(e){notice(message(e),true)}}
$('#profile-form').onsubmit=async e=>{e.preventDefault();try{await api.patch('/api/v1/profile',Object.fromEntries(new FormData(e.currentTarget)));notice('Profil diperbarui.');profile()}catch(x){notice(message(x),true)}};$('#admin-password-form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));if(p.newPassword!==p.newPassword_confirmation)return notice('Konfirmasi password tidak sama.',true);try{await api.post('/api/v1/profile/change-password',p);e.currentTarget.reset();notice('Password diperbarui dan session lain dicabut.')}catch(x){notice(message(x),true)}};$('#admin-logout-all').onclick=async()=>{await api.post('/api/v1/profile/logout-all');location.reload()};
async function sso(){try{const[{data:a},{data:t}]=await Promise.all([api.get('/api/v1/sso/applications'),api.get('/api/v1/teachers?perPage=100&status=ACTIVE')]);$('#sso-list').innerHTML=a.data.map(x=>`<div class="record"><div><b>${esc(x.name)}</b><small class="code">${esc(x.clientId)}</small><small>${esc((x.redirectUris||[]).join(', '))}</small></div><span class="status">${esc(x.status)}</span></div>`).join('')||'<p class="muted">Belum ada aplikasi.</p>';const f=$('#sso-access-form');f.application.innerHTML=a.data.map(x=>`<option value="${x.publicId}">${esc(x.name)}</option>`).join('');f.teacherPublicId.innerHTML=t.data.map(x=>`<option value="${x.publicId}">${esc(x.fullName)}</option>`).join('')}catch(e){notice(message(e),true)}}
$('#sso-form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));try{await api.post('/api/v1/sso/applications',{name:p.name,slug:p.slug,redirectUris:[p.redirectUri],postLogoutRedirectUris:p.logoutUri?[p.logoutUri]:[]});e.currentTarget.reset();notice('Aplikasi SSO dibuat.');sso()}catch(x){notice(message(x),true)}};$('#sso-access-form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));try{await api.post(`/api/v1/sso/applications/${p.application}/access`,{teacherPublicId:p.teacherPublicId,role:p.role});notice('Akses guru diberikan.')}catch(x){notice(message(x),true)}};
api.get('/api/v1/auth/admin/me').then(x=>enter(x.data.data)).catch(()=>$('#login').hidden=false);

const masterConfig={students:{title:'Data siswa',endpoint:'/students',fields:[['nisn','NISN','text'],['fullName','Nama siswa','text'],['parentPhone','Telepon orang tua','text'],['address','Alamat','textarea'],['rfidUid','RFID UID','text'],['status','Status','select:ACTIVE,INACTIVE,GRADUATED,TRANSFERRED,DROPPED_OUT']]},teachers:{title:'Data guru',endpoint:'/teachers',fields:[['fullName','Nama guru','text'],['nip','NIP','text'],['nuptk','NUPTK','text'],['employeeNumber','Nomor pegawai','text'],['email','Email','email'],['phone','Telepon','text'],['address','Alamat','textarea'],['gender','Jenis kelamin','select:MALE,FEMALE'],['status','Status','select:ACTIVE,INACTIVE,RETIRED,TRANSFERRED']]},classes:{title:'Data kelas',endpoint:'/classes',fields:[['academicYearPublicId','Tahun ajaran','years'],['code','Kode kelas','text'],['name','Nama kelas','text'],['gradeLevel','Tingkat','number'],['homeroomTeacherPublicId','Wali kelas','teachers'],['status','Status','select:ACTIVE,INACTIVE,ARCHIVED']]},years:{title:'Tahun ajaran',endpoint:'/academic-years',fields:[['name','Nama (contoh 2026/2027)','text'],['startDate','Mulai','date'],['endDate','Selesai','date'],['isActive','Aktif','checkbox']]},semesters:{title:'Semester',endpoint:'/semesters',fields:[['academicYearPublicId','Tahun ajaran','years'],['type','Jenis','select:ODD,EVEN'],['startDate','Mulai','date'],['endDate','Selesai','date']]}};
let masterKind='students',masterItems=[],masterEditing=null;
const fieldInput=(f,v='')=>{const [key,label,type]=f;if(type==='textarea')return `<label class="full">${label}<textarea name="${key}" rows="3">${esc(v)}</textarea></label>`;if(type==='checkbox')return `<label><span>${label}</span><input name="${key}" type="checkbox" ${v?'checked':''}></label>`;if(type.startsWith('select:'))return `<label>${label}<select name="${key}">${type.slice(7).split(',').map(x=>`<option value="${x}" ${x===v?'selected':''}>${x}</option>`).join('')}</select></label>`;return `<label>${label}<input name="${key}" type="${type}" value="${esc(v)}"></label>`};
async function loadOptions(type){const r=await api.get(type==='years'?'/api/v1/academic-years':'/api/v1/teachers?status=ACTIVE&perPage=100');return r.data.data||[]}
async function masterForm(item=null){const c=masterConfig[masterKind];masterEditing=item;const form=$('#master-form');let html='';for(const f of c.fields){const value=item?.[f[0]]??'';if(f[2]==='years'||f[2]==='teachers'){const opts=await loadOptions(f[2]);html+=`<label>${f[1]}<select name="${f[0]}"><option value="">Pilih</option>${opts.map(x=>`<option value="${x.publicId}" ${value===x.publicId?'selected':''}>${esc(x.name||x.fullName)}</option>`).join('')}</select></label>`}else html+=fieldInput(f,value)}html+='<div class="form-actions"><button type="submit">Simpan</button><button type="button" id="master-cancel" class="outline">Batal</button></div>';form.innerHTML=html;form.hidden=false;$('#master-table').hidden=true;$('#master-cancel').onclick=()=>{form.hidden=true;$('#master-table').hidden=false};form.onsubmit=async e=>{e.preventDefault();const body={};for(const f of c.fields){const el=e.currentTarget.elements[f[0]];if(el.type==='checkbox')body[f[0]]=el.checked;else if(el.value!=='')body[f[0]]=el.value}try{await api({url:`/api/v1${masterEditing?`${c.endpoint}/${masterEditing.publicId}`:c.endpoint}`,method:masterEditing?'patch':'post',data:body});notice(`${c.title} berhasil disimpan.`);form.hidden=true;$('#master-table').hidden=false;masterLoad()}catch(x){notice(message(x),true)}}}
function masterRows(){const c=masterConfig[masterKind];if(!masterItems.length)return '<p class="muted">Belum ada data.</p>';return `<table><thead><tr>${c.fields.slice(0,5).map(f=>`<th>${f[1]}</th>`).join('')}<th>Aksi</th></tr></thead><tbody>${masterItems.map(x=>`<tr>${c.fields.slice(0,5).map(f=>`<td>${esc(x[f[0]]?.name||x[f[0]]?.fullName||x[f[0]]||'—')}</td>`).join('')}<td><button data-edit="${x.publicId}">Edit</button></td></tr>`).join('')}</tbody></table>`}
async function masterLoad(){const c=masterConfig[masterKind];try{const r=await api.get(`/api/v1${c.endpoint}?perPage=100`);masterItems=r.data.data||[];$('#master-heading').textContent=c.title;$('#master-table').innerHTML=masterRows();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>masterForm(masterItems.find(x=>x.publicId===b.dataset.edit)));$('#master-export').hidden=!['students','teachers'].includes(masterKind);$('#master-export').onclick=()=>location.assign(`/api/v1/exports/${masterKind}`)}catch(x){notice(message(x),true)}}
async function masterOpen(kind){masterKind=kind;$('#master-form').hidden=true;$('#master-table').hidden=false;if(kind==='years'||kind==='semesters'){const other=kind==='years'?'semesters':'years';$('#master-overline').innerHTML=`Master data · <button type="button" class="compact" id="switch-period">${other==='years'?'Tahun ajaran':'Semester'}</button>`;setTimeout(()=>$('#switch-period').onclick=()=>masterOpen(other),0)}else $('#master-overline').textContent='Master data';masterLoad()}
document.querySelectorAll('[data-page="students"],[data-page="teachers"],[data-page="classes"]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=true);$('#master-page').hidden=false;masterOpen(b.dataset.page)}));
document.querySelector('[data-page="periods"]').addEventListener('click',()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=true);$('#master-page').hidden=false;masterOpen('years')});
$('#master-new').addEventListener('click',()=>masterForm());
document.querySelector('[data-page="audit"]').addEventListener('click',async()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=true);$('#audit-page').hidden=false;try{const r=await api.get('/api/v1/audit-logs?perPage=100');$('#audit-table').innerHTML=`<table><thead><tr><th>Waktu</th><th>Aktor</th><th>Aksi</th><th>Entitas</th></tr></thead><tbody>${(r.data.data||[]).map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('id-ID')}</td><td>${esc(x.actorType)}</td><td>${esc(x.action)}</td><td>${esc(x.entityType||'')}</td></tr>`).join('')}</tbody></table>`}catch(x){notice(message(x),true)}});
async function auditLoad(){const form=$('#audit-filters'), params=new URLSearchParams(new FormData(form));params.set('perPage','100');if(params.get('dateFrom')&&params.get('dateTo')&&params.get('dateFrom')>params.get('dateTo'))return notice('Tanggal awal tidak boleh setelah tanggal akhir.',true);try{const r=await api.get(`/api/v1/audit-logs?${params}`);const rows=r.data.data||[];$('#audit-table').innerHTML=rows.length?`<table><thead><tr><th>Waktu</th><th>Aktor</th><th>Aksi</th><th>Entitas</th><th>Detail</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('id-ID')}</td><td>${esc(x.actorType)}<br><small>${esc(x.actorPublicId||'—')}</small></td><td>${esc(x.action)}</td><td>${esc(x.entityType||'—')}<br><small>${esc(x.entityPublicId||'')}</small></td><td><button data-audit="${x.publicId}">Lihat</button></td></tr>`).join('')}</tbody></table>`:'<p class="muted">Audit log kosong.</p>';document.querySelectorAll('[data-audit]').forEach(b=>b.onclick=async()=>{try{const d=await api.get(`/api/v1/audit-logs/${b.dataset.audit}`);const x=d.data.data;$('#audit-detail').innerHTML=`<h3>Detail ${esc(x.action)}</h3><p>${esc(x.requestMethod||'')} ${esc(x.requestPath||'')} · ${esc(x.ipAddress||'—')}</p><pre class="code-block">${esc(JSON.stringify({oldValues:x.oldValues,newValues:x.newValues},null,2))}</pre>`;$('#audit-detail').hidden=false}catch(e){notice(message(e),true)}})}catch(x){notice(message(x),true)}}
$('#audit-filters').addEventListener('submit',e=>{e.preventDefault();auditLoad()});$('#audit-reset').addEventListener('click',()=>{$('#audit-filters').reset();auditLoad()});
document.querySelector('[data-page="guide"]').addEventListener('click',()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=true);$('#guide-page').hidden=false});
