import axios from 'axios';
const $=s=>document.querySelector(s),api=axios;api.defaults.headers.common['X-Requested-With']='XMLHttpRequest';api.defaults.headers.common['X-CSRF-TOKEN']=$('meta[name="csrf-token"]').content;api.defaults.headers.common.Accept='application/json';const msg=e=>e.response?.data?.message||'Permintaan gagal.',esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let profile;function toast(text,bad=false){const n=$('#teacher-notice');n.textContent=text;n.classList.toggle('bad',bad);n.hidden=false;setTimeout(()=>n.hidden=true,5000)}
async function loadProfile(){const{data}=await api.get('/api/v1/teacher/profile');profile=data.data;$('#teacher-name').textContent=profile.fullName;$('#teacher-username').textContent=profile.username;$('#teacher-greeting').textContent=`Halo, ${profile.fullName}`;const f=$('#teacher-profile-form');f.email.value=profile.email||'';f.phone.value=profile.phone||'';f.address.value=profile.address||'';$('#photo-preview').innerHTML=profile.photoUrl?`<img src="${profile.photoUrl}?v=${Date.now()}" alt="Foto ${esc(profile.fullName)}">`:esc(profile.fullName.slice(0,2).toUpperCase());$('#teacher-identifiers').innerHTML=[['NIP',profile.nip],['NUPTK',profile.nuptk],['Nomor pegawai',profile.employeeNumber],['Status akun',profile.accountStatus]].map(x=>`<div><dt>${x[0]}</dt><dd>${esc(x[1]||'—')}</dd></div>`).join('')}
async function sessions(){try{const{data}=await api.get('/api/v1/teacher/sessions');$('#teacher-sessions').innerHTML=data.data.length?data.data.map(x=>`<div class="session-row"><div><b>${esc(x.device)}${x.current?' · saat ini':''}</b><small>${esc(x.ipAddress||'—')} · ${new Date(x.lastUsedAt).toLocaleString('id-ID')}</small></div><button data-session="${x.publicId}">Cabut</button></div>`).join(''):'<p class="muted">Tidak ada session aktif.</p>';document.querySelectorAll('[data-session]').forEach(x=>x.onclick=async()=>{await api.delete(`/api/v1/teacher/sessions/${x.dataset.session}`);if(x.closest('.session-row').textContent.includes('saat ini'))location.assign('/teacher/login');else sessions()})}catch(e){toast(msg(e),true)}}
function enter(me){$('#teacher-login').hidden=true;$('#teacher-portal').hidden=false;$('#teacher-name').textContent=me.fullName;$('#teacher-username').textContent=me.username;loadProfile().catch(e=>toast(msg(e),true))}
$('#teacher-login-form').onsubmit=async e=>{e.preventDefault();const error=$('#teacher-login-error');error.hidden=true;try{const{data}=await api.post('/api/v1/auth/teacher/login',Object.fromEntries(new FormData(e.currentTarget)));const returnTo=new URLSearchParams(location.search).get('returnTo');if(returnTo?.startsWith('/oidc/authorize'))location.assign(returnTo);else enter(data.data)}catch(x){error.textContent=msg(x);error.hidden=false}};
document.querySelectorAll('[data-teacher-page]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-teacher-page]').forEach(n=>n.classList.toggle('active',n===x));document.querySelectorAll('.teacher-page').forEach(n=>n.hidden=n.id!==`teacher-${x.dataset.teacherPage}-page`);$('#teacher-title').textContent={home:'Beranda guru',profile:'Profil guru',security:'Keamanan akun'}[x.dataset.teacherPage];if(x.dataset.teacherPage==='profile')loadProfile();if(x.dataset.teacherPage==='security')sessions()});
$('#teacher-profile-form').onsubmit=async e=>{e.preventDefault();try{await api.patch('/api/v1/teacher/profile',Object.fromEntries(new FormData(e.currentTarget)));toast('Profil berhasil diperbarui.');loadProfile()}catch(x){toast(msg(x),true)}};$('#photo-form').onsubmit=async e=>{e.preventDefault();try{await api.post('/api/v1/teacher/profile/photo',new FormData(e.currentTarget));toast('Foto berhasil diperbarui.');loadProfile()}catch(x){toast(msg(x),true)}};$('#teacher-password-form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));if(p.newPassword!==p.confirmation)return toast('Konfirmasi password tidak sama.',true);try{await api.post('/api/v1/teacher/profile/change-password',p);e.currentTarget.reset();toast('Password berhasil diubah.')}catch(x){toast(msg(x),true)}};$('#teacher-logout').onclick=async()=>{await api.post('/api/v1/auth/teacher/logout');location.assign('/teacher/login')};$('#teacher-logout-all').onclick=async()=>{await api.post('/api/v1/teacher/sessions/logout-all');location.assign('/teacher/login')};
async function setup(){const token=new URLSearchParams(location.search).get('token');$('#teacher-setup').hidden=false;if(!token){$('#setup-person').textContent='Token tidak tersedia.';return}try{const{data}=await api.get(`/api/v1/auth/teacher/password-setup/validate?token=${encodeURIComponent(token)}`);if(!data.data.valid){$('#setup-person').textContent='Link tidak valid, kedaluwarsa, atau telah digunakan.';return}$('#setup-person').textContent=`${data.data.account.fullName} · ${data.data.account.username}`;$('#setup-form').hidden=false;$('#setup-form').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));try{await api.post('/api/v1/auth/teacher/password-setup',{token,password:p.password,password_confirmation:p.password_confirmation});location.assign('/teacher/login')}catch(x){const n=$('#setup-error');n.textContent=msg(x);n.hidden=false}}}catch(e){$('#setup-person').textContent=msg(e)}}
if(location.pathname==='/teacher/setup-password')setup();else api.get('/api/v1/auth/teacher/me').then(x=>enter(x.data.data)).catch(()=>$('#teacher-login').hidden=false);
