<?php
namespace App\Application\Journal;

use App\Infrastructure\Database\Connection;
use App\Support\Config;
use App\Support\Ulid;
use InvalidArgumentException;
use PDO;
use RuntimeException;
use Throwable;

final class JournalService
{
    private const ACTIVITIES=['MATERIAL','PRACTICE','DISCUSSION','ASSIGNMENT','TEST','REMEDIAL','ENRICHMENT','OTHER'];
    public function __construct(private readonly Connection $database,private readonly Config $config){}

    public function list(array $actor,array $filters=[]):array
    {
        $page=max(1,(int)($filters['page']??1));$perPage=min(50,max(10,(int)($filters['perPage']??15)));$where=['j.teacher_public_id=:teacher','j.deleted_at IS NULL'];$params=['teacher'=>$actor['portal_teacher_public_id']];
        if(!empty($filters['status'])&&in_array($filters['status'],['DRAFT','FINAL','AMENDED'],true)){$where[]='j.status=:status';$params['status']=$filters['status'];}
        if(!empty($filters['search'])){$where[]='(j.topic LIKE :search OR j.class_name_snapshot LIKE :search OR j.subject_name_snapshot LIKE :search)';$params['search']='%'.substr((string)$filters['search'],0,100).'%';}
        $sql=' FROM journals j WHERE '.implode(' AND ',$where);$count=$this->database->pdo()->prepare('SELECT COUNT(*)'.$sql);$count->execute($params);$total=(int)$count->fetchColumn();
        $query=$this->database->pdo()->prepare('SELECT j.public_id AS publicId,j.journal_number AS journalNumber,j.journal_date AS journalDate,j.class_name_snapshot AS className,j.subject_name_snapshot AS subjectName,j.period_start AS periodStart,j.period_end AS periodEnd,j.activity_type AS activityType,j.topic,j.status,j.finalized_at AS finalizedAt,(SELECT COUNT(*) FROM journal_documentations d WHERE d.journal_id=j.id AND d.deleted_at IS NULL) AS documentationCount'.$sql.' ORDER BY j.journal_date DESC,j.created_at DESC LIMIT :limit OFFSET :offset');foreach($params as $key=>$value)$query->bindValue(':'.$key,$value);$query->bindValue(':limit',$perPage,PDO::PARAM_INT);$query->bindValue(':offset',($page-1)*$perPage,PDO::PARAM_INT);$query->execute();return ['items'=>$query->fetchAll(),'meta'=>['page'=>$page,'perPage'=>$perPage,'total'=>$total,'totalPages'=>(int)ceil($total/$perPage)]];
    }

    public function availableAttendance(array $actor):array
    {
        $query=$this->database->pdo()->prepare("SELECT a.public_id AS publicId,a.attendance_date AS date,a.class_name_snapshot AS className,a.subject_name_snapshot AS subjectName,a.period_start AS periodStart,a.period_end AS periodEnd FROM attendance_sessions a LEFT JOIN journals j ON j.attendance_session_id=a.id WHERE a.teacher_public_id=:teacher AND a.status='FINAL' AND j.id IS NULL ORDER BY a.attendance_date DESC");$query->execute(['teacher'=>$actor['portal_teacher_public_id']]);return $query->fetchAll();
    }

    public function create(array $input,array $actor):array
    {
        $attendanceId=(string)($input['attendancePublicId']??'');$activity=(string)($input['activityType']??'');$topic=trim((string)($input['topic']??''));if(!preg_match('/^[0-9A-HJKMNP-TV-Z]{26}$/',$attendanceId))throw new InvalidArgumentException('Referensi absensi tidak valid.');if(!in_array($activity,self::ACTIVITIES,true))throw new InvalidArgumentException('Jenis kegiatan tidak valid.');if(mb_strlen($topic)<5||mb_strlen($topic)>2000)throw new InvalidArgumentException('Pokok bahasan harus 5–2000 karakter.');$note=$this->nullable($input['teacherNote']??null,2000);
        $pdo=$this->database->pdo();$attendance=$pdo->prepare("SELECT * FROM attendance_sessions WHERE public_id=:id AND teacher_public_id=:teacher AND status='FINAL' AND journal_id IS NULL LIMIT 1");$attendance->execute(['id'=>$attendanceId,'teacher'=>$actor['portal_teacher_public_id']]);$a=$attendance->fetch();if(!$a)throw new InvalidArgumentException('Absensi final yang belum memiliki jurnal tidak ditemukan.');
        $publicId=Ulid::generate();$number='JK-'.str_replace('-','',$a['attendance_date']).'-'.substr($publicId,-6);$pdo->beginTransaction();try{$insert=$pdo->prepare("INSERT INTO journals(public_id,journal_number,attendance_session_id,journal_date,class_public_id,class_name_snapshot,teacher_public_id,teacher_name_snapshot,subject_id,subject_name_snapshot,period_start,period_end,activity_type,topic,teacher_note,status,created_by,updated_by) VALUES(:public_id,:number,:attendance_id,:date,:class_id,:class_name,:teacher_id,:teacher_name,:subject_id,:subject_name,:start,:end,:activity,:topic,:note,'DRAFT',:creator,:updater)");$insert->execute(['public_id'=>$publicId,'number'=>$number,'attendance_id'=>$a['id'],'date'=>$a['attendance_date'],'class_id'=>$a['class_public_id'],'class_name'=>$a['class_name_snapshot'],'teacher_id'=>$a['teacher_public_id'],'teacher_name'=>$a['teacher_name_snapshot'],'subject_id'=>$a['subject_id'],'subject_name'=>$a['subject_name_snapshot'],'start'=>$a['period_start'],'end'=>$a['period_end'],'activity'=>$activity,'topic'=>$topic,'note'=>$note,'creator'=>$actor['id'],'updater'=>$actor['id']]);$journalId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE attendance_sessions SET journal_id=:journal WHERE id=:attendance')->execute(['journal'=>$journalId,'attendance'=>$a['id']]);$this->audit($pdo,$actor,'JOURNAL_CREATED',$publicId,['attendancePublicId'=>$attendanceId]);$pdo->commit();}catch(Throwable $error){$pdo->rollBack();throw $error;}return $this->detail($publicId,$actor);
    }

    public function update(string $publicId,array $input,array $actor):array
    {
        $journal=$this->owned($publicId,$actor,true);$activity=(string)($input['activityType']??$journal['activity_type']);$topic=trim((string)($input['topic']??$journal['topic']));if(!in_array($activity,self::ACTIVITIES,true)||mb_strlen($topic)<5||mb_strlen($topic)>2000)throw new InvalidArgumentException('Data jurnal tidak valid.');$before=['activityType'=>$journal['activity_type'],'topic'=>$journal['topic'],'teacherNote'=>$journal['teacher_note']];$this->database->pdo()->prepare('UPDATE journals SET activity_type=:activity,topic=:topic,teacher_note=:note,updated_by=:user WHERE id=:id')->execute(['activity'=>$activity,'topic'=>$topic,'note'=>$this->nullable($input['teacherNote']??$journal['teacher_note'],2000),'user'=>$actor['id'],'id'=>$journal['id']]);$this->audit($this->database->pdo(),$actor,'JOURNAL_UPDATED',$publicId,['before'=>$before]);return $this->detail($publicId,$actor);
    }

    public function upload(string $publicId,array $file,array $actor):array
    {
        $journal=$this->owned($publicId,$actor,true);if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new InvalidArgumentException('File dokumentasi gagal diterima.');$size=(int)($file['size']??0);if($size<1||$size>(int)$this->config->get('security.max_upload_bytes'))throw new InvalidArgumentException('Ukuran file maksimal 20 MB.');$tmp=(string)$file['tmp_name'];$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($tmp);if(!in_array($mime,$this->config->get('security.allowed_image_mimes'),true))throw new InvalidArgumentException('Dokumentasi harus berupa JPG, PNG, atau WebP yang valid.');$count=$this->database->pdo()->prepare('SELECT COUNT(*) FROM journal_documentations WHERE journal_id=:id AND deleted_at IS NULL');$count->execute(['id'=>$journal['id']]);if((int)$count->fetchColumn()>=(int)$this->config->get('security.max_journal_files'))throw new InvalidArgumentException('Maksimal lima dokumentasi per jurnal.');
        $extension=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime];$generated=bin2hex(random_bytes(20)).'.'.$extension;$directory=rtrim($this->config->get('files.private_path'),'/\\').DIRECTORY_SEPARATOR.'journals'.DIRECTORY_SEPARATOR.$publicId;if(!is_dir($directory)&&!mkdir($directory,0750,true)&&!is_dir($directory))throw new RuntimeException('Penyimpanan dokumentasi tidak tersedia.');$target=$directory.DIRECTORY_SEPARATOR.$generated;if(!move_uploaded_file($tmp,$target))throw new RuntimeException('Dokumentasi gagal disimpan.');
        try{$filePublicId=Ulid::generate();$this->database->pdo()->prepare("INSERT INTO journal_documentations(public_id,journal_id,storage_disk,storage_path,original_name,generated_name,mime_type,file_size,checksum,uploaded_by) VALUES(:public_id,:journal,'private',:path,:original,:generated,:mime,:size,:checksum,:user)")->execute(['public_id'=>$filePublicId,'journal'=>$journal['id'],'path'=>'journals/'.$publicId.'/'.$generated,'original'=>substr(basename((string)$file['name']),0,255),'generated'=>$generated,'mime'=>$mime,'size'=>$size,'checksum'=>hash_file('sha256',$target),'user'=>$actor['id']]);$this->audit($this->database->pdo(),$actor,'JOURNAL_DOCUMENTATION_UPLOADED',$publicId,['filePublicId'=>$filePublicId,'mime'=>$mime,'size'=>$size]);}catch(Throwable $error){@unlink($target);throw $error;}return $this->detail($publicId,$actor);
    }

    public function finalize(string $publicId,array $actor):array
    {
        $journal=$this->owned($publicId,$actor,true);$count=$this->database->pdo()->prepare('SELECT COUNT(*) FROM journal_documentations WHERE journal_id=:id AND deleted_at IS NULL');$count->execute(['id'=>$journal['id']]);if((int)$count->fetchColumn()<1)throw new InvalidArgumentException('Minimal satu dokumentasi diperlukan sebelum finalisasi.');$pdo=$this->database->pdo();$pdo->beginTransaction();try{$pdo->prepare("UPDATE journals SET status='FINAL',finalized_at=NOW(3),updated_by=:user WHERE id=:id AND status='DRAFT'")->execute(['user'=>$actor['id'],'id'=>$journal['id']]);$this->audit($pdo,$actor,'JOURNAL_FINALIZED',$publicId,[]);$pdo->commit();}catch(Throwable $error){$pdo->rollBack();throw $error;}return $this->detail($publicId,$actor);
    }

    public function revise(string $publicId,array $input,array $actor):array
    {
        $journal=$this->owned($publicId,$actor,false);if(!in_array($journal['status'],['FINAL','AMENDED'],true))throw new InvalidArgumentException('Hanya jurnal final yang dapat direvisi.');$reason=trim((string)($input['reason']??''));if(mb_strlen($reason)<5||mb_strlen($reason)>1000)throw new InvalidArgumentException('Alasan revisi harus 5–1000 karakter.');$activity=(string)($input['activityType']??$journal['activity_type']);$topic=trim((string)($input['topic']??$journal['topic']));if(!in_array($activity,self::ACTIVITIES,true)||mb_strlen($topic)<5||mb_strlen($topic)>2000)throw new InvalidArgumentException('Isi revisi tidak valid.');$note=$this->nullable($input['teacherNote']??$journal['teacher_note'],2000);$before=['activityType'=>$journal['activity_type'],'topic'=>$journal['topic'],'teacherNote'=>$journal['teacher_note'],'status'=>$journal['status']];$after=['activityType'=>$activity,'topic'=>$topic,'teacherNote'=>$note,'status'=>'AMENDED'];$pdo=$this->database->pdo();$pdo->beginTransaction();try{$number=$pdo->prepare('SELECT COALESCE(MAX(revision_number),0)+1 FROM journal_revisions WHERE journal_id=:id FOR UPDATE');$number->execute(['id'=>$journal['id']]);$revision=(int)$number->fetchColumn();$pdo->prepare('INSERT INTO journal_revisions(public_id,journal_id,revision_number,reason,before_data_json,after_data_json,revised_by) VALUES(:public_id,:journal,:number,:reason,:before,:after,:user)')->execute(['public_id'=>Ulid::generate(),'journal'=>$journal['id'],'number'=>$revision,'reason'=>$reason,'before'=>json_encode($before,JSON_THROW_ON_ERROR),'after'=>json_encode($after,JSON_THROW_ON_ERROR),'user'=>$actor['id']]);$pdo->prepare("UPDATE journals SET activity_type=:activity,topic=:topic,teacher_note=:note,status='AMENDED',updated_by=:user WHERE id=:id")->execute(['activity'=>$activity,'topic'=>$topic,'note'=>$note,'user'=>$actor['id'],'id'=>$journal['id']]);$this->audit($pdo,$actor,'JOURNAL_REVISED',$publicId,['revisionNumber'=>$revision,'reason'=>$reason]);$pdo->commit();}catch(Throwable $error){$pdo->rollBack();throw $error;}return $this->detail($publicId,$actor);
    }

    public function deleteDraft(string $publicId,array $actor):void
    {
        $journal=$this->owned($publicId,$actor,true);$pdo=$this->database->pdo();$pdo->beginTransaction();try{$pdo->prepare('UPDATE attendance_sessions SET journal_id=NULL WHERE journal_id=:id')->execute(['id'=>$journal['id']]);$pdo->prepare('UPDATE journal_documentations SET deleted_at=NOW(3) WHERE journal_id=:id AND deleted_at IS NULL')->execute(['id'=>$journal['id']]);$pdo->prepare('UPDATE journals SET deleted_at=NOW(3),updated_by=:user WHERE id=:id')->execute(['user'=>$actor['id'],'id'=>$journal['id']]);$this->audit($pdo,$actor,'JOURNAL_DRAFT_DELETED',$publicId,[]);$pdo->commit();}catch(Throwable $error){$pdo->rollBack();throw $error;}
    }

    public function deleteDocumentation(string $journalPublicId,string $filePublicId,array $actor):array
    {
        $journal=$this->owned($journalPublicId,$actor,true);$query=$this->database->pdo()->prepare('SELECT id,storage_path FROM journal_documentations WHERE public_id=:file AND journal_id=:journal AND deleted_at IS NULL LIMIT 1');$query->execute(['file'=>$filePublicId,'journal'=>$journal['id']]);$file=$query->fetch();if(!$file)throw new RuntimeException('Dokumentasi tidak ditemukan.');$this->database->pdo()->prepare('UPDATE journal_documentations SET deleted_at=NOW(3) WHERE id=:id')->execute(['id'=>$file['id']]);$this->audit($this->database->pdo(),$actor,'JOURNAL_DOCUMENTATION_DELETED',$journalPublicId,['filePublicId'=>$filePublicId]);$root=realpath($this->config->get('files.private_path'));$path=$root?realpath($root.DIRECTORY_SEPARATOR.$file['storage_path']):false;if($root&&$path&&str_starts_with($path,$root.DIRECTORY_SEPARATOR))@unlink($path);return $this->detail($journalPublicId,$actor);
    }

    public function detail(string $publicId,array $actor):array
    {
        $journal=$this->owned($publicId,$actor,false);$pdo=$this->database->pdo();$documents=$pdo->prepare('SELECT public_id AS publicId,original_name AS originalName,mime_type AS mimeType,file_size AS fileSize,created_at AS createdAt FROM journal_documentations WHERE journal_id=:id AND deleted_at IS NULL ORDER BY created_at');$documents->execute(['id'=>$journal['id']]);$attendance=$pdo->prepare("SELECT student_public_id AS studentPublicId,attendance_number_snapshot AS attendanceNumber,student_name_snapshot AS studentName,nisn_snapshot AS nisn,status,note FROM attendance_records WHERE attendance_session_id=:id ORDER BY attendance_number_snapshot,student_name_snapshot");$attendance->execute(['id'=>$journal['attendance_session_id']]);$revisions=$pdo->prepare('SELECT public_id AS publicId,revision_number AS revisionNumber,reason,before_data_json AS beforeData,after_data_json AS afterData,created_at AS createdAt FROM journal_revisions WHERE journal_id=:id ORDER BY revision_number DESC');$revisions->execute(['id'=>$journal['id']]);$history=array_map(function(array $row){$row['beforeData']=json_decode($row['beforeData'],true);$row['afterData']=json_decode($row['afterData'],true);return $row;},$revisions->fetchAll());unset($journal['id'],$journal['attendance_session_id']);return ['journal'=>$journal,'documentations'=>$documents->fetchAll(),'attendance'=>$attendance->fetchAll(),'revisions'=>$history];
    }

    public function file(string $journalPublicId,string $filePublicId,array $actor):array
    {
        $journal=$this->owned($journalPublicId,$actor,false);$query=$this->database->pdo()->prepare('SELECT storage_path,original_name,mime_type FROM journal_documentations WHERE public_id=:file AND journal_id=:journal AND deleted_at IS NULL LIMIT 1');$query->execute(['file'=>$filePublicId,'journal'=>$journal['id']]);$file=$query->fetch();if(!$file)throw new RuntimeException('Dokumentasi tidak ditemukan.');$root=realpath($this->config->get('files.private_path'));$path=realpath($root.DIRECTORY_SEPARATOR.$file['storage_path']);if(!$root||!$path||!str_starts_with($path,$root.DIRECTORY_SEPARATOR))throw new RuntimeException('Dokumentasi tidak tersedia.');return ['content'=>(string)file_get_contents($path),'mime'=>$file['mime_type'],'name'=>$file['original_name']];
    }
    private function owned(string $publicId,array $actor,bool $draft):array{$sql='SELECT * FROM journals WHERE public_id=:id AND teacher_public_id=:teacher AND deleted_at IS NULL'.($draft?" AND status='DRAFT'":'').' LIMIT 1';$q=$this->database->pdo()->prepare($sql);$q->execute(['id'=>$publicId,'teacher'=>$actor['portal_teacher_public_id']]);$row=$q->fetch();if(!$row)throw new RuntimeException('Jurnal tidak ditemukan atau tidak dapat diubah.');return $row;}
    private function nullable(mixed $value,int $max):?string{$value=trim((string)$value);if(mb_strlen($value)>$max)throw new InvalidArgumentException('Teks melebihi batas karakter.');return $value===''?null:$value;}
    private function audit(PDO $pdo,array $actor,string $action,string $entityPublicId,array $metadata):void{$pdo->prepare("INSERT INTO audit_logs(public_id,actor_public_id,actor_name_snapshot,actor_role,action,entity_type,entity_public_id,metadata_json,created_at) VALUES(:public_id,:actor_id,:name,:role,:action,'Journal',:entity,:metadata,NOW(3))")->execute(['public_id'=>Ulid::generate(),'actor_id'=>$actor['public_id'],'name'=>$actor['name'],'role'=>$actor['role'],'action'=>$action,'entity'=>$entityPublicId,'metadata'=>json_encode($metadata,JSON_THROW_ON_ERROR)]);}
}
