CREATE TABLE IF NOT EXISTS employees (
 public_id VARCHAR(100) PRIMARY KEY, name VARCHAR(200) NOT NULL, nip VARCHAR(100), active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS accounts (
 id INTEGER PRIMARY KEY AUTO_INCREMENT, username VARCHAR(100) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, name VARCHAR(200) NOT NULL,
 employee_id VARCHAR(100) UNIQUE, active INTEGER NOT NULL DEFAULT 1,
 superadmin_slot INTEGER NULL UNIQUE CHECK (superadmin_slot = 1),
 FOREIGN KEY (employee_id) REFERENCES employees(public_id)
);
CREATE TABLE IF NOT EXISTS roles (
 id INTEGER PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL UNIQUE, permissions TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS grants (
 account_id INTEGER NOT NULL, role_id INTEGER NOT NULL,
 PRIMARY KEY(account_id), FOREIGN KEY(account_id) REFERENCES accounts(id), FOREIGN KEY(role_id) REFERENCES roles(id)
);
CREATE TABLE IF NOT EXISTS login_attempts (
 attempt_key VARCHAR(64) PRIMARY KEY, failures INTEGER NOT NULL, blocked_until INTEGER NOT NULL
);
