<?php
declare(strict_types=1);
// Explicit, isolated database only. Never loads production .env or credentials.
if (PHP_SAPI !== 'cli' || getenv('CBT_TEST_ISOLATED') !== '1') exit("Set CBT_TEST_ISOLATED=1 for an isolated MySQL on port 13317.\n");
spl_autoload_register(function ($class) { if (str_starts_with($class, 'Cbt\\')) require dirname(__DIR__).'/app/'.str_replace('\\','/',substr($class,4)).'.php'; });
use Cbt\Core\{Database,Request};
use Cbt\Repositories\{AttemptRepository,ExamRepository,StudentRepository};
use Cbt\Services\{AnswerService,ScoringService,ExamSessionService};
use Cbt\Middleware\RateLimitMiddleware;
use Cbt\Exceptions\DomainException;
$name='cbt_integrity_'.bin2hex(random_bytes(5));
$connection=new PDO('mysql:host=127.0.0.1;port=13317;charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$connection->exec('CREATE DATABASE `'.$name.'`');
$_ENV=array_merge($_ENV,['DB_HOST'=>'127.0.0.1','DB_PORT'=>'13317','DB_DATABASE'=>$name,'DB_USERNAME'=>'root','DB_PASSWORD'=>'']);
$db=new Database();$pdo=$db->pdo();$passed=0;
$assert=static function(bool $ok,string $label)use(&$passed){if(!$ok)throw new RuntimeException($label);echo 'PASS '.$label.PHP_EOL;$passed++;};
$reject=static function(callable $action,int $status,string $label)use($assert){try{$action();}catch(DomainException $error){$assert($error->status===$status,$label);return;}throw new RuntimeException('Expected rejection: '.$label);};
try {
 $pdo->exec((string)file_get_contents(dirname(__DIR__).'/database/schema.sql'));
 $pdo->exec((string)file_get_contents(dirname(__DIR__).'/database/migrations/20260907_answer_write_versions.sql'));
 $pdo->exec("INSERT INTO users(username,password_hash,name,role) VALUES('test-admin','unused','Test','ADMIN')");
 $pdo->exec("INSERT INTO students(portal_student_id,nisn,name_snapshot,grade_snapshot) VALUES('test-student','0000000001','Test Student','X')");
 $pdo->exec("INSERT INTO exams(public_id,name,grade,duration_minutes,starts_at,ends_at,academic_year,semester,status,created_by) VALUES('test-exam','Test Exam','X',60,UTC_TIMESTAMP()-INTERVAL 1 MINUTE,UTC_TIMESTAMP()+INTERVAL 1 HOUR,'2026','ODD','ACTIVE',1)");
 $pdo->exec("INSERT INTO questions(public_id,exam_id,question_text,option_a,option_b,option_c,option_d,correct_answer) VALUES('test-question',1,'Question','A','B','C','D','B')");
 $attempts=new AttemptRepository($pdo);$exams=new ExamRepository($pdo);$students=new StudentRepository($pdo);
 $sessions=new ExamSessionService($db,$students,$exams,$attempts);
 $session=$sessions->start(1,'0000000001',1);$attempt=$session['attempt_id'];
 $sessions->heartbeat(1,1);
 $monitor=new \Cbt\Repositories\AdminRepository($pdo);
 $live=$monitor->liveSessions([1]);
 $assert(count($live)===1 && $live[0]['connectionState']==='ONLINE','heartbeat is visible in live monitoring');
 $assert($monitor->liveSessions([])===[],'unassigned teacher receives no sessions');
 $assert(!str_contains(json_encode($live),'correct_answer'),'live monitoring does not expose answer keys');
 $answers=new AnswerService($db,$attempts);$scoring=new ScoringService($db,$attempts);
 $one=$answers->save(1,1,1,'A',false,$attempt,0,str_repeat('a',32));
 $assert($one['revision']===1,'first answer saved at revision one');
 $two=$answers->save(1,1,1,'B',true,$attempt,1,str_repeat('b',32));
 $assert($two['revision']===2,'latest answer and flag saved');
 $duplicate=$answers->save(1,1,1,'B',true,$attempt,1,str_repeat('b',32));
 $assert($duplicate['duplicate']&&$duplicate['revision']===2,'lost response retry is idempotent');
 $reject(fn()=>$answers->save(1,1,1,'A',false,$attempt,0,str_repeat('c',32)),409,'stale write rejected');
 $reject(fn()=>$answers->save(1,1,1,'E',false,$attempt,2,str_repeat('c',32)),422,'missing option rejected');
 $reject(fn()=>$answers->save(1,1,1,'A',false,'other-attempt',2,str_repeat('c',32)),409,'different attempt rejected');
 $reject(fn()=>$answers->save(1,1,2,'A',false,$attempt,2,str_repeat('c',32)),404,'question outside snapshot order rejected');
 $pdo->exec("UPDATE questions SET question_text='Changed question',correct_answer='A',points=99 WHERE id=1");
 $pdo->exec((string)file_get_contents(dirname(__DIR__).'/database/migrations/20260907_attempt_questions.sql'));
 $resumed=$sessions->start(1,'0000000001',1);
 $assert($resumed['soal'][0]['pertanyaan']==='Question'&&(float)$resumed['soal'][0]['poin']===1.0,'resume retains original question content and points');
 $pdo->exec("UPDATE exam_attempts SET expires_at=UTC_TIMESTAMP()-INTERVAL 1 SECOND");
 $reject(fn()=>$answers->save(1,1,1,'A',false,$attempt,2,str_repeat('d',32)),409,'late answer rejected');
 $assert($answers->save(1,1,1,'B',true,$attempt,1,str_repeat('b',32))['duplicate'],'previously saved write acknowledged after deadline');
 $summary=$scoring->finalizeDue();$assert($summary['completed']===1&&$summary['failed']===0,'server finalizes expired attempt without browser');
 $result=$scoring->submit(1,1);$assert((float)$result['nilai']===100.0,'score uses latest accepted answer');
 $scoring->submit(1,1);$assert((int)$pdo->query('SELECT COUNT(*) FROM exam_results')->fetchColumn()===1,'repeated submit produces exactly one result');
 $assert($scoring->recover(1,1)['completed']===true,'refresh recovers committed result');
 $reject(fn()=>$scoring->review(1,1),403,'review remains closed until publication');
 $pdo->exec("UPDATE exams SET ends_at=UTC_TIMESTAMP()-INTERVAL 1 SECOND");
 $assert(count($sessions->list(1,'0000000001'))===1,'result remains available after schedule closes');
 $pdo->exec("INSERT INTO cbt_settings(key_name,value) VALUES('review_published_1','1')");
 $review=$scoring->review(1,1);
 $assert($review['soal'][0]['jawaban_benar']==='B'&&count($review['soal'][0]['opsi'])===4,'published review uses original key and returns options');
 $pdo->exec('DELETE FROM attempt_questions WHERE attempt_id=1');
 $legacyReview=$scoring->review(1,1);
 $assert(count($legacyReview['soal'])===1&&$legacyReview['soal'][0]['jawaban_benar']==='A','legacy review repairs a missing question snapshot from the current bank');
 $unsafe='<b onclick="bad()">Safe</b><script>bad()</script><img src="javascript:bad()" onerror="bad()"><img src="assets/question.png" onerror="bad()">';
 $safe=\Cbt\Support\QuestionHtml::clean($unsafe);
 $assert(str_contains($safe,'<b>Safe</b>')&&!str_contains($safe,'bad()')&&str_contains($safe,'assets/question.png'),'question sanitizer strips executable markup and retains local images');
 $rate=new RateLimitMiddleware($pdo,'student-login');
 $r1=new Request('POST','/',[],['nisn'=>'0000000001'],['REMOTE_ADDR'=>'10.0.0.1']);
 $r2=new Request('POST','/',[],['nisn'=>'0000000002'],['REMOTE_ADDR'=>'10.0.0.1']);
 $assert($rate->bucketKey($r1)!==$rate->bucketKey($r2),'students sharing an IP have independent login limits');
 $limited=new RateLimitMiddleware($pdo,'student-login',8,300);$accepted=0;
 for($i=0;$i<9;$i++)$limited($r1,function()use(&$accepted){$accepted++;return \Cbt\Core\Response::json(null);});
 $assert($accepted===8,'login bucket blocks the ninth request for the same account');
 $limited($r2,function()use(&$accepted){$accepted++;return \Cbt\Core\Response::json(null);});
 $assert($accepted===9,'another student on the same IP can still log in');
 $reject(fn()=>(new \Cbt\Services\AdminStudentService($db,new \Cbt\Repositories\AdminStudentRepository($pdo),new \Cbt\Support\SecretCipher()))->reset(1),409,'legacy global reset is rejected without changing results');
 $pdo->exec("UPDATE students SET cbt_status='BLOCKED' WHERE id=1");$_SESSION['student']=['student_id'=>1];$allowed=false;
 (new \Cbt\Middleware\AuthMiddleware('student',null,$pdo))($r1,function()use(&$allowed){$allowed=true;return \Cbt\Core\Response::json(null);});
 $assert(!$allowed&&!isset($_SESSION['student']),'revoked student session is rejected on protected requests');
 echo "{$passed} integration checks passed.\n";
} finally { $connection->exec('DROP DATABASE `'.$name.'`'); }
