<?php

use App\Http\Controllers\AcademicYearController;
use App\Http\Controllers\AdminProfileController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\Auth\AdminSessionController;
use App\Http\Controllers\Auth\TeacherSessionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EnrollmentController;
use App\Http\Controllers\ImportManagementController;
use App\Http\Controllers\OidcController;
use App\Http\Controllers\SchoolClassController;
use App\Http\Controllers\SemesterController;
use App\Http\Controllers\SpreadsheetController;
use App\Http\Controllers\SsoApplicationController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentImportController;
use App\Http\Controllers\TeacherAccountController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TeacherPasswordSetupController;
use App\Http\Controllers\TeacherPhotoController;
use App\Http\Controllers\TeacherSelfController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('portal');
});
Route::get('teacher/{path?}', fn () => view('teacher'))->where('path', '.*');

Route::get('.well-known/openid-configuration', [OidcController::class, 'discovery']);
Route::get('oidc/.well-known/openid-configuration', [OidcController::class, 'discovery']);
Route::get('oidc/jwks', [OidcController::class, 'jwks']);
Route::get('oidc/authorize', [OidcController::class, 'authorize']);
Route::post('oidc/token', [OidcController::class, 'token'])->middleware('throttle:60,1');
Route::match(['GET', 'POST'], 'oidc/userinfo', [OidcController::class, 'userinfo'])->middleware('throttle:120,1');
Route::match(['GET', 'POST'], 'oidc/logout', [OidcController::class, 'logout']);

Route::prefix('api/v1')->group(function (): void {
    Route::post('auth/admin/login', [AdminSessionController::class, 'store'])->middleware('throttle:5,1');
    Route::middleware(['auth:admin', 'portal.session:admin'])->group(function (): void {
        Route::get('auth/admin/me', [AdminSessionController::class, 'show']);
        Route::post('auth/admin/logout', [AdminSessionController::class, 'destroy']);
        Route::get('profile', [AdminProfileController::class, 'show']);
        Route::patch('profile', [AdminProfileController::class, 'update']);
        Route::post('profile/change-password', [AdminProfileController::class, 'changePassword'])->middleware('throttle:5,1');
        Route::get('profile/sessions', [AdminProfileController::class, 'sessions']);
        Route::delete('profile/sessions/{publicId}', [AdminProfileController::class, 'revokeSession']);
        Route::post('profile/logout-all', [AdminProfileController::class, 'logoutAll']);
        Route::get('dashboard/summary', [DashboardController::class, 'summary']);
        Route::get('dashboard/recent-activities', [DashboardController::class, 'recentActivities']);
        Route::get('dashboard/data-quality', [DashboardController::class, 'dataQuality']);
        Route::get('imports', [ImportManagementController::class, 'index']);
        Route::get('imports/{importBatch}/rows', [ImportManagementController::class, 'rows']);
        Route::get('imports/{importBatch}', [ImportManagementController::class, 'show']);
        Route::get('teachers', [TeacherController::class, 'index']);
        Route::get('teachers/{teacher}', [TeacherController::class, 'show']);
        Route::get('teachers/{teacher}/account', [TeacherAccountController::class, 'show']);
        Route::get('teachers/{teacher}/photo', [TeacherPhotoController::class, 'show']);
        Route::get('students/by-nisn/{nisn}', [StudentController::class, 'byNisn']);
        Route::get('students', [StudentController::class, 'index']);
        Route::get('students/{student}', [StudentController::class, 'show']);
        Route::get('academic-years', [AcademicYearController::class, 'index']);
        Route::get('academic-years/{academicYear}', [AcademicYearController::class, 'show']);
        Route::get('semesters', [SemesterController::class, 'index']);
        Route::get('semesters/{semester}', [SemesterController::class, 'show']);
        Route::get('classes', [SchoolClassController::class, 'index']);
        Route::get('classes/{schoolClass}/students', [SchoolClassController::class, 'students']);
        Route::get('classes/{schoolClass}/statistics', [SchoolClassController::class, 'statistics']);
        Route::get('classes/{schoolClass}', [SchoolClassController::class, 'show']);
        Route::get('students/{student}/enrollments', [EnrollmentController::class, 'history']);
        Route::middleware('role:SUPER_ADMIN,DATA_ADMIN,DATA_OPERATOR')->group(function (): void {
            Route::post('students', [StudentController::class, 'store']);
            Route::patch('students/{student}', [StudentController::class, 'update']);
            Route::post('teachers', [TeacherController::class, 'store']);
            Route::patch('teachers/{teacher}', [TeacherController::class, 'update']);
            Route::post('teachers/{teacher}/account', [TeacherAccountController::class, 'store']);
            Route::post('teachers/{teacher}/account/setup-token', [TeacherAccountController::class, 'regenerate']);
            Route::post('teachers/{teacher}/account/disable', [TeacherAccountController::class, 'disable']);
            Route::post('teachers/{teacher}/account/enable', [TeacherAccountController::class, 'enable']);
            Route::post('teachers/{teacher}/account/unlock', [TeacherAccountController::class, 'unlock']);
            Route::post('teachers/{teacher}/account/revoke-sessions', [TeacherAccountController::class, 'revokeSessions']);
            Route::post('teachers/{teacher}/photo', [TeacherPhotoController::class, 'store']);
            Route::delete('teachers/{teacher}/photo', [TeacherPhotoController::class, 'destroy']);
            Route::post('academic-years', [AcademicYearController::class, 'store']);
            Route::patch('academic-years/{academicYear}', [AcademicYearController::class, 'update']);
            Route::post('academic-years/{academicYear}/activate', [AcademicYearController::class, 'activate']);
            Route::post('semesters', [SemesterController::class, 'store']);
            Route::patch('semesters/{semester}', [SemesterController::class, 'update']);
            Route::post('semesters/{semester}/activate', [SemesterController::class, 'activate']);
            Route::post('imports/students/validate', [StudentImportController::class, 'validateFile']);
            Route::get('import-templates/students', [SpreadsheetController::class, 'studentTemplate']);
            Route::get('exports/students', [SpreadsheetController::class, 'students']);
            Route::get('exports/classes/{schoolClass}/students', [SpreadsheetController::class, 'classStudents']);
            Route::post('classes', [SchoolClassController::class, 'store']);
            Route::patch('classes/{schoolClass}', [SchoolClassController::class, 'update']);
            Route::post('classes/{schoolClass}/students', [EnrollmentController::class, 'store']);
            Route::delete('classes/{schoolClass}/students/{student}', [EnrollmentController::class, 'destroy']);
            Route::patch('enrollments/{classEnrollment}', [EnrollmentController::class, 'update']);
            Route::post('enrollments/{classEnrollment}/move', [EnrollmentController::class, 'move']);
        });
        Route::middleware('role:SUPER_ADMIN,DATA_ADMIN')->group(function (): void {
            Route::get('sso/applications', [SsoApplicationController::class, 'index']);
            Route::post('sso/applications', [SsoApplicationController::class, 'store']);
            Route::get('sso/applications/{applicationClient}', [SsoApplicationController::class, 'show']);
            Route::patch('sso/applications/{applicationClient}', [SsoApplicationController::class, 'update']);
            Route::post('sso/applications/{applicationClient}/access', [SsoApplicationController::class, 'grant']);
            Route::post('sso/applications/{applicationClient}/access/{teacherPublicId}/revoke', [SsoApplicationController::class, 'revoke']);
            Route::post('imports/students/{importBatch}/commit', [StudentImportController::class, 'commit']);
            Route::delete('students/{student}', [StudentController::class, 'destroy']);
            Route::post('students/{publicId}/restore', [StudentController::class, 'restore']);
            Route::delete('teachers/{teacher}', [TeacherController::class, 'destroy']);
            Route::post('teachers/{publicId}/restore', [TeacherController::class, 'restore']);
            Route::delete('classes/{schoolClass}', [SchoolClassController::class, 'destroy']);
            Route::post('classes/{publicId}/restore', [SchoolClassController::class, 'restore']);
        });
        Route::middleware('role:SUPER_ADMIN')->group(function (): void {
            Route::get('admin-users', [AdminUserController::class, 'index']);
            Route::post('admin-users', [AdminUserController::class, 'store']);
            Route::get('admin-users/{publicId}', [AdminUserController::class, 'show']);
            Route::patch('admin-users/{publicId}', [AdminUserController::class, 'update']);
            Route::delete('admin-users/{publicId}', [AdminUserController::class, 'destroy']);
            Route::post('admin-users/{publicId}/restore', [AdminUserController::class, 'restore']);
            Route::post('admin-users/{publicId}/activate', [AdminUserController::class, 'activate']);
            Route::post('admin-users/{publicId}/deactivate', [AdminUserController::class, 'deactivate']);
        });
    });
    Route::post('auth/teacher/login', [TeacherSessionController::class, 'store'])->middleware('throttle:5,1');
    Route::get('auth/teacher/password-setup/validate', [TeacherPasswordSetupController::class, 'show'])->middleware('throttle:20,1');
    Route::post('auth/teacher/password-setup', [TeacherPasswordSetupController::class, 'store'])->middleware('throttle:10,1');
    Route::middleware(['auth:teacher', 'portal.session:teacher'])->group(function (): void {
        Route::get('auth/teacher/me', [TeacherSessionController::class, 'show']);
        Route::post('auth/teacher/logout', [TeacherSessionController::class, 'destroy']);
        Route::get('teacher/profile', [TeacherSelfController::class, 'profile']);
        Route::patch('teacher/profile', [TeacherSelfController::class, 'updateProfile']);
        Route::post('teacher/profile/change-password', [TeacherSelfController::class, 'changePassword'])->middleware('throttle:5,1');
        Route::get('teacher/profile/photo', [TeacherSelfController::class, 'photo']);
        Route::post('teacher/profile/photo', [TeacherSelfController::class, 'storePhoto']);
        Route::get('teacher/sessions', [TeacherSelfController::class, 'sessions']);
        Route::delete('teacher/sessions/{publicId}', [TeacherSelfController::class, 'revokeSession']);
        Route::post('teacher/sessions/logout-all', [TeacherSelfController::class, 'logoutAll']);
    });
});
