<?php
declare(strict_types=1);
namespace Cbt\Controllers;
use Cbt\Core\{Config,Request,Response,Session};
use Firebase\JWT\JWT;
use Firebase\JWT\JWK;
use PDO;
final class TeacherSsoController
{
 public function __construct(private PDO$db){}
 public function start(Request$r):Response{$issuer=$this->required('PORTAL_DATA_OIDC_ISSUER');$client=$this->required('PORTAL_DATA_OIDC_CLIENT_ID');$redirect=$this->required('PORTAL_DATA_OIDC_REDIRECT_URI');$this->https($redirect);$v=$this->b64(random_bytes(32));$state=$this->b64(random_bytes(24));$nonce=$this->b64(random_bytes(24));$_SESSION['oidc_teacher']=['state'=>$state,'nonce'=>$nonce,'verifier'=>$v];header('Location: '.rtrim($issuer,'/').'/authorize?'.http_build_query(['client_id'=>$client,'response_type'=>'code','redirect_uri'=>$redirect,'scope'=>'openid profile email portal_role','state'=>$state,'nonce'=>$nonce,'code_challenge'=>$this->b64(hash('sha256',$v,true)),'code_challenge_method'=>'S256']));exit;}
 public function callback(Request$r):Response{$s=$_SESSION['oidc_teacher']??[];if(!isset($s['state'])||!hash_equals((string)$s['state'],(string)($r->query['state']??'')))return Response::error('State SSO tidak valid.',400);$body=$this->post(rtrim($this->required('PORTAL_DATA_OIDC_ISSUER'),'/').'/token',['grant_type'=>'authorization_code','client_id'=>$this->required('PORTAL_DATA_OIDC_CLIENT_ID'),'code'=>$r->query['code']??'','redirect_uri'=>$this->required('PORTAL_DATA_OIDC_REDIRECT_URI'),'code_verifier'=>$s['verifier']]);$claims=$this->verify((string)($body['id_token']??''),$s['nonce']);if(!$claims)return Response::error('ID token Portal Data tidak valid.',401);$info=$this->userinfo(rtrim($this->required('PORTAL_DATA_OIDC_ISSUER'),'/').'/userinfo',(string)($body['access_token']??''));$portal=(string)($info['portal_teacher_id']??$claims['portal_teacher_id']??'');$nip=(string)($info['preferred_username']??$claims['preferred_username']??'');$teacherQuery=$this->db->prepare("SELECT * FROM teachers WHERE status='ACTIVE' AND (portal_teacher_id=:portal OR (nip=:nip AND nip<>'')) LIMIT 1");$teacherQuery->execute(['portal'=>$portal,'nip'=>$nip]);$teacher=$teacherQuery->fetch();if(!$teacher)return Response::error('Guru belum tersinkron dari Portal Data.',403);$q=$this->db->prepare("SELECT * FROM users WHERE teacher_id=:teacher LIMIT 1");$q->execute(['teacher'=>$teacher['id']]);$u=$q->fetch();if(!$u){$username=$teacher['nip']?:('portal-'.$teacher['portal_teacher_id']);$insert=$this->db->prepare("INSERT INTO users(teacher_id,username,password_hash,name,role,status) VALUES(:teacher,:username,:hash,:name,'TEACHER','ACTIVE')");$insert->execute(['teacher'=>$teacher['id'],'username'=>$username,'hash'=>password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT),'name'=>$teacher['name_snapshot']]);$q->execute(['teacher'=>$teacher['id']]);$u=$q->fetch();}if(!$u||$u['role']!=='TEACHER'||$u['status']!=='ACTIVE')return Response::error('Akun CBT guru tidak aktif.',403);Session::regenerate();$_SESSION['auth']=['user_id'=>(int)$u['id'],'teacher_id'=>(int)$teacher['id'],'portal_teacher_id'=>$teacher['portal_teacher_id'],'nip'=>$teacher['nip'],'role'=>'TEACHER'];unset($_SESSION['oidc_teacher']);header('Location: /guru/dashboard');exit;}
 public function logout(Request$r):Response{Session::destroy();header('Location: /guru');exit;}
 private function verify(string$jwt,string$nonce):?array{if($jwt==='')return null;try{$issuer=rtrim($this->required('PORTAL_DATA_OIDC_ISSUER'),'/');$keys=$this->userinfo($issuer.'/jwks','');$p=JWT::decode($jwt,JWK::parseKeySet($keys));$c=(array)$p;if(($c['iss']??'')!==$issuer||($c['aud']??'')!==$this->required('PORTAL_DATA_OIDC_CLIENT_ID')||($c['nonce']??'')!==$nonce)return null;return$c;}catch(\Throwable){return null;}}
 private function post(string$u,array$d):array{$c=curl_init($u);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($d),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded'],CURLOPT_TIMEOUT=>10]);$b=curl_exec($c);$s=(int)curl_getinfo($c,CURLINFO_HTTP_CODE);curl_close($c);$j=is_string($b)?json_decode($b,true):null;return$s>=200&&$s<300&&is_array($j)?$j:[];}
 private function userinfo(string$u,string$t):array{$c=curl_init($u);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>[$t?'Authorization: Bearer '.$t:'Accept: application/json','Accept: application/json'],CURLOPT_TIMEOUT=>10]);$b=curl_exec($c);$s=(int)curl_getinfo($c,CURLINFO_HTTP_CODE);curl_close($c);$j=is_string($b)?json_decode($b,true):null;return$s>=200&&$s<300&&is_array($j)?$j:[];}
 private function required(string$k):string{$v=(string)Config::get($k,'');if($v==='')Response::error('Konfigurasi SSO guru belum lengkap.',503)->send();return rtrim($v,'/');}private function https(string$u):void{if(parse_url($u,PHP_URL_SCHEME)!=='https'&&!in_array(parse_url($u,PHP_URL_HOST),['localhost','127.0.0.1'],true))Response::error('Redirect SSO wajib HTTPS.',503)->send();}private function b64(string$v):string{return rtrim(strtr(base64_encode($v),'+/','-_'),'=');}
}
