import { randomBytes } from 'node:crypto';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { RowDataPacket } from 'mysql2/promise';
import { z } from 'zod';
import { requireRole } from '../lib/access.js';
import { requirePool } from '../lib/db.js';
import { audit } from '../services/audit.js';
import sanitizeHtml from 'sanitize-html';

const positive = z.coerce.number().int().positive();
const questionRow = z.object({ exam_id: positive, question_type: z.enum(['MULTIPLE_CHOICE','MULTIPLE_RESPONSE','SHORT_ANSWER']).default('MULTIPLE_CHOICE'), question_text: z.string().trim().min(1).max(20000), option_a: z.string().max(20000).nullable().optional(), option_b: z.string().max(20000).nullable().optional(), option_c: z.string().max(20000).nullable().optional(), option_d: z.string().max(20000).nullable().optional(), option_e: z.string().max(20000).nullable().optional(), correct_answer: z.string().trim().min(1).max(500), points: z.coerce.number().positive().max(1000).default(1) }).strict();
const cleanHtml=(value:string)=>sanitizeHtml(value,{allowedTags:[...sanitizeHtml.defaults.allowedTags,'img','table','thead','tbody','tr','td','th','u','s','sub','sup'],allowedAttributes:{...sanitizeHtml.defaults.allowedAttributes,img:['src','alt','width','height'],a:['href','name','target','rel'],'*':['class']},allowedSchemes:['http','https','mailto'],allowProtocolRelative:false});

async function resetOne(studentId: number, examId: number, actorId: number, reason: string) {
  if (!reason.trim()) throw Object.assign(new Error('Alasan reset wajib diisi'), { statusCode: 422 });
  const pool = requirePool(); const connection = await pool.getConnection();
  try {
    await connection.beginTransaction();
    const [attemptRows] = await connection.execute<RowDataPacket[]>('SELECT a.*,s.is_active,s.cbt_status FROM exam_attempts a JOIN students s ON s.id=a.student_id WHERE a.student_id=? AND a.exam_id=? FOR UPDATE', [studentId, examId]);
    const attempt = attemptRows[0];
    if (!attempt || attempt.status !== 'TERMINATED' || Number(attempt.violation_count) < 3) throw Object.assign(new Error('Reset hanya tersedia untuk attempt yang dihentikan setelah tiga pelanggaran'), { statusCode: 409 });
    if (!attempt.is_active || attempt.cbt_status !== 'ACTIVE') throw Object.assign(new Error('Akun siswa tidak aktif'), { statusCode: 409 });
    const [lastRows] = await connection.execute<RowDataPacket[]>('SELECT MAX(occurred_at) stopped_at FROM violations WHERE attempt_id=?', [attempt.id]);
    const stoppedAt = lastRows[0]?.stopped_at ? new Date(lastRows[0].stopped_at).getTime() : Date.now();
    const remaining = Math.max(0, new Date(attempt.expires_at).getTime() - stoppedAt);
    if (remaining <= 0) throw Object.assign(new Error('Sisa waktu ujian sudah habis'), { statusCode: 409 });
    const expiresAt = new Date(Date.now() + remaining).toISOString().slice(0, 19).replace('T', ' ');
    const before = { status: attempt.status, violation_count: Number(attempt.violation_count), expires_at: attempt.expires_at };
    await connection.execute('DELETE FROM exam_results WHERE attempt_id=?', [attempt.id]);
    await connection.execute("UPDATE exam_attempts SET status='IN_PROGRESS',violation_count=0,completed_at=NULL,expires_at=? WHERE id=?", [expiresAt, attempt.id]);
    await connection.execute("INSERT INTO audit_logs(actor_user_id,actor_role,action,entity_type,entity_id,before_data,after_data) VALUES(?,'ADMIN','CBT_ATTEMPT_RESUMED','ExamAttempt',?,?,?)", [actorId, attempt.public_id, JSON.stringify(before), JSON.stringify({ status: 'IN_PROGRESS', violation_count: 0, expires_at: expiresAt, reason: reason.trim().slice(0, 1000) })]);
    await connection.commit();
    return { attempt_id: attempt.public_id, expires_at: `${expiresAt}Z` };
  } catch (error) { try { await connection.rollback(); } catch { /* no transaction */ } throw error; }
  finally { connection.release(); }
}

export async function adminRoutes(app: FastifyInstance) {
  const admin = (request: FastifyRequest, mutate = false) => requireRole(request, ['ADMIN'], mutate);
  app.get('/api/admin/dashboard', async (request) => {
    admin(request); const pool = requirePool();
    const [[students]] = await pool.query<RowDataPacket[]>('SELECT COUNT(*) students, SUM(is_active=1 AND cbt_status=\'ACTIVE\') active_students FROM students');
    const [[exams]] = await pool.query<RowDataPacket[]>('SELECT COUNT(*) exams, SUM(status=\'ACTIVE\') active_exams FROM exams');
    const [[attempts]] = await pool.query<RowDataPacket[]>('SELECT COUNT(*) attempts, SUM(status=\'IN_PROGRESS\') in_progress,SUM(status=\'TERMINATED\') terminated FROM exam_attempts');
    const [[tickets]] = await pool.query<RowDataPacket[]>('SELECT SUM(status IN (\'OPEN\',\'IN_PROGRESS\')) open_tickets FROM support_tickets');
    return { students: Number(students?.students ?? 0), active_students: Number(students?.active_students ?? 0), exams: Number(exams?.exams ?? 0), active_exams: Number(exams?.active_exams ?? 0), attempts: Number(attempts?.attempts ?? 0), in_progress: Number(attempts?.in_progress ?? 0), terminated: Number(attempts?.terminated ?? 0), open_tickets: Number(tickets?.open_tickets ?? 0) };
  });
  app.get('/api/admin/students', async (request) => {
    admin(request); const query = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(50), q: z.string().max(100).optional(), grade: z.string().max(10).optional(), class_id: z.string().max(64).optional() }).parse(request.query);
    const pool = requirePool(); const where = ['s.is_active=1']; const params: (string|number)[] = [];
    if (query.q) { where.push('(s.nisn LIKE ? OR s.name_snapshot LIKE ?)'); params.push(`%${query.q}%`, `%${query.q}%`); }
    if (query.grade) { where.push('s.grade_snapshot=?'); params.push(query.grade); }
    if (query.class_id) { where.push('s.portal_class_id=?'); params.push(query.class_id); }
    const [rows] = await pool.query<RowDataPacket[]>(`SELECT s.id,s.nisn,s.name_snapshot,s.class_snapshot,s.grade_snapshot,s.cbt_status,COUNT(a.id) attempt_count,MAX(a.status) attempt_status FROM students s LEFT JOIN exam_attempts a ON a.student_id=s.id WHERE ${where.join(' AND ')} GROUP BY s.id ORDER BY s.class_snapshot,s.name_snapshot LIMIT ? OFFSET ?`, [...params, query.limit, (query.page - 1) * query.limit]);
    const [counts] = await pool.query<RowDataPacket[]>(`SELECT COUNT(*) total FROM students s WHERE ${where.join(' AND ')}`, params);
    return { items: rows, page: query.page, limit: query.limit, total: Number(counts[0]?.total ?? 0) };
  });
  app.get('/api/admin/users', async (request) => { admin(request); const [rows] = await requirePool().query<RowDataPacket[]>('SELECT u.id,u.username,u.name,u.role,u.status,t.nip teacher_nip,e.nip employee_nip FROM users u LEFT JOIN teachers t ON t.id=u.teacher_id LEFT JOIN employees e ON e.id=u.employee_id ORDER BY u.name LIMIT 500'); return rows; });
  app.post('/api/admin/users', async (request) => {
    const claims = admin(request, true); const body = z.object({ id: z.number().int().positive().optional(), username: z.string().trim().min(3).max(100), name: z.string().trim().min(2).max(191), password: z.string().min(12).max(200).optional(), role: z.enum(['ADMIN','TEACHER','EMPLOYEE']).default('ADMIN'), status: z.enum(['ACTIVE','DISABLED']).default('ACTIVE') }).strict().parse(request.body);
    if (!body.id && !body.password) throw Object.assign(new Error('Password minimal 12 karakter diperlukan untuk akun baru'), { statusCode: 422 });
    const pool = requirePool(); const { hash } = await import('bcryptjs');
    if (body.id) {
      const [existing] = await pool.execute<RowDataPacket[]>('SELECT id FROM users WHERE id=?', [body.id]); if (!existing[0]) throw Object.assign(new Error('Akun tidak ditemukan'), { statusCode: 404 });
      if (body.password) await pool.execute('UPDATE users SET username=?,name=?,role=?,status=?,password_hash=? WHERE id=?', [body.username, body.name, body.role, body.status, await hash(body.password, 12), body.id]);
      else await pool.execute('UPDATE users SET username=?,name=?,role=?,status=? WHERE id=?', [body.username, body.name, body.role, body.status, body.id]);
    } else await pool.execute('INSERT INTO users(username,password_hash,name,role,status) VALUES(?,?,?,?,?)', [body.username, await hash(body.password!, 12), body.name, body.role, body.status]);
    await audit(pool, claims.sub, claims.role, 'USER_SAVED', 'User', body.id ?? body.username); return { success: true };
  });
  app.get('/api/admin/results', async (request) => {
    admin(request); const query = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(200).default(50), exam_id: z.coerce.number().int().positive().optional() }).parse(request.query);
    const where = query.exam_id ? 'WHERE a.exam_id=?' : ''; const params = query.exam_id ? [query.exam_id] : [];
    const [rows] = await requirePool().execute<RowDataPacket[]>(`SELECT r.id,r.question_count,r.correct_count,r.wrong_count,r.blank_count,r.earned_points,r.maximum_points,r.score,r.created_at,a.public_id attempt_id,a.exam_id,e.name exam_name,s.nisn,s.name_snapshot,s.class_snapshot FROM exam_results r JOIN exam_attempts a ON a.id=r.attempt_id JOIN exams e ON e.id=a.exam_id JOIN students s ON s.id=a.student_id ${where} ORDER BY r.created_at DESC LIMIT ? OFFSET ?`, [...params, query.limit, (query.page - 1) * query.limit]);
    return { items: rows, page: query.page, limit: query.limit };
  });
  app.get('/api/admin/violations', async (request) => {
    admin(request); const query = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(200).default(100), exam_id: z.coerce.number().int().positive().optional() }).parse(request.query);
    const where = query.exam_id ? 'WHERE a.exam_id=?' : ''; const params = query.exam_id ? [query.exam_id] : [];
    const [rows] = await requirePool().execute<RowDataPacket[]>(`SELECT v.id,v.event_key,v.type,v.occurred_at,s.nisn,s.name_snapshot,s.class_snapshot,e.name exam_name,a.status attempt_status,a.violation_count FROM violations v JOIN exam_attempts a ON a.id=v.attempt_id JOIN students s ON s.id=a.student_id JOIN exams e ON e.id=a.exam_id ${where} ORDER BY v.occurred_at DESC LIMIT ? OFFSET ?`, [...params, query.limit, (query.page - 1) * query.limit]); return { items: rows, page: query.page, limit: query.limit };
  });
  app.get('/api/admin/portal-classes', async (request) => { admin(request); const [rows] = await requirePool().query<RowDataPacket[]>('SELECT portal_class_id,code,name,grade,academic_year FROM portal_classes WHERE status=\'ACTIVE\' ORDER BY grade,name LIMIT 1000'); return rows; });
  app.get('/api/admin/exams', async (request) => { admin(request); const [rows] = await requirePool().query<RowDataPacket[]>('SELECT e.id,e.public_id,e.name,e.grade,e.duration_minutes,e.session_number,e.starts_at,e.ends_at,e.academic_year,e.semester,e.subject_name,e.status,COUNT(DISTINCT q.id) question_count,COUNT(DISTINCT a.id) attempt_count FROM exams e LEFT JOIN questions q ON q.exam_id=e.id LEFT JOIN exam_attempts a ON a.exam_id=e.id GROUP BY e.id ORDER BY e.starts_at DESC LIMIT 500'); return rows; });
  app.get<{Params:{id:string}}>('/api/admin/exams/:id', async (request) => { admin(request); const id=positive.parse(request.params.id); const pool=requirePool(); const [rows]=await pool.execute<RowDataPacket[]>('SELECT id,public_id,name,grade,duration_minutes,session_number,starts_at,ends_at,academic_year,semester,subject_name,status FROM exams WHERE id=?',[id]); if(!rows[0])throw Object.assign(new Error('Ujian tidak ditemukan'),{statusCode:404});const [classes]=await pool.execute<RowDataPacket[]>('SELECT portal_class_id FROM exam_target_classes WHERE exam_id=? ORDER BY portal_class_id',[id]);const [students]=await pool.execute<RowDataPacket[]>('SELECT student_id FROM exam_target_students WHERE exam_id=? ORDER BY student_id',[id]);return{...rows[0],target_class_ids:classes.map((row)=>row.portal_class_id),target_student_ids:students.map((row)=>Number(row.student_id))}; });
  app.post('/api/admin/exams', async (request) => {
    const claims=admin(request,true);const body=z.object({id:positive.optional(),name:z.string().trim().min(3).max(191),grade:z.string().trim().min(1).max(10),duration_minutes:z.coerce.number().int().min(1).max(600),session_number:z.coerce.number().int().min(1).max(20).default(1),starts_at:z.string().datetime({offset:true}),ends_at:z.string().datetime({offset:true}),academic_year:z.string().trim().min(1).max(30),semester:z.enum(['ODD','EVEN']),subject_name:z.string().max(100).nullable().optional(),status:z.enum(['DRAFT','ACTIVE','INACTIVE','ARCHIVED']).default('DRAFT'),target_class_ids:z.array(z.string().min(1).max(64)).max(500).default([]),target_student_ids:z.array(positive).max(5000).default([])}).strict().parse(request.body);const start=new Date(body.starts_at),end=new Date(body.ends_at);if(end<=start)throw Object.assign(new Error('Waktu selesai harus setelah waktu mulai'),{statusCode:422});const pool=requirePool();const c=await pool.getConnection();let id=body.id;
    try{await c.beginTransaction();if(id){const[old]=await c.execute<RowDataPacket[]>('SELECT id FROM exams WHERE id=? FOR UPDATE',[id]);if(!old[0])throw Object.assign(new Error('Ujian tidak ditemukan'),{statusCode:404});const[active]=await c.execute<RowDataPacket[]>('SELECT id FROM exam_attempts WHERE exam_id=? AND status=\'IN_PROGRESS\' LIMIT 1',[id]);if(active[0])throw Object.assign(new Error('Ujian sedang berlangsung dan belum bisa diubah'),{statusCode:409});await c.execute('UPDATE exams SET name=?,grade=?,duration_minutes=?,session_number=?,starts_at=?,ends_at=?,academic_year=?,semester=?,subject_name=?,status=? WHERE id=?',[body.name,body.grade,body.duration_minutes,body.session_number,start.toISOString().slice(0,23).replace('T',' '),end.toISOString().slice(0,23).replace('T',' '),body.academic_year,body.semester,body.subject_name??null,body.status,id]);await c.execute('DELETE FROM exam_target_classes WHERE exam_id=?',[id]);await c.execute('DELETE FROM exam_target_students WHERE exam_id=?',[id]);}else{const publicId=ulid();const[result]=await c.execute('INSERT INTO exams(public_id,name,grade,duration_minutes,session_number,starts_at,ends_at,academic_year,semester,subject_name,status) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[publicId,body.name,body.grade,body.duration_minutes,body.session_number,start.toISOString().slice(0,23).replace('T',' '),end.toISOString().slice(0,23).replace('T',' '),body.academic_year,body.semester,body.subject_name??null,body.status]);id=(result as {insertId:number}).insertId;}const classIds=[...new Set(body.target_class_ids)];for(let i=0;i<classIds.length;i+=200){const batch=classIds.slice(i,i+200);await c.query(`INSERT INTO exam_target_classes(exam_id,portal_class_id) VALUES ${batch.map(()=>'(?,?)').join(',')}`,[...batch.flatMap((classId)=>[id,classId])]);}const studentIds=[...new Set(body.target_student_ids)];for(let i=0;i<studentIds.length;i+=200){const batch=studentIds.slice(i,i+200);await c.query(`INSERT INTO exam_target_students(exam_id,student_id) VALUES ${batch.map(()=>'(?,?)').join(',')}`,[...batch.flatMap((studentId)=>[id,studentId])]);}await c.commit();}catch(error){try{await c.rollback();}catch{}throw error;}finally{c.release();}await audit(pool,claims.sub,claims.role,'EXAM_SAVED','Exam',id);return{id};
  });
  app.get('/api/admin/live-sessions', async (request) => { admin(request); const [rows] = await requirePool().query<RowDataPacket[]>(`SELECT a.public_id,a.status,a.started_at,a.expires_at,a.violation_count,s.nisn,s.name_snapshot,s.class_snapshot,e.id exam_id,e.name exam_name,c.last_seen_at FROM exam_attempts a JOIN students s ON s.id=a.student_id JOIN exams e ON e.id=a.exam_id LEFT JOIN attempt_connections c ON c.attempt_id=a.id WHERE a.status='IN_PROGRESS' ORDER BY a.updated_at DESC LIMIT 500`); return rows; });
  app.get('/api/admin/exams/:id/report', async (request) => { admin(request); const id = positive.parse((request.params as {id: string}).id); const [rows] = await requirePool().execute<RowDataPacket[]>(`SELECT COUNT(*) participants, SUM(a.status='COMPLETED') completed, SUM(a.status='IN_PROGRESS') in_progress, AVG(r.score) average_score, MIN(r.score) min_score, MAX(r.score) max_score FROM exam_attempts a LEFT JOIN exam_results r ON r.attempt_id=a.id WHERE a.exam_id=?`, [id]); const [distribution] = await requirePool().execute<RowDataPacket[]>(`SELECT FLOOR(r.score/10)*10 score_band,COUNT(*) students FROM exam_results r JOIN exam_attempts a ON a.id=r.attempt_id WHERE a.exam_id=? GROUP BY score_band ORDER BY score_band`, [id]); return { summary: rows[0], distribution }; });
  app.get('/api/admin/questions', async (request) => { admin(request); const query = z.object({ exam_id: z.coerce.number().int().positive().optional(), page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(50) }).parse(request.query); const where = query.exam_id ? 'WHERE exam_id=?' : ''; const params = query.exam_id ? [query.exam_id] : []; const [rows] = await requirePool().execute<RowDataPacket[]>(`SELECT id,public_id,exam_id,question_type,question_text,option_a,option_b,option_c,option_d,option_e,points FROM questions ${where} ORDER BY id DESC LIMIT ? OFFSET ?`, [...params, query.limit, (query.page-1)*query.limit]); return { items: rows, page: query.page, limit: query.limit }; });
  app.post('/api/admin/questions/import', async (request) => {
    const claims = admin(request, true); const body = z.object({ rows: z.array(z.unknown()).min(1).max(200) }).strict().parse(request.body); const pool = requirePool(); let inserted=0; const errors: {row:number;error:string}[]=[];
    for (let i=0;i<body.rows.length;i++) { try { const row = questionRow.parse(normalizeQuestion(body.rows[i])); let key=row.correct_answer; if(row.question_type!=='SHORT_ANSWER'){const normalized=key.toUpperCase().split(',').map((x)=>x.trim()).filter(Boolean);if(!normalized.length||(row.question_type==='MULTIPLE_CHOICE'&&normalized.length!==1)||normalized.some((letter)=>!['A','B','C','D','E'].includes(letter)||!optionText(row,letter).trim()))throw new Error('Jawaban/kunci tidak valid');key=normalized.sort().join(',');} const [result] = await pool.execute('INSERT INTO questions(public_id,exam_id,question_type,question_text,option_a,option_b,option_c,option_d,option_e,correct_answer,points) VALUES(?,?,?,?,?,?,?,?,?,?,?)', [ulid(),row.exam_id,row.question_type,cleanHtml(row.question_text),row.option_a?cleanHtml(row.option_a):null,row.option_b?cleanHtml(row.option_b):null,row.option_c?cleanHtml(row.option_c):null,row.option_d?cleanHtml(row.option_d):null,row.option_e?cleanHtml(row.option_e):null,key,row.points]); inserted += (result as {affectedRows:number}).affectedRows; } catch (error) { errors.push({row:i+1,error:error instanceof z.ZodError?error.issues.map(x=>x.message).join(', '):error instanceof Error?error.message:'Data tidak valid'}); } }
    await audit(pool,claims.sub,claims.role,'QUESTIONS_IMPORTED','Question',inserted,{inserted,failed:errors.length}); return { inserted, failed:errors.length, errors };
  });
  app.post('/api/admin/questions',async(request)=>{const claims=admin(request,true);const row=questionRow.parse(normalizeQuestion(request.body));let key=row.correct_answer;if(row.question_type!=='SHORT_ANSWER'){const letters=key.toUpperCase().split(',').map(x=>x.trim()).filter(Boolean);if(!letters.length||(row.question_type==='MULTIPLE_CHOICE'&&letters.length!==1)||letters.some(x=>!['A','B','C','D','E'].includes(x)||!optionText(row,x).trim()))throw Object.assign(new Error('Jawaban benar tidak cocok dengan opsi yang tersedia'),{statusCode:422});key=letters.sort().join(',');}const [result]=await requirePool().execute('INSERT INTO questions(public_id,exam_id,question_type,question_text,option_a,option_b,option_c,option_d,option_e,correct_answer,points) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[ulid(),row.exam_id,row.question_type,cleanHtml(row.question_text),row.option_a?cleanHtml(row.option_a):null,row.option_b?cleanHtml(row.option_b):null,row.option_c?cleanHtml(row.option_c):null,row.option_d?cleanHtml(row.option_d):null,row.option_e?cleanHtml(row.option_e):null,key,row.points]);const id=(result as {insertId:number}).insertId;await audit(requirePool(),claims.sub,claims.role,'QUESTION_SAVED','Question',id);return{id};});
  app.delete<{Params:{id:string}}>('/api/admin/questions/:id',async(request)=>{const claims=admin(request,true);const id=positive.parse(request.params.id);const[res]=await requirePool().execute('DELETE FROM questions WHERE id=?',[id]);if(!(res as {affectedRows:number}).affectedRows)throw Object.assign(new Error('Soal tidak ditemukan'),{statusCode:404});await audit(requirePool(),claims.sub,claims.role,'QUESTION_DELETED','Question',id);return{success:true};});
  app.post<{Params:{id:string}}>('/api/admin/students/:id/reset',async(request)=>{const claims=admin(request,true);const id=positive.parse(request.params.id);const body=z.object({exam_id:positive,reason:z.string().trim().min(3).max(1000)}).strict().parse(request.body);return resetOne(id,body.exam_id,claims.sub,body.reason);});
  app.post('/api/admin/teacher-assignments',async(request)=>{const claims=admin(request,true);const body=z.object({teacher_id:positive.nullable().optional(),employee_id:positive.nullable().optional(),exam_id:positive.nullable().optional(),duty_role:z.enum(['TEACHER','PROCTOR']).default('TEACHER')}).strict().refine(v=>Boolean(v.teacher_id||v.employee_id)).parse(request.body);if(body.teacher_id&&body.employee_id)throw Object.assign(new Error('Pilih satu identitas personel'),{statusCode:422});const[res]=await requirePool().execute('INSERT INTO teacher_exam_assignments(teacher_id,employee_id,exam_id,duty_role,created_by) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE duty_role=VALUES(duty_role)',[body.teacher_id??null,body.employee_id??null,body.exam_id??null,body.duty_role,claims.sub]);await audit(requirePool(),claims.sub,claims.role,'TEACHER_ASSIGNMENT_SAVED','TeacherExamAssignment',(res as {insertId:number}).insertId);return{success:true};});
  app.get('/api/admin/teacher-assignments',async(request)=>{admin(request);const[rows]=await requirePool().query<RowDataPacket[]>('SELECT a.id,a.teacher_id,a.employee_id,a.exam_id,a.duty_role,t.name_snapshot teacher_name,e.name_snapshot employee_name,x.name exam_name FROM teacher_exam_assignments a LEFT JOIN teachers t ON t.id=a.teacher_id LEFT JOIN employees e ON e.id=a.employee_id LEFT JOIN exams x ON x.id=a.exam_id ORDER BY a.id DESC LIMIT 500');return rows;});
  app.delete<{Params:{id:string}}>('/api/admin/teacher-assignments/:id',async(request)=>{const claims=admin(request,true);const id=positive.parse(request.params.id);const[res]=await requirePool().execute('DELETE FROM teacher_exam_assignments WHERE id=?',[id]);if(!(res as {affectedRows:number}).affectedRows)throw Object.assign(new Error('Penugasan tidak ditemukan'),{statusCode:404});await audit(requirePool(),claims.sub,claims.role,'TEACHER_ASSIGNMENT_DELETED','TeacherExamAssignment',id);return{success:true};});
  app.post<{Params:{id:string}}>('/api/admin/teachers/:id/proctor-eligibility',async(request)=>{const claims=admin(request,true);const id=positive.parse(request.params.id);const{eligible}=z.object({eligible:z.boolean()}).strict().parse(request.body);const[res]=await requirePool().execute('UPDATE teachers SET proctor_eligible=? WHERE id=?',[Number(eligible),id]);if(!(res as {affectedRows:number}).affectedRows)throw Object.assign(new Error('Guru tidak ditemukan'),{statusCode:404});await audit(requirePool(),claims.sub,claims.role,'TEACHER_PROCTOR_ELIGIBILITY_UPDATED','Teacher',id,{eligible:!eligible},{eligible});return{success:true};});
  app.post('/api/admin/students/reset-batch', async (request) => {
    const claims = admin(request,true); const body = z.object({ student_ids:z.array(positive).min(1).max(50),exam_id:positive,reason:z.string().trim().min(3).max(1000) }).strict().parse(request.body); const results=[] as {student_id:number;ok:boolean;result?:unknown;error?:string}[];
    for (const studentId of [...new Set(body.student_ids)]) { try { results.push({student_id:studentId,ok:true,result:await resetOne(studentId,body.exam_id,claims.sub,body.reason)}); } catch (error) { results.push({student_id:studentId,ok:false,error:error instanceof Error?error.message:'Reset gagal'}); } }
    return { total:results.length,reset:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,results };
  });
}
function optionText(row:{option_a?:string|null;option_b?:string|null;option_c?:string|null;option_d?:string|null;option_e?:string|null},letter:string){return ({A:row.option_a,B:row.option_b,C:row.option_c,D:row.option_d,E:row.option_e} as Record<string,string|null|undefined>)[letter]??'';}
function normalizeQuestion(value:unknown){if(!value||typeof value!=='object')return value;const row=value as Record<string,unknown>;return {exam_id:row.exam_id??row.ujian_id,question_type:row.question_type??row.tipe_soal,question_text:row.question_text??row.pertanyaan,option_a:row.option_a??row.opsi_a,option_b:row.option_b??row.opsi_b,option_c:row.option_c??row.opsi_c,option_d:row.option_d??row.opsi_d,option_e:row.option_e??row.opsi_e,correct_answer:row.correct_answer??row.jawaban_benar,points:row.points??row.poin};}
function ulid(){const chars='0123456789ABCDEFGHJKMNPQRSTVWXYZ';let value=Date.now(),out='';for(let i=0;i<10;i++){out=chars[value%32]+out;value=Math.floor(value/32);}for(const byte of randomBytes(16))out+=chars[byte&31];return out;}
