import { randomBytes } from 'node:crypto';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { PoolConnection, RowDataPacket } from 'mysql2/promise';
import { z } from 'zod';
import { requireRole } from '../lib/access.js';
import { requirePool } from '../lib/db.js';
import { audit } from '../services/audit.js';

const types=['STUDENTS','TEACHERS','EMPLOYEES','CLASSES','ACADEMIC_YEARS','SEMESTERS'] as const;
const endpoints:Record<typeof types[number],string>={STUDENTS:'/api/v1/integration/cbt/students',TEACHERS:'/api/v1/integration/cbt/teachers',EMPLOYEES:'/api/v1/integration/cbt/employees',CLASSES:'/api/v1/integration/cbt/classes',ACADEMIC_YEARS:'/api/v1/integration/cbt/academic-years',SEMESTERS:'/api/v1/integration/cbt/semesters'};
let token:string|undefined;let tokenExpires=0;
async function getToken(){if(token&&Date.now()<tokenExpires-15000)return token;const base=process.env.PORTAL_DATA_BASE_URL?.replace(/\/$/,'');const id=process.env.PORTAL_DATA_SYNC_CLIENT_ID;const secret=process.env.PORTAL_DATA_SYNC_CLIENT_SECRET;if(!base||!id||!secret)throw Object.assign(new Error('Konfigurasi Portal Data belum lengkap'),{statusCode:503});const body=new URLSearchParams({grant_type:'client_credentials',client_id:id,client_secret:secret,scope:'portal_data.read'});const response=await fetch(`${base}/oidc/token`,{method:'POST',headers:{accept:'application/json','content-type':'application/x-www-form-urlencoded'},body,signal:AbortSignal.timeout(10000)});if(!response.ok)throw Object.assign(new Error(`Portal Data token HTTP ${response.status}`),{statusCode:502});const data=await response.json() as {access_token?:string;expires_in?:number};if(!data.access_token)throw Object.assign(new Error('Respons token Portal Data tidak valid'),{statusCode:502});token=data.access_token;tokenExpires=Date.now()+Number(data.expires_in??300)*1000;return token;}
async function fetchPage(type:typeof types[number],page:number,retried=false){const base=process.env.PORTAL_DATA_BASE_URL!.replace(/\/$/,'');const url=new URL(endpoints[type],base);url.searchParams.set('page',String(page));url.searchParams.set('per_page',type==='CLASSES'? '100':'200');const response=await fetch(url,{headers:{accept:'application/json',authorization:`Bearer ${await getToken()}`},signal:AbortSignal.timeout(15000)});if(response.status===401&&!retried){token=undefined;tokenExpires=0;return fetchPage(type,page,true);}if(!response.ok)throw Object.assign(new Error(`Portal Data ${type} HTTP ${response.status}`),{statusCode:502});const json=await response.json() as Record<string,any>;const container=json.data??{};const items=container.data??container;if(!Array.isArray(items))throw Object.assign(new Error(`Payload ${type} tidak valid`),{statusCode:502});const meta=json.meta??container.meta??container;const hasMore=Boolean(meta.has_more??(Number(meta.current_page??page)<Number(meta.last_page??page)));return {items:items as Record<string,any>[],hasMore};}
function grade(value:unknown):string|null{const v=String(value??'').toUpperCase().trim();return ({'7':'VII','8':'VIII','9':'IX','10':'X','11':'XI','12':'XII'} as Record<string,string>)[v]??(v||null);}
async function upsert(connection:PoolConnection,type:typeof types[number],row:Record<string,any>){const active=Boolean(row.is_active??(String(row.status??'ACTIVE').toUpperCase()==='ACTIVE'));const id=String(row.id??row[({STUDENTS:'student_id',TEACHERS:'teacher_id',EMPLOYEES:'employee_id',CLASSES:'class_id'} as Record<string,string>)[type]??'id']??'');const now='UTC_TIMESTAMP(3)';
 if(type==='STUDENTS'){const nisn=String(row.nisn??'').trim();const name=String(row.name??row.nama??'').trim();if(!id||!/^\d{8,20}$/.test(nisn)||!name)throw new Error('Data siswa invalid');const[collision]=await connection.execute<RowDataPacket[]>('SELECT portal_student_id FROM students WHERE nisn=? LIMIT 1',[nisn]);if(collision[0]&&collision[0].portal_student_id!==id)throw new Error('NISN sudah terdaftar untuk siswa Portal Data lain');const cls=row.class??{};await connection.execute(`INSERT INTO students(portal_student_id,portal_class_id,nisn,name_snapshot,class_snapshot,grade_snapshot,academic_year_snapshot,is_active,last_synced_at) VALUES(?,?,?,?,?,?,?,?,${now}) ON DUPLICATE KEY UPDATE portal_class_id=IF(portal_student_id=VALUES(portal_student_id),VALUES(portal_class_id),portal_class_id),nisn=IF(portal_student_id=VALUES(portal_student_id),VALUES(nisn),nisn),name_snapshot=IF(portal_student_id=VALUES(portal_student_id),VALUES(name_snapshot),name_snapshot),class_snapshot=IF(portal_student_id=VALUES(portal_student_id),VALUES(class_snapshot),class_snapshot),grade_snapshot=IF(portal_student_id=VALUES(portal_student_id),VALUES(grade_snapshot),grade_snapshot),academic_year_snapshot=IF(portal_student_id=VALUES(portal_student_id),VALUES(academic_year_snapshot),academic_year_snapshot),is_active=IF(portal_student_id=VALUES(portal_student_id),VALUES(is_active),is_active),last_synced_at=IF(portal_student_id=VALUES(portal_student_id),${now},last_synced_at)`,[id,String(cls.id??row.class_id??'')||null,nisn,name,String(cls.name??row.kelas??row.rombel??'')||null,grade(row.grade??row.tingkat),String(row.academic_year??row.tahun_ajaran??'')||null,Number(active)]);return;}
 if(type==='TEACHERS'){const name=String(row.name??row.nama??'').trim();if(!id||!name)throw new Error('Data guru invalid');if(row.nip){const[collision]=await connection.execute<RowDataPacket[]>('SELECT portal_teacher_id FROM teachers WHERE nip=? LIMIT 1',[row.nip]);if(collision[0]&&collision[0].portal_teacher_id!==id)throw new Error('NIP guru sudah terdaftar untuk personel lain');}if(row.nuptk){const[collision]=await connection.execute<RowDataPacket[]>('SELECT portal_teacher_id FROM teachers WHERE nuptk=? LIMIT 1',[row.nuptk]);if(collision[0]&&collision[0].portal_teacher_id!==id)throw new Error('NUPTK sudah terdaftar untuk guru lain');}await connection.execute(`INSERT INTO teachers(portal_teacher_id,nip,nuptk,name_snapshot,status,last_synced_at) VALUES(?,?,?,?,?,${now}) ON DUPLICATE KEY UPDATE nip=IF(portal_teacher_id=VALUES(portal_teacher_id),VALUES(nip),nip),nuptk=IF(portal_teacher_id=VALUES(portal_teacher_id),VALUES(nuptk),nuptk),name_snapshot=IF(portal_teacher_id=VALUES(portal_teacher_id),VALUES(name_snapshot),name_snapshot),status=IF(portal_teacher_id=VALUES(portal_teacher_id),VALUES(status),status),last_synced_at=IF(portal_teacher_id=VALUES(portal_teacher_id),${now},last_synced_at)`,[id,row.nip||null,row.nuptk||null,name,active?'ACTIVE':'INACTIVE']);return;}
 if(type==='EMPLOYEES'){const name=String(row.name??row.nama??'').trim();if(!id||!name)throw new Error('Data pegawai invalid');if(row.nip){const[collision]=await connection.execute<RowDataPacket[]>('SELECT portal_employee_id FROM employees WHERE nip=? LIMIT 1',[row.nip]);if(collision[0]&&collision[0].portal_employee_id!==id)throw new Error('NIP pegawai sudah terdaftar untuk personel lain');}await connection.execute(`INSERT INTO employees(portal_employee_id,nip,name_snapshot,position_snapshot,status,last_synced_at) VALUES(?,?,?,?,?,${now}) ON DUPLICATE KEY UPDATE nip=IF(portal_employee_id=VALUES(portal_employee_id),VALUES(nip),nip),name_snapshot=IF(portal_employee_id=VALUES(portal_employee_id),VALUES(name_snapshot),name_snapshot),position_snapshot=IF(portal_employee_id=VALUES(portal_employee_id),VALUES(position_snapshot),position_snapshot),status=IF(portal_employee_id=VALUES(portal_employee_id),VALUES(status),status),last_synced_at=IF(portal_employee_id=VALUES(portal_employee_id),${now},last_synced_at)`,[id,row.nip||null,name,row.position||row.jabatan||null,active?'ACTIVE':'INACTIVE']);return;}
 if(type==='CLASSES'){const name=String(row.name??row.nama??'').trim();if(!id||!name)throw new Error('Data kelas invalid');await connection.execute(`INSERT INTO portal_classes(portal_class_id,code,name,grade,academic_year,status,last_synced_at) VALUES(?,?,?,?,?,?,${now}) ON DUPLICATE KEY UPDATE code=VALUES(code),name=VALUES(name),grade=VALUES(grade),academic_year=VALUES(academic_year),status=VALUES(status),last_synced_at=${now}`,[id,row.code??row.kode??name,name,grade(row.grade??row.tingkat),row.academic_year??row.tahun_ajaran??null,active?'ACTIVE':'INACTIVE']);return;}
 if(type==='ACADEMIC_YEARS'){if(!id||!row.name)throw new Error('Data tahun ajaran invalid');await connection.execute(`INSERT INTO portal_academic_years(portal_academic_year_id,name,is_active,last_synced_at) VALUES(?,?,?,${now}) ON DUPLICATE KEY UPDATE name=IF(portal_academic_year_id=VALUES(portal_academic_year_id),VALUES(name),name),is_active=IF(portal_academic_year_id=VALUES(portal_academic_year_id),VALUES(is_active),is_active),last_synced_at=IF(portal_academic_year_id=VALUES(portal_academic_year_id),${now},last_synced_at)`,[id,row.name,Number(Boolean(row.is_active))]);return;}
 const yearId=String(row.academic_year_id??'');const year=String(row.academic_year??'');const semester=String(row.type??'').toUpperCase();if(!id||!yearId||!year||!['ODD','EVEN'].includes(semester))throw new Error('Data semester invalid');await connection.execute(`INSERT INTO portal_semesters(portal_semester_id,portal_academic_year_id,type,academic_year,is_active,last_synced_at) VALUES(?,?,?,?,?,${now}) ON DUPLICATE KEY UPDATE portal_academic_year_id=IF(portal_semester_id=VALUES(portal_semester_id),VALUES(portal_academic_year_id),portal_academic_year_id),type=IF(portal_semester_id=VALUES(portal_semester_id),VALUES(type),type),academic_year=IF(portal_semester_id=VALUES(portal_semester_id),VALUES(academic_year),academic_year),is_active=IF(portal_semester_id=VALUES(portal_semester_id),VALUES(is_active),is_active),last_synced_at=IF(portal_semester_id=VALUES(portal_semester_id),${now},last_synced_at)`,[id,yearId,semester,year,Number(Boolean(row.is_active))]);}
export async function portalSyncRoutes(app:FastifyInstance){
 const admin=(request:FastifyRequest,mutate=false)=>requireRole(request,['ADMIN'],mutate);
 app.post<{Params:{type:string}}>('/api/admin/portal-data/sync/:type',async(request)=>{
  const claims=admin(request,true);const type=z.enum(types).parse(request.params.type.toUpperCase());const pool=requirePool();const lock=await pool.getConnection();let acquired=false;
  const[log]=await pool.execute('INSERT INTO portal_sync_logs(sync_type,started_at,status,initiated_by) VALUES(?,UTC_TIMESTAMP(3),\'RUNNING\',?)',[type,claims.sub]);
  const logId=(log as {insertId:number}).insertId;let total=0,processed=0,failed=0;let firstError='';
  try{
   const[locks]=await lock.query<RowDataPacket[]>('SELECT GET_LOCK(?,0) ok',[`arena:portal-sync:${type}`]);acquired=Boolean(locks[0]?.ok);
   if(!acquired)throw Object.assign(new Error('Sinkronisasi tipe ini sedang berjalan'),{statusCode:409});
   for(let page=1;;page++){
    const result=await fetchPage(type,page);const connection=await pool.getConnection();
    try{
     await connection.beginTransaction();
     for(const row of result.items){total++;try{await upsert(connection,type,row);processed++;}catch(error){failed++;if(!firstError)firstError=error instanceof Error?error.message:'Data invalid';}}
     await connection.commit();
    }catch(error){try{await connection.rollback();}catch{}throw error;}finally{connection.release();}
    if(!result.hasMore)break;if(page>=10000)throw new Error('Batas pagination aman terlampaui');
   }
   const status=failed?'PARTIAL':'SUCCESS';
   await pool.execute('UPDATE portal_sync_logs SET finished_at=UTC_TIMESTAMP(3),status=?,total=?,inserted_count=0,updated_count=0,failed_count=?,error_summary=? WHERE id=?',[status,total,failed,firstError||null,logId]);
   await audit(pool,claims.sub,claims.role,'PORTAL_DATA_SYNC','PortalData',type,undefined,{total,processed,failed,status});
   return {type,total,processed,failed,status};
  }catch(error){
   await pool.execute("UPDATE portal_sync_logs SET finished_at=UTC_TIMESTAMP(3),status='FAILED',total=?,failed_count=?,error_summary=? WHERE id=?",[total,failed+1,error instanceof Error?error.message:'Sync failed',logId]);throw error;
  }finally{if(acquired)try{await lock.query('SELECT RELEASE_LOCK(?)',[`arena:portal-sync:${type}`]);}catch{}lock.release();}
 });
 app.get('/api/admin/portal-data/sync/status',async(request)=>{admin(request);const query=z.object({limit:z.coerce.number().int().min(1).max(100).default(20)}).parse(request.query);const[rows]=await requirePool().execute<RowDataPacket[]>('SELECT * FROM portal_sync_logs ORDER BY id DESC LIMIT ?', [query.limit]);return rows;});
}
