import { createHash, createHmac, createPublicKey, randomBytes, timingSafeEqual, verify } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import type { RowDataPacket } from 'mysql2/promise';
import { z } from 'zod';
import { issueToken, newCsrf } from '../lib/auth.js';
import { requirePool } from '../lib/db.js';

const b64 = (value: Buffer | string) => Buffer.from(value).toString('base64url');
const secret = process.env.AUTH_TOKEN_SECRET ?? 'local-development-only';
const config = z.object({ OIDC_ISSUER:z.string().url().optional(), OIDC_CLIENT_ID:z.string().optional(), OIDC_REDIRECT_URI:z.string().url().optional(), OIDC_POST_LOGOUT_URI:z.string().url().optional() }).parse(process.env);
function signedState(value: object) { const payload=b64(JSON.stringify(value));const mac=createHmac('sha256',secret).update(payload).digest('base64url');return `${payload}.${mac}`; }
function readState(value:string) { const [payload,mac]=value.split('.');if(!payload||!mac)return null;const expected=createHmac('sha256',secret).update(payload).digest();const actual=Buffer.from(mac,'base64url');if(expected.length!==actual.length||!timingSafeEqual(expected,actual))return null;try{const state=JSON.parse(Buffer.from(payload,'base64url').toString());return state.exp>Date.now()/1000?state:null;}catch{return null;} }
async function json(url:string, options:RequestInit={}) { const response=await fetch(url,{...options,signal:AbortSignal.timeout(8000),headers:{accept:'application/json',...options.headers}});if(!response.ok)throw Object.assign(new Error(`SSO endpoint gagal (${response.status})`),{statusCode:502});return response.json() as Promise<Record<string,any>>; }
async function discovery() { if(!config.OIDC_ISSUER||!config.OIDC_CLIENT_ID||!config.OIDC_REDIRECT_URI)throw Object.assign(new Error('Konfigurasi OIDC belum lengkap'),{statusCode:503});const issuer=config.OIDC_ISSUER.replace(/\/$/,'');const data=await json(`${issuer}/.well-known/openid-configuration`);if(String(data.issuer).replace(/\/$/,'')!==issuer)throw Object.assign(new Error('Issuer OIDC tidak cocok'),{statusCode:502});for(const key of ['authorization_endpoint','token_endpoint','jwks_uri','userinfo_endpoint'])if(data[key]){const endpoint=new URL(data[key]);if(endpoint.protocol!=='https:'&& !['localhost','127.0.0.1'].includes(endpoint.hostname))throw Object.assign(new Error('Endpoint OIDC harus HTTPS'),{statusCode:502});}return data; }
async function validateIdToken(token:string, nonce:string, oidc:Record<string,any>) {
  const parts=token.split('.');if(parts.length!==3)throw Object.assign(new Error('ID token tidak valid'),{statusCode:401});let header:Record<string,any>,claims:Record<string,any>;try{header=JSON.parse(Buffer.from(parts[0]!, 'base64url').toString());claims=JSON.parse(Buffer.from(parts[1]!, 'base64url').toString());}catch{throw Object.assign(new Error('ID token tidak valid'),{statusCode:401});}if(header.alg!=='RS256'||typeof header.kid!=='string'||!header.kid)throw Object.assign(new Error('Algoritma ID token tidak didukung'),{statusCode:401});const jwks=await json(oidc.jwks_uri);const jwk=jwks.keys?.find((key:Record<string,string>)=>key.kid===header.kid&&key.kty==='RSA'&&(!key.use||key.use==='sig'));if(!jwk)throw Object.assign(new Error('Kunci SSO tidak ditemukan'),{statusCode:401});const publicKey=createPublicKey({key:jwk,format:'jwk'});const valid=verify('RSA-SHA256',Buffer.from(`${parts[0]}.${parts[1]}`),publicKey,Buffer.from(parts[2]!, 'base64url'));const aud=Array.isArray(claims.aud)?claims.aud:[claims.aud];const issuer=typeof claims.iss==='string'?claims.iss.replace(/\/$/,''):'';const now=Date.now()/1000;const azpOk=aud.length<2||claims.azp===config.OIDC_CLIENT_ID;if(!valid||issuer!==String(oidc.issuer).replace(/\/$/,'')||!aud.includes(config.OIDC_CLIENT_ID)||!azpOk||!Number.isFinite(Number(claims.exp))||Number(claims.exp)<=now||Number(claims.nbf)>now+60||claims.nonce!==nonce)throw Object.assign(new Error('Verifikasi identitas SSO gagal'),{statusCode:401});return claims as Record<string,any>;
}
export async function ssoRoutes(app:FastifyInstance) {
  app.get('/auth/sso/start',async(_request,reply)=>{const oidc=await discovery();const verifier=b64(randomBytes(32));const nonce=b64(randomBytes(24));const state=signedState({verifier,nonce,exp:Math.floor(Date.now()/1000)+300});const challenge=b64(createHash('sha256').update(verifier).digest());const url=new URL(oidc.authorization_endpoint);url.searchParams.set('client_id',config.OIDC_CLIENT_ID!);url.searchParams.set('redirect_uri',config.OIDC_REDIRECT_URI!);url.searchParams.set('response_type','code');url.searchParams.set('scope','openid profile email portal_role');url.searchParams.set('state',state);url.searchParams.set('nonce',nonce);url.searchParams.set('code_challenge',challenge);url.searchParams.set('code_challenge_method','S256');return reply.redirect(url.toString());});
  app.get('/auth/sso/callback',async(request,reply)=>{const query=z.object({state:z.string(),code:z.string().min(1)}).safeParse(request.query);if(!query.success)throw Object.assign(new Error('Callback SSO tidak lengkap'),{statusCode:400});const state=readState(query.data.state);if(!state)throw Object.assign(new Error('State SSO tidak valid atau kedaluwarsa'),{statusCode:400});const oidc=await discovery();const body=new URLSearchParams({grant_type:'authorization_code',client_id:config.OIDC_CLIENT_ID!,code:query.data.code,redirect_uri:config.OIDC_REDIRECT_URI!,code_verifier:state.verifier});const tokens=await json(oidc.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});const claims=await validateIdToken(String(tokens.id_token??''),state.nonce,oidc);let personClaims=claims;if(oidc.userinfo_endpoint&&tokens.access_token){const info=await json(oidc.userinfo_endpoint,{headers:{authorization:`Bearer ${tokens.access_token}`}});if(info.sub!==claims.sub)throw Object.assign(new Error('Subject userinfo tidak cocok dengan ID token'),{statusCode:401});personClaims={...claims,...info};}const nip=String(personClaims.preferred_username??'');const employeePortal=String(personClaims.portal_employee_id??'');const teacherPortal=String(personClaims.portal_teacher_id??'');const pool=requirePool();let person:RowDataPacket|undefined;let role:'TEACHER'|'EMPLOYEE'='TEACHER';let field='teacher_id';
    if(employeePortal){const[rows]=await pool.execute<RowDataPacket[]>("SELECT * FROM employees WHERE status='ACTIVE' AND (portal_employee_id=? OR (nip=? AND nip<>'')) LIMIT 1",[employeePortal,nip]);person=rows[0];role='EMPLOYEE';field='employee_id';}else{const[rows]=await pool.execute<RowDataPacket[]>("SELECT * FROM teachers WHERE status='ACTIVE' AND (portal_teacher_id=? OR (nip=? AND nip<>'')) LIMIT 1",[teacherPortal,nip]);person=rows[0];}
    if(!person)throw Object.assign(new Error('Personel belum tersinkron dari Portal Data'),{statusCode:403});const[users]=await pool.execute<RowDataPacket[]>(`SELECT id,username,name,role,status FROM users WHERE ${field}=? LIMIT 1`,[person.id]);let user=users[0];if(!user){const username=person.nip||`portal-${employeePortal||teacherPortal}`;const {hash}=await import('bcryptjs');const[insert]=await pool.execute('INSERT INTO users(teacher_id,employee_id,username,password_hash,name,role,status) VALUES(?,?,?,?,?,?,\'ACTIVE\')',[role==='TEACHER'?person.id:null,role==='EMPLOYEE'?person.id:null,username,await hash(randomBytes(32).toString('hex'),12),person.name_snapshot,role]);const id=(insert as {insertId:number}).insertId;const[created]=await pool.execute<RowDataPacket[]>('SELECT id,username,name,role,status FROM users WHERE id=?',[id]);user=created[0];}if(!user||user.status!=='ACTIVE'||user.role!==role)throw Object.assign(new Error('Akun personel Arena tidak aktif'),{statusCode:403});const csrf=newCsrf();const token=issueToken({sub:Number(user.id),role,exp:Math.floor(Date.now()/1000)+7200,csrf});reply.header('Cache-Control','no-store');const frontend=process.env.ARENA_WEB_URL;if(frontend){const target=new URL('/sso-complete',frontend);target.hash=new URLSearchParams({token,csrf,name:String(user.name),role}).toString();return reply.redirect(target.toString());}return {token,csrf_token:csrf,staff:{id:Number(user.id),name:user.name,role}};});
  app.get('/auth/sso/logout',async(_request,reply)=>{if(!config.OIDC_POST_LOGOUT_URI)return {success:true};const oidc=await discovery();if(!oidc.end_session_endpoint)return reply.redirect(config.OIDC_POST_LOGOUT_URI);const url=new URL(oidc.end_session_endpoint);url.searchParams.set('post_logout_redirect_uri',config.OIDC_POST_LOGOUT_URI);url.searchParams.set('client_id',config.OIDC_CLIENT_ID!);return reply.redirect(url.toString());});
}
