import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { RowDataPacket } from 'mysql2/promise';
import { requireRole } from '../lib/access.js';
import { requirePool } from '../lib/db.js';

export async function staffRoutes(app:FastifyInstance){
 app.get('/api/teacher/dashboard',async(request)=>{const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE']);const pool=requirePool();const admin=claims.role==='ADMIN';const examScope=admin?'':' AND EXISTS(SELECT 1 FROM teacher_exam_assignments x JOIN users u ON (u.teacher_id IS NOT NULL AND u.teacher_id=x.teacher_id) OR (u.employee_id IS NOT NULL AND u.employee_id=x.employee_id) WHERE u.id=? AND x.exam_id=e.id AND x.duty_role=\'TEACHER\')';const values=admin?[]:[claims.sub];const[exams]=await pool.execute<RowDataPacket[]>(`SELECT e.id,e.name,e.starts_at,e.ends_at,e.status,COUNT(DISTINCT a.id) attempts,SUM(a.status='IN_PROGRESS') in_progress FROM exams e LEFT JOIN exam_attempts a ON a.exam_id=e.id WHERE 1=1${examScope} GROUP BY e.id ORDER BY e.starts_at DESC LIMIT 100`,values);return{exams};});
 app.get('/api/teacher/live-sessions',async(request)=>{const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE']);const admin=claims.role==='ADMIN';const scope=admin?'':' AND EXISTS(SELECT 1 FROM teacher_exam_assignments x JOIN users u ON (u.teacher_id IS NOT NULL AND u.teacher_id=x.teacher_id) OR (u.employee_id IS NOT NULL AND u.employee_id=x.employee_id) WHERE u.id=? AND x.exam_id=e.id AND (x.duty_role=\'TEACHER\' OR (x.duty_role=\'PROCTOR\' AND x.exam_id IS NULL)))';const params=admin?[]:[claims.sub];const[rows]=await requirePool().execute<RowDataPacket[]>(`SELECT a.public_id,a.status,a.started_at,a.expires_at,a.violation_count,s.nisn,s.name_snapshot,s.class_snapshot,e.id exam_id,e.name exam_name,c.last_seen_at FROM exam_attempts a JOIN students s ON s.id=a.student_id JOIN exams e ON e.id=a.exam_id LEFT JOIN attempt_connections c ON c.attempt_id=a.id WHERE a.status='IN_PROGRESS'${scope} ORDER BY a.updated_at DESC LIMIT 500`,params);return rows;});
 app.get('/api/staff/violations',async(request)=>{const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE']);const admin=claims.role==='ADMIN';const scope=admin?'':' AND EXISTS(SELECT 1 FROM teacher_exam_assignments x JOIN users u ON (u.teacher_id IS NOT NULL AND u.teacher_id=x.teacher_id) OR (u.employee_id IS NOT NULL AND u.employee_id=x.employee_id) WHERE u.id=? AND (x.exam_id=e.id OR (x.duty_role=\'PROCTOR\' AND x.exam_id IS NULL)))';const params=admin?[]:[claims.sub];const[rows]=await requirePool().execute<RowDataPacket[]>(`SELECT v.id,v.type,v.event_key,v.occurred_at,a.status attempt_status,a.violation_count,e.id exam_id,e.name exam_name,s.nisn,s.name_snapshot,s.class_snapshot FROM violations v JOIN exam_attempts a ON a.id=v.attempt_id JOIN exams e ON e.id=a.exam_id JOIN students s ON s.id=a.student_id WHERE 1=1${scope} ORDER BY v.occurred_at DESC LIMIT 500`,params);return rows;});
}
