import { randomBytes } from 'node:crypto';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { RowDataPacket } from 'mysql2/promise';
import { z } from 'zod';
import { requireRole } from '../lib/access.js';
import { requirePool } from '../lib/db.js';
import { audit } from '../services/audit.js';
import { assertCsrf, claimsFromRequest } from '../lib/auth.js';

const ticketCategories = ['ACCOUNT_ACCESS','EXAM_LOCKED','PIN','CONNECTION','TECHNICAL','OTHER'] as const;
async function canHandle(pool: ReturnType<typeof requirePool>, userId: number) {
  const [rows] = await pool.execute<RowDataPacket[]>(`SELECT EXISTS(SELECT 1 FROM teacher_exam_assignments a JOIN users u ON (u.teacher_id IS NOT NULL AND u.teacher_id=a.teacher_id) OR (u.employee_id IS NOT NULL AND u.employee_id=a.employee_id) WHERE u.id=? AND a.duty_role='PROCTOR' AND a.exam_id IS NULL) ok`, [userId]);
  return Boolean(rows[0]?.ok);
}
function ticketSelect() { return `SELECT t.public_id id,t.student_id studentId,s.nisn,s.name_snapshot studentName,s.class_snapshot className,t.exam_id examId,e.name examName,t.category,t.message,t.status,t.handled_by,t.staff_note staffNote,t.resolution_type resolutionType,t.created_at createdAt,t.updated_at updatedAt,t.resolved_at resolvedAt,u.name handlerName,a.status attemptStatus,a.violation_count violationCount FROM support_tickets t JOIN students s ON s.id=t.student_id LEFT JOIN exams e ON e.id=t.exam_id LEFT JOIN exam_attempts a ON a.id=t.attempt_id LEFT JOIN users u ON u.id=t.handled_by`; }
async function getTicket(id: string, role: string, actorId: number) {
  const pool = requirePool(); const permissions = role === 'ADMIN' || await canHandle(pool, actorId);
  if (!permissions) throw Object.assign(new Error('Fitur tiket hanya untuk admin atau petugas piket'), { statusCode: 403 });
  const [rows] = await pool.execute<RowDataPacket[]>(`${ticketSelect()} WHERE t.public_id=? LIMIT 1`, [id]);
  if (!rows[0]) throw Object.assign(new Error('Tiket tidak ditemukan'), { statusCode: 404 });
  return rows[0];
}
export async function supportRoutes(app: FastifyInstance) {
  app.post('/api/student/support-tickets/request', async (request) => {
    const token=request.headers.authorization?.startsWith('Bearer ')?claimsFromRequest(request):null;if(token){if(token.role!=='STUDENT')throw Object.assign(new Error('Sesi siswa diperlukan'),{statusCode:403});assertCsrf(request,token);}
    const body = z.object({ category:z.enum(ticketCategories).default('OTHER'),message:z.string().trim().min(5).max(1000),exam_id:z.number().int().positive().nullable().optional(),nisn:z.string().trim().regex(/^\d{8,20}$/).optional() }).strict().parse(request.body); const pool=requirePool();
    if(!token&&!body.nisn)throw Object.assign(new Error('Masukkan NISN untuk membuat tiket bantuan'),{statusCode:422});
    const[students]=token?await pool.execute<RowDataPacket[]>('SELECT id FROM students WHERE id=? AND is_active=1',[token.sub]):await pool.execute<RowDataPacket[]>('SELECT id FROM students WHERE nisn=? AND is_active=1',[body.nisn??'']);const studentId=Number(students[0]?.id);if(!studentId)throw Object.assign(new Error('Siswa tidak ditemukan atau tidak aktif'),{statusCode:404});
    const [open] = await pool.execute<RowDataPacket[]>(`SELECT t.public_id id FROM support_tickets t WHERE t.student_id=? AND t.category=? AND COALESCE(t.exam_id,0)=COALESCE(?,0) AND t.status IN ('OPEN','IN_PROGRESS') ORDER BY t.id DESC LIMIT 1`, [studentId,body.category,body.exam_id??null]);
    if(open[0]) return open[0];
    const [attempts] = body.exam_id ? await pool.execute<RowDataPacket[]>('SELECT id FROM exam_attempts WHERE student_id=? AND exam_id=?', [studentId,body.exam_id]) : [[] as RowDataPacket[], []];
    if(body.exam_id&&!attempts[0]){const[eligibility]=await pool.execute<RowDataPacket[]>(`SELECT e.id FROM exams e JOIN students s ON s.id=? WHERE e.id=? AND e.status='ACTIVE' AND e.grade=s.grade_snapshot AND UTC_TIMESTAMP(3) BETWEEN e.starts_at AND e.ends_at AND (NOT EXISTS(SELECT 1 FROM exam_target_classes tc0 WHERE tc0.exam_id=e.id) OR EXISTS(SELECT 1 FROM exam_target_classes tc WHERE tc.exam_id=e.id AND tc.portal_class_id=s.portal_class_id)) AND (NOT EXISTS(SELECT 1 FROM exam_target_students ts0 WHERE ts0.exam_id=e.id) OR EXISTS(SELECT 1 FROM exam_target_students ts WHERE ts.exam_id=e.id AND ts.student_id=s.id))`,[studentId,body.exam_id]);if(!eligibility[0])throw Object.assign(new Error('Ujian tidak terkait dengan siswa ini'),{statusCode:422});}
    const id=ulid();
    await pool.execute('INSERT INTO support_tickets(public_id,student_id,exam_id,attempt_id,category,message) VALUES(?,?,?,?,?,?)', [id,studentId,body.exam_id??null,attempts[0]?.id??null,body.category,body.message]);
    await audit(pool,null,'STUDENT','SUPPORT_TICKET_CREATED','SupportTicket',id);
    return { id };
  });
  app.get('/api/student/support-tickets', async (request) => { const claims=requireRole(request,['STUDENT']);const [rows]=await requirePool().execute<RowDataPacket[]>(`${ticketSelect()} WHERE t.student_id=? ORDER BY t.updated_at DESC LIMIT 20`,[claims.sub]);return rows; });
  app.get('/api/staff/support-tickets', async (request) => {
    const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE']); const query=z.object({status:z.enum(['ALL','OPEN','IN_PROGRESS','RESOLVED','CLOSED']).default('ALL')}).parse(request.query); const pool=requirePool();
    if(claims.role!=='ADMIN'&&!(await canHandle(pool,claims.sub))) throw Object.assign(new Error('Akses tiket hanya untuk petugas piket'),{statusCode:403});
    const where=query.status==='ALL'?'':' AND t.status=?';const params=(query.status==='ALL'?[]:[query.status]) as string[];const [rows]=await pool.execute<RowDataPacket[]>(`${ticketSelect()} WHERE 1=1${where} ORDER BY FIELD(t.status,'OPEN','IN_PROGRESS','RESOLVED','CLOSED'),t.updated_at DESC LIMIT 200`,params);return rows;
  });
  app.post<{Params:{id:string}}>('/api/staff/support-tickets/:id/status', async (request) => {
    const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE'],true); const body=z.object({status:z.enum(['OPEN','IN_PROGRESS','RESOLVED','CLOSED']),note:z.string().max(1000).default('')}).strict().parse(request.body);const ticket=await getTicket(request.params.id,claims.role,claims.sub);
    if(claims.role!=='ADMIN'&&['OPEN','CLOSED'].includes(body.status)) throw Object.assign(new Error('Petugas hanya dapat mengambil atau menyelesaikan tiket'),{statusCode:403});
    if(['RESOLVED','CLOSED'].includes(ticket.status)) throw Object.assign(new Error('Tiket sudah ditutup'),{statusCode:409});
    if(ticket.status==='IN_PROGRESS'&&Number(ticket.handled_by)!==claims.sub) throw Object.assign(new Error('Tiket sedang ditangani petugas lain'),{statusCode:409});
    if(body.status==='RESOLVED'&&(ticket.status!=='IN_PROGRESS'||Number(ticket.handled_by)!==claims.sub)) throw Object.assign(new Error('Ambil tiket terlebih dahulu'),{statusCode:409});
    await requirePool().execute('UPDATE support_tickets SET status=?,handled_by=?,staff_note=?,resolution_type=?,resolved_at=IF(? IN (\'RESOLVED\',\'CLOSED\'),UTC_TIMESTAMP(3),NULL) WHERE public_id=?',[body.status,claims.sub,body.note||null,body.status==='RESOLVED'?'ASSISTED':null,body.status,request.params.id]);
    await audit(requirePool(),claims.sub,claims.role,'SUPPORT_TICKET_STATUS_CHANGED','SupportTicket',request.params.id,{status:ticket.status},{status:body.status,note:body.note});return {success:true};
  });
  app.post<{Params:{id:string}}>('/api/staff/support-tickets/:id/reset', async (request) => {
    const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE'],true);const body=z.object({reason:z.string().trim().min(3).max(1000)}).strict().parse(request.body);const ticket=await getTicket(request.params.id,claims.role,claims.sub);
    if(ticket.status!=='IN_PROGRESS'||Number(ticket.handled_by)!==claims.sub)throw Object.assign(new Error('Ambil tiket terlebih dahulu'),{statusCode:409});
    if(ticket.attemptStatus!=='TERMINATED'||Number(ticket.violationCount)<3)throw Object.assign(new Error('Reset hanya untuk siswa yang dihentikan setelah tiga pelanggaran'),{statusCode:409});
    const reset = await resetAttempt(Number(ticket.studentId),Number(ticket.examId),claims.sub,claims.role,body.reason);
    await requirePool().execute("UPDATE support_tickets SET status='RESOLVED',staff_note=?,resolution_type='CBT_RESET',resolved_at=UTC_TIMESTAMP(3) WHERE public_id=?",[body.reason,request.params.id]);
    return {reset,ticket:{id:request.params.id,resolutionType:'CBT_RESET'}};
  });
  app.post('/api/staff/admin-communications', async (request) => {
    const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE'],true);const pool=requirePool();if(claims.role!=='ADMIN'&&!(await canHandle(pool,claims.sub)))throw Object.assign(new Error('Fitur komunikasi hanya untuk petugas piket'),{statusCode:403});const body=z.object({category:z.enum(['TECHNICAL','ASSISTANCE','EXAM_REPORT','EMERGENCY','OTHER']).default('OTHER'),subject:z.string().trim().min(4).max(180),message:z.string().trim().min(2).max(2000)}).strict().parse(request.body);const id=ulid();
    await pool.query('START TRANSACTION');try{const [result]=await pool.execute('INSERT INTO staff_admin_threads(public_id,created_by,category,subject,status) VALUES(?,?,?,? ,\'OPEN\')',[id,claims.sub,body.category,body.subject]);const threadId=(result as {insertId:number}).insertId;await pool.execute('INSERT INTO staff_admin_messages(thread_id,sender_user_id,message) VALUES(?,?,?)',[threadId,claims.sub,body.message]);await pool.query('COMMIT');}catch(error){await pool.query('ROLLBACK');throw error;}return {id};
  });
  app.get('/api/staff/admin-communications', async (request) => {const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE']);const pool=requirePool();if(claims.role!=='ADMIN'&&!(await canHandle(pool,claims.sub)))throw Object.assign(new Error('Fitur komunikasi hanya untuk petugas piket'),{statusCode:403});const where=claims.role==='ADMIN'?'':'WHERE t.created_by=?';const params=claims.role==='ADMIN'?[]:[claims.sub];const [rows]=await pool.execute<RowDataPacket[]>(`SELECT t.public_id id,t.category,t.subject,t.status,t.created_at,t.updated_at,u.name creator_name,(SELECT message FROM staff_admin_messages m WHERE m.thread_id=t.id ORDER BY m.id DESC LIMIT 1) last_message FROM staff_admin_threads t JOIN users u ON u.id=t.created_by ${where} ORDER BY t.updated_at DESC LIMIT 200`,params);return rows;});
  app.get<{Params:{id:string}}>('/api/staff/admin-communications/:id', async (request) => {const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE']);const pool=requirePool();if(claims.role!=='ADMIN'&&!(await canHandle(pool,claims.sub)))throw Object.assign(new Error('Fitur komunikasi hanya untuk petugas piket'),{statusCode:403});const where=claims.role==='ADMIN'?'':' AND created_by=?';const params=claims.role==='ADMIN'?[request.params.id]:[request.params.id,claims.sub];const [threads]=await pool.execute<RowDataPacket[]>(`SELECT * FROM staff_admin_threads WHERE public_id=?${where}`,params);const thread=threads[0];if(!thread)throw Object.assign(new Error('Percakapan tidak ditemukan'),{statusCode:404});await pool.execute('UPDATE staff_admin_messages SET read_at=COALESCE(read_at,UTC_TIMESTAMP(3)) WHERE thread_id=? AND sender_user_id<>?',[thread.id,claims.sub]);if(claims.role==='ADMIN'&&thread.status==='OPEN')await pool.execute("UPDATE staff_admin_threads SET status='READ' WHERE id=?",[thread.id]);const [messages]=await pool.execute<RowDataPacket[]>('SELECT m.id,m.message,m.attachment_path,m.created_at,m.sender_user_id,u.name sender_name,u.role sender_role FROM staff_admin_messages m JOIN users u ON u.id=m.sender_user_id WHERE m.thread_id=? ORDER BY m.id',[thread.id]);return {thread,messages};});
  app.post<{Params:{id:string}}>('/api/staff/admin-communications/:id/messages', async (request) => {const claims=requireRole(request,['ADMIN','TEACHER','EMPLOYEE'],true);const body=z.object({message:z.string().trim().min(2).max(2000)}).strict().parse(request.body);const pool=requirePool();const where=claims.role==='ADMIN'?'':' AND created_by=?';const params=claims.role==='ADMIN'?[request.params.id]:[request.params.id,claims.sub];const [rows]=await pool.execute<RowDataPacket[]>(`SELECT id,status FROM staff_admin_threads WHERE public_id=?${where}`,params);const thread=rows[0];if(!thread)throw Object.assign(new Error('Percakapan tidak ditemukan'),{statusCode:404});if(thread.status==='RESOLVED')throw Object.assign(new Error('Percakapan sudah selesai'),{statusCode:409});await pool.execute('INSERT INTO staff_admin_messages(thread_id,sender_user_id,message) VALUES(?,?,?)',[thread.id,claims.sub,body.message]);await pool.execute('UPDATE staff_admin_threads SET status=?,resolved_at=NULL WHERE id=?',[claims.role==='ADMIN'?'IN_PROGRESS':'OPEN',thread.id]);return {success:true};});
  app.post<{Params:{id:string}}>('/api/staff/admin-communications/:id/status', async (request) => {const claims=requireRole(request,['ADMIN'],true);const {status}=z.object({status:z.enum(['OPEN','READ','IN_PROGRESS','RESOLVED'])}).strict().parse(request.body);const [result]=await requirePool().execute('UPDATE staff_admin_threads SET status=?,resolved_at=IF(?=\'RESOLVED\',UTC_TIMESTAMP(3),NULL) WHERE public_id=?',[status,status,request.params.id]);if((result as {affectedRows:number}).affectedRows===0)throw Object.assign(new Error('Percakapan tidak ditemukan'),{statusCode:404});return {success:true};});
}
async function resetAttempt(studentId:number,examId:number,actorId:number,role:string,reason:string){const pool=requirePool();const c=await pool.getConnection();try{await c.beginTransaction();const[rows]=await c.execute<RowDataPacket[]>('SELECT a.*,s.cbt_status,s.is_active FROM exam_attempts a JOIN students s ON s.id=a.student_id WHERE a.student_id=? AND a.exam_id=? FOR UPDATE',[studentId,examId]);const a=rows[0];if(!a||a.status!=='TERMINATED'||Number(a.violation_count)<3)throw Object.assign(new Error('Attempt tidak memenuhi syarat reset'),{statusCode:409});if(!a.is_active||a.cbt_status!=='ACTIVE')throw Object.assign(new Error('Akun siswa tidak aktif'),{statusCode:409});if(role!=='ADMIN'){const[perm]=await c.execute<RowDataPacket[]>("SELECT EXISTS(SELECT 1 FROM teacher_exam_assignments WHERE duty_role='PROCTOR' AND exam_id IS NULL AND ((teacher_id=(SELECT teacher_id FROM users WHERE id=?)) OR (employee_id=(SELECT employee_id FROM users WHERE id=?)))) ok",[actorId,actorId]);if(!perm[0]?.ok)throw Object.assign(new Error('Reset hanya untuk petugas piket'),{statusCode:403});}const[last]=await c.execute<RowDataPacket[]>('SELECT MAX(occurred_at) t FROM violations WHERE attempt_id=?',[a.id]);const stopped=last[0]?.t?new Date(last[0].t).getTime():Date.now();const remaining=new Date(a.expires_at).getTime()-stopped;if(remaining<=0)throw Object.assign(new Error('Sisa waktu ujian habis'),{statusCode:409});const expires=new Date(Date.now()+remaining).toISOString().slice(0,19).replace('T',' ');await c.execute('DELETE FROM exam_results WHERE attempt_id=?',[a.id]);await c.execute("UPDATE exam_attempts SET status='IN_PROGRESS',violation_count=0,completed_at=NULL,expires_at=? WHERE id=?",[expires,a.id]);await c.execute("INSERT INTO audit_logs(actor_user_id,actor_role,action,entity_type,entity_id,after_data) VALUES(?,?,'CBT_ATTEMPT_RESUMED','ExamAttempt',?,?)",[actorId,role,a.public_id,JSON.stringify({reason,expires_at:expires})]);await c.commit();return{attempt_id:a.public_id,expires_at:expires};}catch(e){try{await c.rollback();}catch{}throw e;}finally{c.release();}}
function ulid(){const chars='0123456789ABCDEFGHJKMNPQRSTVWXYZ';let t=Date.now(),s='';for(let i=0;i<10;i++){s=chars[t%32]+s;t=Math.floor(t/32);}for(const x of randomBytes(16))s+=chars[x&31];return s;}
