import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {FormEvent,useState} from 'react';
import {Link,Navigate,NavLink,Route,Routes,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowRight,Camera,ExternalLink,Globe2,Home,KeyRound,LogOut,MonitorSmartphone,ShieldCheck,UserRound} from 'lucide-react';
import {DetailItem,EmptyState,ErrorState,FormField,LoadingSkeleton,PageHeader,SectionCard,StatusBadge,useToast} from '../components/management';
import {api} from '../lib/api';
type Me={publicId:string;username:string;fullName:string};
type Profile={teacherPublicId:string;accountPublicId:string;username:string;email?:string;fullName:string;nip?:string;nuptk?:string;employeeNumber?:string;gender?:string;phone?:string;address?:string;photoUrl?:string;teacherStatus:string;accountStatus:string;lastLoginAt?:string};
type Session={publicId:string;device:string;ipAddress?:string;lastUsedAt:string;current?:boolean};
type TeacherApplication={publicId:string;name:string;slug:string;description?:string;role:string;launchUrl?:string};
export function validTeacherPassword(v:string){return v.length>=10&&/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/[0-9]/.test(v)}
export function validOidcReturnTo(v:string|null):v is string{return !!v&&(v==='/oidc/authorize'||v.startsWith('/oidc/authorize?'))}
function Login(){const[params]=useSearchParams(),returnTo=params.get('returnTo'),[u,setU]=useState(''),[p,setP]=useState(''),[show,setShow]=useState(false),nav=useNavigate(),toast=useToast(),m=useMutation({mutationFn:()=>api('/auth/teacher/login',{method:'POST',body:JSON.stringify({username:u,password:p})}),onSuccess:()=>validOidcReturnTo(returnTo)?location.assign(returnTo):nav('/teacher'),onError:()=>toast('Username atau password tidak valid.','error')});return <main className="login"><form onSubmit={(e:FormEvent)=>{e.preventDefault();if(!m.isPending)m.mutate()}}><h1>Portal Guru</h1><p className="page-description">Kelola profil, keamanan, dan sesi akun sekolah.</p><FormField label="Username"><input value={u} onChange={e=>setU(e.target.value)} autoComplete="username" required/></FormField><FormField label="Password"><input type={show?'text':'password'} value={p} onChange={e=>setP(e.target.value)} autoComplete="current-password" required/></FormField><label><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Tampilkan password</label><button className="primary" disabled={!u||!p||m.isPending}>{m.isPending?'Memproses…':'Masuk'}</button></form></main>}
function Setup(){const[params]=useSearchParams(),token=params.get('token')??'',q=useQuery({queryKey:['teacher-setup',token],queryFn:()=>api<any>(`/auth/teacher/password-setup/validate?token=${encodeURIComponent(token)}`),enabled:!!token,retry:false}),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[done,setDone]=useState(false),toast=useToast(),m=useMutation({mutationFn:()=>api('/auth/teacher/password-setup',{method:'POST',body:JSON.stringify({token,password,passwordConfirmation:confirmation})}),onSuccess:()=>setDone(true),onError:e=>toast((e as Error).message,'error')});if(!token||q.isError||q.data&&!q.data.data.valid)return <main className="login"><section><h1>Link tidak valid</h1><p>Token telah digunakan, kedaluwarsa, atau tidak valid.</p><Link to="/teacher/login">Ke halaman login</Link></section></main>;if(q.isPending)return <LoadingSkeleton/>;if(done)return <main className="login"><section><h1>Password berhasil diatur</h1><Link to="/teacher/login">Login sebagai guru</Link></section></main>;return <main className="login"><form onSubmit={e=>{e.preventDefault();m.mutate()}}><h1>Atur Password</h1><p>{q.data?.data.account?.fullName}</p><FormField label="Password"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></FormField><small>Minimal 10 karakter, huruf besar, huruf kecil, dan angka.</small><FormField label="Konfirmasi"><input type="password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/></FormField><button className="primary" disabled={!validTeacherPassword(password)||password!==confirmation||m.isPending}>Aktifkan akun</button></form></main>}
function Dashboard({me}:{me:Me}){
 const profileQuery=useQuery({queryKey:['teacher-dashboard-profile'],queryFn:()=>api<Profile>('/teacher/profile')});
 const sessions=useQuery({queryKey:['teacher-dashboard-sessions'],queryFn:()=>api<Session[]>('/teacher/sessions')});
 const applications=useQuery({queryKey:['teacher-applications'],queryFn:()=>api<TeacherApplication[]>('/teacher/applications')});
 if(profileQuery.isPending)return <LoadingSkeleton/>;
 if(profileQuery.isError)return <ErrorState retry={()=>profileQuery.refetch()}/>;
 const profile=profileQuery.data.data,fields=[profile.email,profile.phone,profile.address,profile.nip,profile.nuptk].filter(Boolean).length,progress=Math.round(fields/5*100),firstName=me.fullName.trim().split(/\s+/)[0],lastLogin=profile.lastLoginAt?new Date(profile.lastLoginAt).toLocaleString('id-ID'):'Belum tersedia';
 return <div className="page teacher-dashboard">
  <section className="teacher-welcome"><div><span className="teacher-eyebrow">Portal Guru</span><h1>Halo, {firstName}.</h1><p>Akses aplikasi sekolah dan kelola akun Anda dari satu tempat.</p></div><div className="teacher-avatar">{me.fullName.slice(0,2).toUpperCase()}</div></section>
  <section className="teacher-applications"><div className="teacher-section-heading"><div><span className="teacher-eyebrow">Website sekolah</span><h2>Aplikasi Anda</h2><p>Aplikasi yang telah diberikan untuk akun ini.</p></div></div>{applications.isPending?<LoadingSkeleton rows={2}/>:applications.isError?<ErrorState retry={()=>applications.refetch()}/>:applications.data.data.length?<div className="teacher-application-grid">{applications.data.data.map((application,index)=>{const content=<><span className="application-number">{String(index+1).padStart(2,'0')}</span><Globe2/><div><strong>{application.name}</strong><p>{application.description||'Aplikasi sekolah terhubung melalui Portal Data.'}</p><small>{application.role}</small></div>{application.launchUrl?<ExternalLink/>:<span className="application-unavailable">URL belum tersedia</span>}</>;return application.launchUrl?<a key={application.publicId} href={application.launchUrl} target="_blank" rel="noreferrer">{content}</a>:<article key={application.publicId}>{content}</article>})}</div>:<EmptyState title="Belum ada aplikasi" description="Hubungi administrator untuk mendapatkan akses aplikasi sekolah."/>}</section>
  <div className="teacher-metrics"><article><span>Status akun</span><StatusBadge value={profile.accountStatus}/><small>Akses portal tersedia</small></article><article><span>Kelengkapan profil</span><strong>{progress}%</strong><div className="profile-progress"><i style={{width:`${progress}%`}}/></div></article><article><span>Perangkat aktif</span><strong>{sessions.data?.data.length??0}</strong><small>Login yang masih terhubung</small></article></div>
  <section className="teacher-access"><div className="teacher-section-heading"><div><h2>Kelola akun</h2><p>Profil, password, dan perangkat aktif.</p></div></div><div className="teacher-action-grid"><Link to="/teacher/profile"><UserRound/><div><strong>Profil saya</strong><span>Data kontak dan identitas</span></div><ArrowRight/></Link><Link to="/teacher/profile"><Camera/><div><strong>Foto profil</strong><span>Perbarui foto akun</span></div><ArrowRight/></Link><Link to="/teacher/security"><KeyRound/><div><strong>Ganti password</strong><span>Jaga keamanan akun</span></div><ArrowRight/></Link><Link to="/teacher/sessions"><MonitorSmartphone/><div><strong>Perangkat & sesi</strong><span>Periksa akses yang aktif</span></div><ArrowRight/></Link></div></section>
  <section className="teacher-account-summary"><div><ShieldCheck/><div><h2>Ringkasan akun</h2><p>Informasi utama akun Portal Data Anda.</p></div></div><dl><div><dt>Username</dt><dd>{profile.username}</dd></div><div><dt>Email</dt><dd>{profile.email||'Belum diisi'}</dd></div><div><dt>Login terakhir</dt><dd>{lastLogin}</dd></div></dl></section>
 </div>
}
function Profile(){const q=useQuery({queryKey:['teacher-profile'],queryFn:()=>api<Profile>('/teacher/profile')}),toast=useToast(),qc=useQueryClient(),[editing,setEditing]=useState(false),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),m=useMutation({mutationFn:()=>api('/teacher/profile',{method:'PATCH',body:JSON.stringify({email,phone,address})}),onSuccess:r=>{toast(r.message);setEditing(false);qc.invalidateQueries({queryKey:['teacher-profile','teacher-dashboard-profile']})},onError:e=>toast((e as Error).message,'error')});if(q.isPending)return <LoadingSkeleton/>;if(q.isError)return <ErrorState retry={()=>q.refetch()}/>;const p=q.data.data;if(editing)return <form className="formcard" onSubmit={e=>{e.preventDefault();m.mutate()}}><FormField label="Email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></FormField><FormField label="Telepon"><input value={phone} onChange={e=>setPhone(e.target.value)}/></FormField><FormField label="Alamat"><textarea value={address} onChange={e=>setAddress(e.target.value)}/></FormField><div className="actions"><button type="button" onClick={()=>setEditing(false)}>Batal</button><button className="primary">Simpan</button></div></form>;return <><PageHeader title={p.fullName} description={p.username} action={<button onClick={()=>{setEmail(p.email??'');setPhone(p.phone??'');setAddress(p.address??'');setEditing(true)}}>Edit profil</button>}/><TeacherPhotoUpload photoUrl={p.photoUrl} fullName={p.fullName}/><div className="details"><DetailItem label="Status akun" value={<StatusBadge value={p.accountStatus}/>}/><DetailItem label="NIP" value={p.nip}/><DetailItem label="NUPTK" value={p.nuptk}/><DetailItem label="Nomor pegawai" value={p.employeeNumber}/><DetailItem label="Email" value={p.email}/><DetailItem label="Telepon" value={p.phone}/><DetailItem label="Alamat" value={p.address}/></div></>}
function Security(){const[c,setC]=useState(''),[n,setN]=useState(''),[x,setX]=useState(''),toast=useToast(),m=useMutation({mutationFn:()=>api('/teacher/profile/change-password',{method:'POST',body:JSON.stringify({currentPassword:c,newPassword:n,confirmation:x})}),onSuccess:r=>{toast(r.message);setC('');setN('');setX('')},onError:e=>toast((e as Error).message,'error')});return <div><PageHeader title="Keamanan" description="Ganti password akun guru"/><form className="formcard" onSubmit={e=>{e.preventDefault();m.mutate()}}><FormField label="Password saat ini"><input type="password" value={c} onChange={e=>setC(e.target.value)} required/></FormField><FormField label="Password baru"><input type="password" value={n} onChange={e=>setN(e.target.value)} required/></FormField><FormField label="Konfirmasi"><input type="password" value={x} onChange={e=>setX(e.target.value)} required/></FormField><button className="primary" disabled={!validTeacherPassword(n)||n!==x||m.isPending}>Ganti password</button></form></div>}
function Sessions(){const q=useQuery({queryKey:['teacher-sessions'],queryFn:()=>api<Session[]>('/teacher/sessions')}),qc=useQueryClient(),toast=useToast(),m=useMutation({mutationFn:(id?:string)=>api(id?`/teacher/sessions/${id}`:'/teacher/sessions/logout-all',{method:id?'DELETE':'POST'}),onSuccess:r=>{toast(r.message);qc.invalidateQueries({queryKey:['teacher-sessions','teacher-dashboard-sessions']})}});return <section><PageHeader title="Sesi aktif" description="Cabut akses perangkat yang tidak dikenal."/>{q.isPending?<LoadingSkeleton/>:!q.data?.data.length?<EmptyState title="Tidak ada sesi"/>:<div className="tablewrap"><table><thead><tr><th>Perangkat</th><th>IP</th><th>Terakhir digunakan</th><th>Aksi</th></tr></thead><tbody>{q.data.data.map(s=><tr key={s.publicId}><td>{s.device}{s.current?' (saat ini)':''}</td><td>{s.ipAddress??'—'}</td><td>{new Date(s.lastUsedAt).toLocaleString('id-ID')}</td><td>{!s.current&&<button onClick={()=>m.mutate(s.publicId)}>Cabut</button>}</td></tr>)}</tbody></table></div>}<button className="danger" onClick={()=>m.mutate(undefined)}>Logout semua perangkat</button></section>}
function Protected(){const me=useQuery({queryKey:['teacher-me'],queryFn:()=>api<Me>('/auth/teacher/me'),retry:false});if(me.isPending)return <LoadingSkeleton/>;if(me.isError)return <Navigate to="/teacher/login" replace/>;return <div className="shell teacher-shell"><aside><div className="teacher-brand"><span>PD</span><div><strong>Portal Guru</strong><small>Portal Data Sekolah</small></div></div><nav><NavLink to="/teacher" end><Home/>Beranda</NavLink><NavLink to="/teacher/profile"><UserRound/>Profil</NavLink><NavLink to="/teacher/security"><KeyRound/>Keamanan</NavLink><NavLink to="/teacher/sessions"><MonitorSmartphone/>Sesi</NavLink></nav><div className="teacher-side-account"><span>{me.data.data.fullName.slice(0,2).toUpperCase()}</span><div><strong>{me.data.data.fullName}</strong><small>@{me.data.data.username}</small></div></div><button className="teacher-logout" onClick={()=>api('/auth/teacher/logout',{method:'POST'}).finally(()=>location.assign('/teacher/login'))}><LogOut/>Keluar</button></aside><main><Routes><Route path="/teacher" element={<Dashboard me={me.data.data}/>}/><Route path="/teacher/profile" element={<div className="page teacher-subpage"><Profile/></div>}/><Route path="/teacher/security" element={<div className="page teacher-subpage"><Security/></div>}/><Route path="/teacher/sessions" element={<div className="page teacher-subpage"><Sessions/></div>}/></Routes></main></div>}
export function TeacherPortal(){return <Routes><Route path="/teacher/login" element={<Login/>}/><Route path="/teacher/setup-password" element={<Setup/>}/><Route path="/teacher/*" element={<Protected/>}/></Routes>}
function TeacherPhotoUpload({photoUrl,fullName}:{photoUrl:string|undefined;fullName:string}){const[file,setFile]=useState<File>(),toast=useToast(),qc=useQueryClient(),upload=useMutation({mutationFn:()=>{const body=new FormData();if(file)body.append('file',file);return api('/teacher/profile/photo',{method:'POST',body})},onSuccess:r=>{toast(r.message);setFile(undefined);qc.invalidateQueries({queryKey:['teacher-profile','teacher-dashboard-profile']})},onError:e=>toast((e as Error).message,'error')});return <section className="profile"><div>{photoUrl?<img className="avatar" src={photoUrl} alt={`Foto ${fullName}`}/>:<div className="avatar fallback">{fullName.slice(0,2).toUpperCase()}</div>}<label className="upload">Foto JPEG/PNG/WebP, maks. 2 MB<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0])}/></label><button disabled={!file||upload.isPending} onClick={()=>upload.mutate()}>{upload.isPending?'Mengunggah…':'Unggah foto'}</button></div></section>}
