import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { ConfirmDialog, CopyButton, DetailItem, EmptyState, ErrorState, LoadingSkeleton, Modal, StatusBadge, useToast } from '../components/management';
import { api } from '../lib/api';
type Account = { publicId: string; username: string; email?: string; status: string; lastLoginAt?: string; passwordConfigured: boolean };
export function TeacherAccountPanel({ teacherId }: { teacherId: string }) {
    const q = useQuery({ queryKey: ['teacher-account', teacherId], queryFn: () => api<Account | null>(`/teachers/${teacherId}/account`) });
    const qc = useQueryClient(), toast = useToast();
    const [url, setUrl] = useState(''), [password, setPassword] = useState(''), [mailStatus, setMailStatus] = useState(''), [action, setAction] = useState<string>();
    const mutation = useMutation({ mutationFn: async () => action === 'create' ? api<any>(`/teachers/${teacherId}/account`, { method: 'POST', body: '{}' }) : api<any>(`/teachers/${teacherId}/account/${action}`, { method: 'POST' }), onSuccess: r => { toast(r.message); if (r.data?.defaultPassword) setPassword(r.data.defaultPassword); if (r.data?.passwordSetupUrl) { setUrl(r.data.passwordSetupUrl); setMailStatus(r.data.mailStatus ?? ''); } setAction(undefined); qc.invalidateQueries({ queryKey: ['teacher-account', teacherId] }); }, onError: e => toast((e as Error).message, 'error') });
    if (q.isPending) return <LoadingSkeleton rows={2}/>;
    if (q.isError) return <ErrorState retry={() => q.refetch()}/>;
    const a = q.data.data, open = Boolean(url || password);
    return <section><h2>Akun Portal</h2>{!a ? <div className="formcard"><EmptyState title="Akun belum dibuat"/><p>Username akan dibuat otomatis dari NIP, NUPTK, atau nomor pegawai.</p><button className="primary" disabled={mutation.isPending} onClick={() => setAction('create')}>Buat akun dan kirim aktivasi</button></div> : <><div className="details"><DetailItem label="Status" value={<StatusBadge value={a.status}/>}/><DetailItem label="Username" value={a.username}/><DetailItem label="Email" value={a.email}/><DetailItem label="Login terakhir" value={a.lastLoginAt ? new Date(a.lastLoginAt).toLocaleString('id-ID') : '—'}/></div><div className="actions">{a.status === 'PENDING_SETUP' && <button onClick={() => setAction('setup-token')}>Kirim ulang aktivasi</button>}{a.status === 'ACTIVE' && <button className="danger" onClick={() => setAction('disable')}>Nonaktifkan</button>}{a.status === 'DISABLED' && <button onClick={() => setAction('enable')}>Aktifkan</button>}{a.status === 'LOCKED' && <button onClick={() => setAction('unlock')}>Buka kunci</button>}<button onClick={() => setAction('revoke-sessions')}>Cabut seluruh session</button></div></>}<ConfirmDialog open={!!action} title={action === 'create' ? 'Buat akun guru?' : 'Konfirmasi tindakan akun'} description={action === 'create' ? 'Username dibuat otomatis dan tautan aktivasi akan dikirim melalui email.' : 'Perubahan credential dan session akan dicatat dalam audit log.'} busy={mutation.isPending} onClose={() => setAction(undefined)} onConfirm={() => mutation.mutate()}/><Modal title={password ? 'Credential akun guru' : 'Tautan aktivasi satu kali'} open={open} onClose={() => { setUrl(''); setPassword(''); }}>{password && <><p><strong>Password awal</strong> hanya ditampilkan sekali. Salin dan simpan secara aman.</p><input readOnly value={password}/><div className="actions"><CopyButton value={password} label="Salin password"/></div></>}{url && <><p>{mailStatus === 'SENT' ? 'Tautan aktivasi berhasil dikirim ke email guru.' : 'Salin tautan ini dan berikan kepada guru.'}</p><textarea readOnly value={url}/><div className="actions"><CopyButton value={url} label="Salin URL"/></div></>}<button className="primary" onClick={() => { setUrl(''); setPassword(''); }}>Selesai</button></Modal></section>;
}
