import React,{createContext,useContext,useEffect,useId,useRef,useState}from'react';import{Check,ChevronLeft,ChevronRight,Copy,Eye,EyeOff,Search,X}from'lucide-react';import type{PageMeta}from'../lib/api';
export const statusLabels:Record<string,string>={ACTIVE:'Aktif',INACTIVE:'Tidak Aktif',ARCHIVED:'Diarsipkan',GRADUATED:'Lulus',TRANSFERRED:'Pindah',DROPPED_OUT:'Keluar',ODD:'Ganjil',EVEN:'Genap',PENDING_SETUP:'Menunggu Pengaturan',DISABLED:'Dinonaktifkan',LOCKED:'Terkunci',VALID:'Valid',WARNING:'Peringatan',FAILED:'Gagal',READY:'Siap Diproses',PROCESSING:'Sedang Diproses',COMPLETED:'Selesai',COMPLETED_WITH_WARNINGS:'Selesai dengan Peringatan',INSERTED:'Ditambahkan',UPDATED:'Diperbarui',SKIPPED:'Dilewati',DELETED:'Dihapus',SUPER_ADMIN:'Super Admin',DATA_ADMIN:'Admin Data',DATA_OPERATOR:'Operator Data',AUDITOR:'Auditor',STUDENT:'Siswa',TEACHER:'Guru',ADMIN:'Administrator',SYSTEM:'Sistem',APPLICATION:'Aplikasi'};
export const humanizeStatus=(value:string|boolean|null|undefined)=>value==null||value===''?'—':typeof value==='boolean'?(value?'Aktif':'Tidak Aktif'):statusLabels[value]??String(value).replaceAll('_',' ').toLowerCase().replace(/(^|\s)\S/g,x=>x.toUpperCase());
export function PageHeader({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className="pagehead"><div><p className="breadcrumb" aria-label="Breadcrumb">Portal Data <span aria-hidden="true">/</span> {title}</p><h1>{title}</h1>{description&&<p className="page-description">{description}</p>}</div>{action&&<div className="responsive-actions">{action}</div>}</div>}
export function SectionCard({title,description,children,className=''}:React.PropsWithChildren<{title?:string;description?:string;className?:string}>){return <section className={`section-card ${className}`}>{title&&<header className="section-head"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div></header>}{children}</section>}
export function LoadingSkeleton({rows=4}:{rows?:number}){return <div className="loading" aria-busy="true" aria-live="polite" aria-label="Memuat data">{Array.from({length:rows},(_,i)=><i key={i}/>)}</div>}
export function EmptyState({title='Belum ada data',description,action}:{title?:string;description?:string;action?:React.ReactNode}){return <section className="state empty-state"><h3>{title}</h3>{description&&<p>{description}</p>}{action}</section>}
export function ErrorState({retry,message='Data gagal dimuat.'}:{retry:()=>void;message?:string}){return <section className="state error-state" role="alert"><h3>Terjadi kendala</h3><p>{message}</p><button onClick={retry}>Coba lagi</button></section>}
export function StatusBadge({value}:{value:string|boolean|null|undefined}){return <span className={`badge ${value==null?'unknown':String(value).toLowerCase()}`}><span className="status-dot" aria-hidden="true"/>{humanizeStatus(value)}</span>}
export function RoleBadge({value}:{value:string}){return <span className="role-badge">{humanizeStatus(value)}</span>}
export function ServerPagination({meta,onPage}:{meta?:PageMeta|undefined;onPage:(page:number)=>void}){if(!meta||meta.totalPages<=1)return null;return <nav className="pagination" aria-label="Navigasi halaman"><button aria-label="Halaman sebelumnya" disabled={meta.page<=1} onClick={()=>onPage(meta.page-1)}><ChevronLeft size={18}/></button><span>Halaman {meta.page} dari {meta.totalPages} · {meta.total} data</span><button aria-label="Halaman berikutnya" disabled={meta.page>=meta.totalPages} onClick={()=>onPage(meta.page+1)}><ChevronRight size={18}/></button></nav>}
export function FormField({label,error,required,helper,children}:{label:string;error?:string|undefined;required?:boolean;helper?:string;children:React.ReactNode}){const id=useId(),errorId=`${id}-error`,helperId=`${id}-helper`,child=React.isValidElement(children)?React.cloneElement(children as React.ReactElement<Record<string,unknown>>,{id,...(error?{'aria-invalid':true,'aria-describedby':errorId}:helper?{'aria-describedby':helperId}:{})}):children;return <label className="field" htmlFor={id}><span>{label}{required&&<b aria-hidden="true"> *</b>}</span>{child}{helper&&<small id={helperId} className="helper">{helper}</small>}{error&&<small id={errorId} className="field-error" role="alert">{error}</small>}</label>}
export function SearchInput(props:React.InputHTMLAttributes<HTMLInputElement>){return <div className="search-input"><Search size={17} aria-hidden="true"/><input type="search" {...props}/></div>}
export function PasswordInput(props:React.InputHTMLAttributes<HTMLInputElement>){const[visible,setVisible]=useState(false);return <div className="password-input"><input {...props} type={visible?'text':'password'}/><button type="button" aria-label={visible?'Sembunyikan password':'Tampilkan password'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>}
export function ImageUpload({currentUrl,alt,file,onChange,maxMb=2}:{currentUrl:string|undefined;alt:string;file:File|undefined;onChange:(file?:File)=>void;maxMb?:number}){const[preview,setPreview]=useState<string>(),[error,setError]=useState<string>();useEffect(()=>{if(!file){setPreview(undefined);return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);function select(next?:File){if(!next){setError(undefined);onChange();return}if(!['image/jpeg','image/png','image/webp'].includes(next.type)){setError('Foto harus berformat JPEG, PNG, atau WebP.');return}if(next.size>maxMb*1024*1024){setError(`Ukuran foto maksimal ${maxMb} MB.`);return}setError(undefined);onChange(next)}return <div className="image-upload"><div className="image-preview">{preview||currentUrl?<img src={preview??currentUrl} alt={alt}/>:<span aria-label="Belum ada foto">{alt.slice(0,2).toUpperCase()}</span>}</div><label className="button">Pilih foto<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>select(event.target.files?.[0])}/></label>{file&&<button type="button" onClick={()=>select()}>Batalkan pilihan</button>}<small>JPEG, PNG, atau WebP · maksimal {maxMb} MB</small>{error&&<small className="field-error" role="alert">{error}</small>}</div>}
export function DetailItem({label,value}:{label:string;value:React.ReactNode}){return <div className="detail"><small>{label}</small><strong>{value??'—'}</strong></div>}
export function Modal({title,open,onClose,children}:{title:string;open:boolean;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDivElement>(null),trigger=useRef<HTMLElement|null>(null);useEffect(()=>{if(open){trigger.current=document.activeElement as HTMLElement;ref.current?.focus();document.body.classList.add('modal-open')}else{document.body.classList.remove('modal-open');trigger.current?.focus()}return()=>document.body.classList.remove('modal-open')},[open]);if(!open)return null;function keys(e:React.KeyboardEvent){if(e.key==='Escape'){onClose();return}if(e.key==='Tab'){const nodes=[...ref.current!.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0]!,last=nodes[nodes.length-1]!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}return <div className="overlay" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" tabIndex={-1} ref={ref} onKeyDown={keys}><header className="modal-head"><h2 id="modal-title">{title}</h2><button aria-label="Tutup dialog" onClick={onClose}><X size={20}/></button></header><div className="modal-body">{children}</div></div></div>}
export function ConfirmDialog({open,title,description,busy,onConfirm,onClose}:{open:boolean;title:string;description:string;busy?:boolean;onConfirm:()=>void;onClose:()=>void}){return <Modal open={open} title={title} onClose={onClose}><p>{description}</p><div className="actions modal-actions"><button onClick={onClose} disabled={busy}>Batal</button><button className="danger" onClick={onConfirm} disabled={busy}>{busy?'Memproses…':'Ya, lanjutkan'}</button></div></Modal>}
export function CopyButton({value,label='Salin'}:{value:string;label?:string}){const[copied,setCopied]=useState(false);return <button type="button" onClick={()=>navigator.clipboard.writeText(value).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1600)})}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'Tersalin':label}</button>}
export function PermissionGate({allowed,children,fallback=null}:React.PropsWithChildren<{allowed:boolean;fallback?:React.ReactNode}>){return allowed?<>{children}</>:<>{fallback}</>}
type Toast={id:number;kind:'success'|'error'|'warning'|'info';message:string};const ToastContext=createContext<(message:string,kind?:Toast['kind'])=>void>(()=>undefined);export function ToastProvider({children}:{children:React.ReactNode}){const[list,setList]=useState<Toast[]>([]);function push(message:string,kind:Toast['kind']='success'){const id=Date.now()+Math.random();setList(v=>[...v,{id,kind,message}]);setTimeout(()=>setList(v=>v.filter(x=>x.id!==id)),3500)}return <ToastContext.Provider value={push}>{children}<div className="toasts" aria-live="polite" aria-atomic="true">{list.map(t=><div key={t.id} className={`toast ${t.kind}`} role="status">{t.message}</div>)}</div></ToastContext.Provider>}export const useToast=()=>useContext(ToastContext);
