export type PageMeta={page:number;perPage:number;total:number;totalPages:number};
export type ApiResponse<T>={success:boolean;message:string;data:T;meta?:PageMeta;errors?:Record<string,string[]>};
export class ApiError extends Error{constructor(message:string,public status:number,public errors?:Record<string,string[]>){super(message)}}

export function apiErrorMessage(status:number,serverMessage?:string){if(status===401)return'Sesi Anda telah berakhir. Silakan masuk kembali.';if(status===403)return serverMessage??'Anda tidak memiliki izin untuk melakukan tindakan ini.';if(status===429)return'Terlalu banyak percobaan. Tunggu sebentar lalu coba lagi.';if(status>=500)return'Terjadi gangguan pada server. Silakan coba kembali.';return serverMessage??'Permintaan tidak dapat diproses.'}

function cookie(name:string){return document.cookie.split('; ').find(value=>value.startsWith(`${name}=`))?.slice(name.length+1)}
let csrfRenewal:Promise<string>|undefined;
function renewCsrf(teacher:boolean){if(!csrfRenewal)csrfRenewal=(async()=>{const response=await fetch(`/api/v1/auth/${teacher?'teacher':'admin'}/csrf`,{credentials:'include',cache:'no-store'});if(!response.ok)throw new ApiError(response.status===401?'Sesi Anda telah berakhir. Silakan masuk kembali.':'Token keamanan tidak dapat diperbarui.',response.status);const body=await response.json()as ApiResponse<{csrf:string}>;return body.data.csrf})().finally(()=>{csrfRenewal=undefined});return csrfRenewal}

export async function api<T>(path:string,init?:RequestInit){const teacher=path==='/teacher'||path.startsWith('/teacher/')||path==='/auth/teacher'||path.startsWith('/auth/teacher/'),cookieName=teacher?'portal_teacher_csrf':'portal_csrf',mutating=!['GET','HEAD','OPTIONS'].includes((init?.method??'GET').toUpperCase()),isForm=init?.body instanceof FormData;let csrf=cookie(cookieName)||document.querySelector('meta[name="csrf-token"]')?.getAttribute('content');for(let attempt=0;attempt<2;attempt++){let response:Response;try{response=await fetch(`/api/v1${path}`,{...init,credentials:'include',cache:'no-store',headers:{...(isForm?{}:{'Content-Type':'application/json'}),...(csrf?{'X-CSRF-Token':decodeURIComponent(csrf)}:{}),...init?.headers}})}catch{throw new ApiError('Tidak dapat terhubung ke server. Periksa koneksi Anda.',0)}if(response.status===204)return{success:true,message:'Berhasil.',data:null}as ApiResponse<T>;const body=await response.json().catch(()=>({message:undefined,errors:undefined}));if(response.ok)return body as ApiResponse<T>;const csrfRejected=response.status===419||(response.status===403&&typeof body.message==='string'&&body.message.toLowerCase().includes('csrf'));if(csrfRejected&&mutating&&attempt===0){csrf=await renewCsrf(teacher);continue}throw new ApiError(apiErrorMessage(response.status,body.message),response.status,body.errors)}throw new ApiError('Token keamanan tidak dapat diperbarui.',419)}
